### ISSUE TITLE
The app is without icon when openned on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by raulgrangeiro** [ONLYOFFICE/DesktopEditors#1637] opened 2024-07-12 20:17 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.1.0.169

### Expected Behavior

The app showing icon on system bar when oppened.

### Actual Behavior

The app doesn't show icon on the system bar when oppened.

![Captura de tela de 2024-07-12 17-13-06](https://github.com/user-attachments/assets/0ac812fe-095c-4df8-b74f-e73af86841f4)

### Reproduction Steps

1. Install DEB version on Ubuntu 24.04 LTS
2. Open the app
3. See the problem

### Additional information

My system:

Notebook: Acer Aspire 5 A515-45-R6BL
CPU: AMD Ryzen 7 5700U
RAM: 20GB 3200MHz
SSD: 512 GB M.2

**Comment by XDmitryK** [comment] 2024-07-17 14:52
@raulgrangeiro Hi
I think this problem is similar to the issue #466

**Comment by raulgrangeiro** [comment] 2024-07-18 01:11
> @raulgrangeiro Hi I think this problem is similar to the issue #466

Good night. I don't think it is the same issue. If you see on the screenshot youcan notice the app is without icon on system's task bar.

**Comment by XDmitryK** [comment] 2024-08-13 10:28
@raulgrangeiro 
I apologize, I should have added a link to the comment. I already wrote below that this is a known issue under number #47886
https://github.com/ONLYOFFICE/DesktopEditors/issues/466#issuecomment-1924590265

**Comment by Rita-Bubnova** [comment] 2024-08-13 12:06
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/466#issuecomment-1924590265.

**Closed by Rita-Bubnova** 2024-08-13 12:06 UTC
Labels: duplicate

**Comment by raulgrangeiro** [comment] 2024-08-13 12:27
> @raulgrangeiro I apologize, I should have added a link to the comment. I already wrote below that this is a known issue under number #47886 [#466 (comment)](https://github.com/ONLYOFFICE/DesktopEditors/issues/466#issuecomment-1924590265)

Why didn't it happen when I was using on Ubuntu 23.10? It just appeared on Ubuntu 24.04 LTS.

**Comment by XDmitryK** [comment] 2024-08-13 14:55
@raulgrangeiro 
Fortunately, this does not happen on all systems. We have caught this bug on systems Debian 10\11 and Ubuntu 22.04.3\24.04

**Comment by raulgrangeiro** [comment] 2024-08-13 17:07
> @raulgrangeiro Fortunately, this does not happen on all systems. We have caught this bug on systems Debian 10\11 and Ubuntu 22.04.3\24.04

Interesting. I hope this can be fixed.

Thanks for answering me. God bless you!
