### ISSUE TITLE
Infinite load if delete file which trying to open

### ISSUE THREAD

**Issue by Xyz00777** [ONLYOFFICE/DesktopEditors#405] opened 2020-06-07 13:09 UTC
**Do you want to request a *feature* or report a *bug*?**
bug report

**What is the current behavior?**
if you delte a file while onlyoffice want to open it, only office get into a infinity open loop and can get only closed while killing the process over the task manager

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open a file and delete the file while onlyoffice opens it

**What is the expected behavior?**
it should say that it cant find the file and not try to open it (i let it try to open the file around 20minutes :D )

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.5.1.78 windows.
propably linux too? dont have a system too check

**Comment by Rita-Bubnova** [comment] 2020-06-09 07:49
Hello, @Xyz00777.
Sorry, I could not reproduce your problem. But @K0R0L able to reproduce the bug and he will fix this problem in the future.

**Comment by Rita-Bubnova** [comment] 2024-05-07 11:05
@Xyz00777, DesktopEditors v8.0.0 is released. Is this issue relevant?

**Comment by Xyz00777** [comment] 2024-05-08 00:30
im not using onlyoffice at the moment on windows, so cant really test it sorry.
When you thin its resolved i have nothing against closing it :)

**Comment by Rita-Bubnova** [comment] 2024-05-13 14:53
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-05-13 14:53 UTC
Labels: confirmed-bug, waiting feedback
