### ISSUE TITLE
Extremey slow app start on Ubuntu 19.10 and GNOME 3.34

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#268] opened 2019-10-18 10:09 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Too slow to start or open a document. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Install latest Ubuntu (19.10) and open ONLY Office.

**What is the expected behavior?**
Startup should be quick, like on past Ubuntu releases.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v 5.4.1

**Comment by XDmitryK** [comment] 2019-10-18 11:18
I'm confirm. I informed our developers.
Thanks for feedback.

**Comment by PJSingh5000** [comment] 2019-10-20 22:09
Experiencing the same issue on Ubuntu 19.10 and GNOME Shell 3.34.1.
I'm using vanilla Gnome shell.

It takes up to 40 seconds for the application to open after clicking on it in the Dock.

I've tried launching it from the terminal, but no errors are printed.

**Comment by EchedeyLR** [comment] 2019-10-24 18:35
I am experiencing the same issue in PureOS 9, GNOME 3.30.2.

I am using the snap version, no issues with other snap which open nearly immediately. The issue is not only to open the main menu but even open a document (new or already created) from the main menu. In the last case, it's more than a minute.

**Comment by janxkoci** [comment] 2021-08-06 19:27
Are you using the debian package, flatpak or snap? Snap was quite slow for me (although never 40s), while flatpak opens in about a second (I have an SSD).

**Comment by PJSingh5000** [comment] 2021-08-07 04:53
I no longer experience a long delay in Ubuntu 21.04.

**Comment by ShockwaveNN** [comment] 2021-08-09 07:32
@uncertainquark could you confirm that latest version is slow for you still or this problem is fixed?

**Comment by uncertainquark** [comment] 2021-08-09 08:43
I'm not on Linux anymore so can't confirm.

**Comment by ShockwaveNN** [comment] 2021-08-09 08:50
@uncertainquark Ok thanks, in that case I'll close this issue
If someone expereincing same issue and this is still actual (last report in 2019 year) - I think it's better to open new issue

**Closed by ShockwaveNN** 2021-08-09 08:50 UTC
Labels: bug
