### ISSUE TITLE
Installed fonts are not showing up in desktop editor 

### ISSUE THREAD

**Issue by dhrunia** [ONLYOFFICE/DesktopEditors#426] opened 2020-07-23 11:27 UTC
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
Fonts installed on system are not showing up in the desktop editor

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Install tff-mscorefonts-installer to install fonts like times new roman etc
2. Open desktop editor and create a new document
3. Check the fonts drop down menu for times new roman

**What is the expected behavior?**
Fonts installed on system should show up in the fonts drop down menu of the  desktop editor

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 5.5.1.78 (flatpak)
OS: Pop!_os 20.04

**Comment by ShockwaveNN** [comment] 2020-07-23 11:57
Seems like duplicate of https://github.com/flathub/org.onlyoffice.desktopeditors/issues/2

If not - please create new issue at flathub repo

**Closed by ShockwaveNN** 2020-07-23 11:57 UTC
