### ISSUE TITLE
Equation font automatically changes to Times New Roman when inserting a symbol by its shortcut

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#362] opened 2020-04-17 10:20 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
**What is the current behavior?**
In some document like the one I am attaching, when inserting an equation and when inserting a symbol by its shortcut inside this equation, the font automatically changes from Cambria Math to Times New Roman.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To reproduce:
1. Open the attached document: 
[Copernicus_Word_template.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/4492286/Copernicus_Word_template.docx)
2. Insert an equation in the document with <Alt>-<=>
3. Remark that the font is "Cambria Math" inside the equation
3. Type "\alpha" and then press <Space>.
4. The font has changed to "Times New Roman".

**What is the expected behavior?**
I think the font should not change.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.5.1

**Comment by Rita-Bubnova** [comment] 2020-04-17 11:46
Hello, @parrenin.
Thank you. I can confirm - this is a bug, issue 45205 in our internal issue tracker. 
Problem reproduces in Document Server.

**Comment by kbauer** [comment] 2021-05-03 10:40
As additional information: 
- The font doesn't switch to Times New Roman specifically, but to whatever font the surrounding text uses.
- The same issue seems to occur for auto-replacement of subscripts (`d_1` -> <i>d<sub>1</sub></i>).

**Comment by parrenin** [comment] 2022-04-08 13:27
It seems to me this issue has been fixed as of 7.0.2.

**Comment by parrenin** [comment] 2022-04-08 13:29
Oups, I wrote too quickly, this issue is still present in 7.0.2.

**Comment by Rita-Bubnova** [comment] 2023-02-01 15:36
The issue was fixed in version 7.3.0.

The problem was actually in Document Server.

**Comment by DenisDeeSign** [comment] 2023-02-01 17:57
DocumentServer and DesktopEditors v7.3.0 are released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by DenisDeeSign** 2023-02-01 17:57 UTC
Labels: bug, fixed
