### ISSUE TITLE
Please add file extensions in "Save as" types

### ISSUE THREAD

**Issue by JesseSteele** [ONLYOFFICE/DesktopEditors#954] opened 2022-06-12 08:41 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Please add file extensions in parentheses to the list of available file types in "Save as"

Office Open XML Document (.docx)
Word 97-2003 Document (for Legacy) (.doc) -- Need this, some publishers still use it, I use LibreOffice for this
Open Document Text File (.odt)
Open Document Document Template (.odf) -- "Document Document" ?
Open Document Template File (.odf) -- That's better
Rich Text Format File (.rtf)
Plain Text File (.txt)
Hyper Text Markup Language File (.html/.htm)
Electronic Publication File (.epub)
Portable Document (.pdf)

...et cetera.

I need to be sure which type of file I am saving something as, but of course the long names are also helpful.

**Comment by ShockwaveNN** [comment] 2022-06-12 08:47
I think this may be  a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/939

**Comment by ShockwaveNN** [comment] 2022-08-15 13:50
This issue was closed due to no response.

**Closed by ShockwaveNN** 2022-08-15 13:50 UTC
Labels: waiting feedback
