### ISSUE TITLE
ifs function returns error if any one of outputs are invalid

### ISSUE THREAD

**Issue by simonm3** [ONLYOFFICE/DesktopEditors#1020] opened 2022-09-17 09:40 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.7.1.57

### Expected Behavior

`=IFS(1=1,"correct",1=2,1/0)`

should produce output "correct" 

### Actual Behavior

shows div0 error

### Reproduction Steps

`=IFS(1=1,"correct",1=2,1/0)`

**Comment by VladimirProkofiev52** [comment] 2022-09-20 15:33
Hello!
@simonm3 , I can confirm - this is bug, issue 59117 in our private issue tracker.
Problem can be reproduced in DocumentServer.
Thank you for report.

**Comment by VladimirProkofiev52** [comment] 2023-02-01 13:30
@simonm3, The problem has been fixed in version 7.3.0. 
Please update your version of the editor.

**Comment by DenisDeeSign** [comment] 2023-02-01 13:52
Since version is released I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by DenisDeeSign** 2023-02-01 13:52 UTC
Labels: bug, fixed
