### ISSUE TITLE
Spreadsheet editor: No keyboard input accepted if mouse is outside the window and home window closed

### ISSUE THREAD

**Issue by IanHead** [ONLYOFFICE/DesktopEditors#1037] opened 2022-09-30 00:41 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.0.204

### Expected Behavior

With the spreadsheet editor window having focus, the application should continue to accept keyboard input no matter where the mouse cursor is situated on the screen.

### Actual Behavior

If a spreadsheet is open in its own window, and the OnlyOffice main (home) window is closed, then the spreadsheet editor will only accept keyboard input if the mouse pointer is sitting inside of it. See attached video for example (in this example, I am holding down the 'a' key while moving the mouse in and out of the window)

### Reproduction Steps

1. Open OnlyOffice Desktop Editors
2. Have Open File set to  'In its own window' (or tear off the document tab once created)
3. Create a new spreadsheet or open an existing one
4. Close the main OnlyOffice window
5. Test keyboard input with the mouse cursor sitting inside of the window
6. Test keyboard input with the mouse cursor sitting outside of the window

### Additional information

https://user-images.githubusercontent.com/12196401/193165860-8d28e822-ce6b-466b-b2d7-1400f2a63c5c.mp4

**Comment by lankthedank** [comment] 2023-01-04 13:25
I am having the same issue.

Package - 7.2.1.36 (flatpak from Flathub)
OS - Vanilla OS (based on Ubuntu 22.10) - however, I have replicated the issue on Fedora 36 and 37 using the same package format.

**Comment by Rita-Bubnova** [comment] 2023-01-04 14:22
Hello.
I checked this problem in ONLYOFFICE Desktop Editors version 7.2.1.36 on Windows 11 and I can't reproduce it. 
But we will check the issue on Linux OS.

**Comment by matveevms** [comment] 2023-01-12 11:37
Hello, @IanHead 
Thanks for the report. We are aware of this issue and have already fixed it in the next version. I can't say the exact release date yet.

**Comment by DenisDeeSign** [comment] 2023-02-01 10:32
DesktopEditors v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by DenisDeeSign** 2023-02-01 10:32 UTC
Labels: bug, fixed
