### ISSUE TITLE
[Feature Request] .webp support

### ISSUE THREAD

**Issue by Zunon** [ONLYOFFICE/DesktopEditors#1410] opened 2023-11-04 12:36 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I can't seem to be able to paste or insert webp images, and honestly I'm getting sick of converting any webp image I need to use to png before putting it into my document. Could we support it in addition to the other existing image formats?

**Comment by Rita-Bubnova** [comment] 2023-11-05 05:33
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2143.

**Closed by Rita-Bubnova** 2023-11-05 05:33 UTC
