### ISSUE TITLE
Multiple copies of the main window when opening files, with active Open documents in tab option (Ubuntu 20.04)

### ISSUE THREAD

**Issue by maxj97983** [ONLYOFFICE/DesktopEditors#1339] opened 2023-08-08 06:32 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

v7.4.1.36

### Expected Behavior

File should be safe after edit it and show the updated file.

### Actual Behavior

showing the warning dialog of "This file cannot be saved or created" when try to save the file after edit.

### Reproduction Steps

Steps to reproduce the error -
1. Open multiple files, after reboot the system.
2. Files will open in different windows. 
3. Close any one window.
4. Update the existing files and tried to save it.
5. warning dialog comes that says "This file cannot be saved or created".
6. Check the screenshot for the reference.

![FileCorrupt](https://github.com/ONLYOFFICE/DesktopEditors/assets/141709637/97bb6539-6728-444e-9090-70c760f9e662)

### Additional information

Please provide the solution to recover the corrupted files. And please correct this issue as soon as possible.

**Comment by LuckySpecialist** [comment] 2023-08-08 10:57
Hi @maxj97983!
To understand the problem, I need an exact scenario and sequence of actions from you:
- which files are opened
- where they are located
- where they are saved
- and other details...

From your description, I understood that the problem is when working with several files and saving changes to them, after which you received an error.
Sample files and videos demonstrating the problem will also greatly speed up the search for the problem.

**Comment by maxj97983** [comment] 2023-08-09 05:35
@LuckySpecialist ,
1. This issue occurs with all type of files like (docx,xlsx,pptx).
2. Files are stored in document folder but there is no specific location dependency.
3. I am saving the files on same location from where they opens.
4. This issue only occurs when i am trying to access the files just after reboot the system and file open in multiple windows.
5. There is no file size boundation. All types of file are corrupted after editing and trying to save. 
6. OS version Ubuntu 20.04 and Onlyoffice version is 7.4.1.36 (deb).
7.  For the demonstration, i am sharing the video.

https://github.com/ONLYOFFICE/DesktopEditors/assets/141709637/22fceb01-4523-4961-af25-2f97d9e73b40

If you need any other information, Feel free to ask.

**Comment by tejada-c** [comment] 2023-08-09 13:48
That is exactly the failure that has been happening to me with my students. I already reported it separately, but it is the same and you have given excellent details.

**Comment by LuckySpecialist** [comment] 2023-08-10 09:03
Hi @maxj97983, thanks for the video demonstrating the problem.
In the application `Settings`, you have the `Open file` option set to `In its own tab` - right?

**Comment by maxj97983** [comment] 2023-08-10 09:16
Hello @LuckySpecialist , 
Yes, All the settings of the application is set default. "**Open file**" options sets to "**In its own tab**".

**Comment by LuckySpecialist** [comment] 2023-08-10 09:55
In this case, the behavior of the application on the video is not normal. With the default settings, all documents should open in one main window.
I can't reproduce this behavior on my files - can you attach your examples?

**Comment by maxj97983** [comment] 2023-08-10 10:17
system specifications 
OS: Ubuntu 20.04.6 LTS x86_64 
Kernel: 5.15.0-78-generic 
CPU: Intel Xeon E5-1650 v4 (12) @ 4.000GHz 
GPU: NVIDIA Quadro K420 
Memory: 3148MiB / 31945MiB 

[file-sample_1MB.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/12311653/file-sample_1MB.docx)
[file_example_XLSX_5000.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/12311654/file_example_XLSX_5000.xlsx)

**Comment by LuckySpecialist** [comment] 2023-08-10 10:38
Do you have the system installed on HDD or SSD?

**Comment by maxj97983** [comment] 2023-08-10 10:46
My system is on HDD but this problem is same with SSD as well.

**Comment by LuckySpecialist** [comment] 2023-08-10 10:49
And where the system is installed on SSD files also open with multiple copies of the main window?

**Comment by maxj97983** [comment] 2023-08-10 10:56
Yes, files are open in different window with or without SSD.

**Comment by LuckySpecialist** [comment] 2023-08-10 11:03
And if you select all the files and press Enter, does the problem with opening multiple copies of the main window remain?

**Comment by maxj97983** [comment] 2023-08-10 11:07
No, at this time all files are opening in same window. But when i open all files with double click. Some files open in different windows.

**Comment by LuckySpecialist** [comment] 2023-08-10 11:35
And if you select each file in turn and press Enter?

I'm asking because so far I haven't been able to reproduce the problem with opening multiple copies of the main window on my systems, even with your files (it hardly depends on them).
So I'm trying to find a scenario in which I can reproduce the problem, because most likely this is the reason for the disputed files.
Maybe the @tejada-c will help with the script, if he also has several copies of the main window?

**Comment by maxj97983** [comment] 2023-08-10 12:04
You can try one more option to generate this issue.
1. Reboot the system.
2. Very frequently Click on single file.
3. If same file opens in two window, then close one of them and try to edit the other one and save it.
4. It will show the same warning dialog and file will become zero byte.


This issue generates only when different window is open, and close one of them. 
May be you are trying to edit the files without closing the one window.

**Comment by LuckySpecialist** [comment] 2023-08-10 12:29
So the problem is not repeated either...
If you have two copies of the main window open with one file, this is what we need to fix, but we can't repeat it. One file should not be opened twice.

**Comment by maxj97983** [comment] 2023-08-10 12:35
So in that case, Is there any way to recover the files data if it is corrupted ??
Because data loss is really very big issue. And i lost my important file.

**Comment by LuckySpecialist** [comment] 2023-08-10 12:41
The problem is that the file is written empty, judging by your words. Therefore, there is nothing to restore there. If it had not been saved, the data would have ended up in the Recovery section.
The problem is very unpleasant - I agree. It is not possible to repeat it yet...

**Comment by maxj97983** [comment] 2023-08-11 05:05
This problem typically arises when two windows are opened for either the same or distinct files. It is plausible that this complication is associated with the creation of temporary files during the process of file opening.

Can you open some files in different windows?

**Comment by LuckySpecialist** [comment] 2023-08-11 07:14
In general, initially I checked on a virtual machine with Ubuntu 22.04.
Then I tried on a real Ubuntu 23.04. Perhaps you need a certain configuration with a set of installed applications to reproduce this. I will look for other configurations and try.

**Comment by maxj97983** [comment] 2023-08-11 11:12
@LuckySpecialist 
Can you please try in Ubuntu 20.04 version. With given configuration above.

**Comment by LuckySpecialist** [comment] 2023-08-11 15:47
The problem was reproduced on Ubuntu 20.04, I passed the problem to the developers. Bug 59389 was issued earlier, now it is open again.
Thanks for the feedback.

**Comment by sskdv** [comment] 2023-08-23 10:50
Good afternoon. Please tell me, was it possible to solve or defeat the problem with saving files? The case when when saving a file it becomes zero in size?!

**Comment by LuckySpecialist** [comment] 2023-08-30 11:01
Hi @sskdv, if you have the same problem as described in the issue, it is likely that to get around it, you do not need to run multiple copies of the application and wait for a fix in the future.
If your scenario is different, you need to open a new issue.

**Comment by tejada-c** [comment] 2023-11-13 16:37
My boss had an important file corrupted by this same bug and I had to recommend another application to work with because he was very disappointed.
OnlyOffice is beautiful and an excellent project, but that error of opening a file twice in different windows and corrupting it is something that needs to be corrected soon. Greetings

**Comment by LuckySpecialist** [comment] 2024-01-29 09:03
The problem has been fixed in [this commit](https://github.com/ONLYOFFICE/desktop-apps/commit/1d330c2e1fb65e3cb902d6fb29284a3d9e6bef99) and will be included in the next release.

**Comment by Rita-Bubnova** [comment] 2024-02-01 08:40
Desktop Editors v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-02-01 08:40 UTC
Labels: confirmed-bug, fixed-release
