### ISSUE TITLE
Add other option for "Interface scaling"

### ISSUE THREAD

**Issue by korongmambu** [ONLYOFFICE/DesktopEditors#699] opened 2021-08-16 06:49 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Like title said, add other option for "Interface scaling" like 50%, 75%, 110%, 120%, 125%, etc. It's a good feature for user convenience.

**Comment by ShockwaveNN** [comment] 2021-08-16 07:07
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/699

We are planning to add 125% and 175% in near future release, but currently we are not thinking about other scaling from your list, because for each scale we need to make separate icons and I'm not sure that 120% and 125% scale difference really worth a work

**Comment by korongmambu** [comment] 2021-08-21 18:08
> Duplicate of #699

If this is a duplicate. Can you provide the correct reference, because the reference issue you provided is mine.

> We are planning to add 125% and 175% in near future release, but currently we are not thinking about other scaling from your list, because for each scale we need to make separate icons and I'm not sure that 120% and 125% scale difference really worth a work

Cool, when this going to be release?

**Comment by ShockwaveNN** [comment] 2021-08-23 07:29
Oops sorry, wrong issue

Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/664

And more precise - issue 47624 in our private issue tracker

>Cool, when this going to be release?

Sorry, we cannot guarantee any time frame - it'll be released as soon as it be ready

**Comment by ShockwaveNN** [comment] 2021-08-23 07:30
Oo

**Comment by ShockwaveNN** [comment] 2021-08-23 07:30
I can leave this issue opened for discussion of other scales but I really do not know situation in which you need 120% scale and not 125%

**Comment by korongmambu** [comment] 2021-08-23 07:56
> I can leave this issue opened for discussion of other scales but I really do not know situation in which you need 120% scale and not 125%

Not particulary need actually, just give some examples. Also I think it's ok to have 25% difference for each scale, at least not to small like 100% and not to big like 150% in my case.

**Comment by ShockwaveNN** [comment] 2021-08-23 08:05
In that case I think we should close this issue and any discussion (if any question is still not answered) better to continue  in #664

**Closed by ShockwaveNN** 2021-08-23 08:05 UTC
