### ISSUE TITLE
Default font used by the ui of ONLYOFFICE can't display some Chinese characters

### ISSUE THREAD

**Issue by Nyaacinth** [ONLYOFFICE/DesktopEditors#990] opened 2022-08-08 08:03 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.1.1 (533)

### Expected Behavior

Display characters correctly

### Actual Behavior

Display blocks instead of the character

### Reproduction Steps

Open ONLYOFFICE;
Change the language to Chinese (中文);
Open a document and look at the toolbar;
Find out the problem.

### Additional information

“常规”:
https://imgur.com/a/9Ew0B6n
The app window:
https://imgur.com/a/TL9jE2O

**Comment by ShockwaveNN** [comment] 2022-08-08 08:18
Hi, is this default empty document from `/example` or some other document you've opened?

**Comment by Nyaacinth** [comment] 2022-08-08 08:38
> Hi, is this default empty document from `/example` or some other document you've opened?

No matter the document opened, the problem is the font used by user interface

**Comment by ShockwaveNN** [comment] 2022-08-08 08:43
For me this page looking fine, maybe some fonts are missing on your host system?
![image](https://user-images.githubusercontent.com/668524/183377434-12e7b689-f8c0-414b-ab33-d2e3f9b34548.png)


Could you try to check this page on some other systems, on Linux or Windows?

**Comment by Nyaacinth** [comment] 2022-08-08 08:55
> For me this page looking fine, maybe some fonts are missing on your host system? ![image](https://user-images.githubusercontent.com/668524/183377434-12e7b689-f8c0-414b-ab33-d2e3f9b34548.png)
> 
> Could you try to check this page on some other systems, on Linux or Windows?

Just installed on Arch Linux, and it looks normal, no errors, no blocks
https://imgur.com/a/Hlyz3nM

Maybe it's a platform specific issue? The problem still exists on macOS.

**Comment by Gingetsu** [comment] 2022-08-08 10:34
Hello, @Nyaacinth.
I can confirm - this is bug and you're right it's related to #415. We discuss this issue with our development team (issue 54118 in our internal issue tracker). Thank you for report.

**Comment by ShockwaveNN** [comment] 2022-08-08 10:38
Thanks for your report, but I'll close it as duplicate of #415

**Closed by ShockwaveNN** 2022-08-08 10:38 UTC
