### ISSUE TITLE
presenter: wrong monitor settings

### ISSUE THREAD

**Issue by paolo119922** [ONLYOFFICE/DesktopEditors#1197] opened 2023-02-05 15:44 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.0

### Expected Behavior

in presentation mode with a dual display, the display 2 should show the presentation in full screen, and the display 1 (primary, on PC) should show the notes

### Actual Behavior

the presentation stays on PC primary monitor 1, and the presenter view with my notes opens on extended 2. 
obviously it must work the other way around...

### Additional information

win 11, monitor 1920x1080, hdmi connection with smart tv.

**Comment by Rita-Bubnova** [comment] 2023-02-13 08:44
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/285.

**Closed** 2023-02-13 08:47 UTC
Labels: duplicate
