### ISSUE TITLE
Arabic / Urdu Text is not rendered correctly when opening existing files

### ISSUE THREAD

**Issue by Mohsyn** [ONLYOFFICE/DesktopEditors#981] opened 2022-07-28 20:48 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

ONLYOFFICE Desktop Editors version 7.1.1.57

### Expected Behavior

Urdu/Arabic alphabets/text changes form depending on where in the word it appears.
OnlyOffice spreadsheet when opening a file with multilingual text in it should render it how the system normally renders such text.

### Actual Behavior

Urdu/Arabic utf-8 text is not rendered correctly and shows up as broken individual characters.

### Reproduction Steps

Open any excel file with urdu/arabic text 
Please note that copy paste some text from web into onlyoffice spreadsheet does not break the text characters, only opening an existing file has this issue.

**Comment by ShockwaveNN** [comment] 2022-07-29 07:20
I think it's a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

If not - please share some files with incorrect rendering (if it's not related to RTL)

**Comment by ShockwaveNN** [comment] 2022-08-30 15:26
This issue was closed due to no response.

**Closed by ShockwaveNN** 2022-08-30 15:26 UTC
Labels: waiting feedback
