### ISSUE TITLE
The font isn't rendering properly.

### ISSUE THREAD

**Issue by SMSourov** [ONLYOFFICE/DesktopEditors#621] opened 2021-05-15 05:01 UTC
**Do you want to request a *feature* or report a *bug*?**
It is a bug. 

**What is the current behavior?**
It isn't rendering the font properly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open ONLYOFFICE Editors > DOCUMENT and type "আমার সোনার বাংলা। আমি তোমায় ভালোবাসি।" (My golden Bengal. I love you.). You can also copy and paste the text. The appropriate font for writing this without installing any font is Nirmala UI.

**What is the expected behavior?**
The text should look like this.
![image](https://user-images.githubusercontent.com/81343486/118348426-0d598c80-b56c-11eb-9a0a-5629162d21a2.png)

**What is the actual behavior?**
BROKEN!
![image](https://user-images.githubusercontent.com/81343486/118348439-27936a80-b56c-11eb-9452-ab1f5e13e542.png)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I'm using Windows 10, version 20H2, build 19042.985(including all latest updates at the time of reporting this bug). The version that is affected with the problem is 6.2.0.148(latest version at the time of reporting this bug). I haven't tested the previous versions.

**Comment by Rita-Bubnova** [comment] 2021-05-19 12:57
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/732.

**Closed** 2021-05-25 08:18 UTC
Labels: duplicate
