### ISSUE TITLE
Printed PDF is rasterized

### ISSUE THREAD

**Issue by eldelacajita** [ONLYOFFICE/DesktopEditors#600] opened 2021-04-21 07:34 UTC
**Do you want to request a *feature* or report a *bug*?**
I'd say it is a bug, but I may be wrong.

**What is the current behavior?**
When printing a document to PDF, it rasterizes the content, creating a needlessly big file and losing the ability to select or edit text. The exported file does also display clearly visible banding, due to the raster being cut in slices.

This doesn't happen on Windows with Microsoft Print to PDF and Adobe PDF printers, but it also doesn't happen on Linux with any other program and the same printer, so it seems to be an issue between ONLYOFFICE and that printer. Maybe wrong default settings?

Using "save as PDF" does not show this issue, but it is _not a feasible replacement_ with spreadsheets, as it doesn't respect the page settings and page jumps, generating a very messy document.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Go to File/Print
2. Select "Print to File" (PDF)
3. Check the printed file. 

**What is the expected behavior?**
It should print a light, non-rasterized PDF where contents are selectable and editable. 

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

ONLYOFFICE Desktop Editors version 6.2.0.148 on Manjaro Linux

**Comment by Rita-Bubnova** [comment] 2021-04-21 14:14
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/481.

**Closed** 2021-04-21 14:17 UTC
Labels: duplicate

**Comment by eldelacajita** [comment] 2021-04-21 14:36
Sorry for the duplicate, I searched but didn't find that issue.
