### ISSUE TITLE
Arrow keys do not work in presentation mode

### ISSUE THREAD

**Issue by bdaase** [ONLYOFFICE/DesktopEditors#130] opened 2018-07-22 15:26 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Arrow keys, space and enter are not working during presentation to step through the slides. 
Furthermore F5 does not start a presentation, ESC does not close it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just create a new presentation and try to launch it (the button for that works)!

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Ubuntu 18.04 (completely fresh installation), 5.1.29.350

**Comment by Rita-Bubnova** [comment] 2018-07-23 08:33
Hello, @BjoernDaase.
Thank you. I can confirm - this is a bug, issue 38283 in our internal issue tracker.

Start the presentation mode by pressing the Ctrl + F5 keys.
For more information on the operation of hot keys, see Help ("File" -> "Help" -> "Keyboard shortcuts").

**Comment by Julvenzor** [comment] 2023-02-26 00:58
Hi! This bug is still present in version 7.3. The workaround is not easy to discover for basic users. This situation forces you to use the mouse wheel to move the slides and it may limit the use of your program for teaching activities.

Regards.

**Comment by ElenaMaaya** [comment] 2024-08-12 14:19
Hello, @bdaase! Thanks for your report! The problem is fixed and not repeated in Desktop Editor version  8.1.1 on Windows 11 and Kubuntu 24.04. Please update Desktop Editor. If the problem persists, please write here again.

**Comment by Rita-Bubnova** [comment] 2024-08-13 08:34
DesktopEditors v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-08-13 08:34 UTC
Labels: confirmed-bug, fixed
