### ISSUE TITLE
OnlyOffice randomly corrupts any file worked from flash drive

### ISSUE THREAD

**Issue by tejada-c** [ONLYOFFICE/DesktopEditors#1325] opened 2023-07-20 21:19 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.4

### Expected Behavior

OnlyOffice should work normally when opening a file from a USB flash drive and it should be able to save the changes without any errors or corruption of the file that was changed.

### Actual Behavior

OnlyOffice randomly corrupts any file worked from flash drive, in version 7.4 for Ubuntu. If he doesn't notice the error message when he tries to save it and doesn't save it under another name, OnlyOffice corrupts all the original file, losing all the information that the file had, which only appears as plain text, with 0 bytes of storage space.

Corrupted file sample:
[ACTIVIDAD INTEGRADORA TRIMESTRE II.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/12114015/ACTIVIDAD.INTEGRADORA.TRIMESTRE.II.docx)

### Reproduction Steps

1. Open a text or presentation file with OnlyOffice, from a usb flash memory.
2. Edit it for a bit
3. Then paste an image from the internet
4. Finally, click save.
5. Randomly, the error may occur. It doesn't always come up.

**Comment by janxkoci** [comment] 2023-08-01 22:30
Or it could just be a wonky flash drive / USB port. I have several flash drives with weird quirks - some of them don't work in any computer other than mine, for example :shrug: And one fancy Sandisk I bought in Germany disconnects some 10 minutes after I plug it in, almost every time I try to use it - €40 out the window.

**Comment by janxkoci** [comment] 2023-08-07 14:46
@matveevms Sorry, but I never said I have the issue. In fact, I think it's more likely the issue is with OP's hardware (a flashdrive) rather than with OnlyOffice.

**Comment by tejada-c** [comment] 2023-08-09 13:37
I work with several students throughout the day, and every class I have, at least three students get this error. It's not that the memory is damaged, because most of them use new memories and it doesn't always happen to the same person. It's a random error, but I haven't identified the exact reason. We all work with Ubuntu 22.04 LTS.

**Comment by tejada-c** [comment] 2023-08-09 13:50
to see details of this bug, go to this link https://github.com/ONLYOFFICE/DesktopEditors/issues/1339

**Comment by sskdv** [comment] 2023-08-23 11:16
Good afternoon. Please tell me, was it possible to solve or defeat the problem with saving files? The case when when saving a file it becomes zero in size?!

**Comment by matveevms** [comment] 2023-09-13 14:30
Hello, @sskdv 
If your problem is not related to the flash drive, you need to open a new issue.
Thank you in advance.

**Comment by Rita-Bubnova** [comment] 2023-09-13 14:56
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-09-13 14:56 UTC
Labels: invalid
