### ISSUE TITLE
appimage v8.0 is not have?

### ISSUE THREAD

**Issue by newyorkthink** [ONLYOFFICE/DesktopEditors#1498] opened 2024-02-08 01:03 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

latest

### Expected Behavior

appimage

### Actual Behavior

appimage

**Comment by matveevms** [comment] 2024-02-08 13:22
This issue is a duplicate of https://github.com/ONLYOFFICE/appimage-desktopeditors/issues/56.
Appimage 8.0.0 will be available in the coming days.

**Comment by Rita-Bubnova** [comment] 2024-02-08 13:27
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-02-08 13:27 UTC
Labels: duplicate
