### ISSUE TITLE
[Feature Request] Swap Presenter View and Slide Show

### ISSUE THREAD

**Issue by JonathanLindsey** [ONLYOFFICE/DesktopEditors#597] opened 2021-04-10 22:47 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Opening Presenter View displays the windows on the wrong screens for our setup and there is apparently no way to swap the windows from within OnlyOffice.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Add a button in the presenter view and possibly a setting to swap which window is on which screen. OnlyOffice should remember the configuration on a per machine basis.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 6.2.0.148 on Windows 10 1909.
I have not tried other versions or platforms.

**Comment by Rita-Bubnova** [comment] 2021-04-12 14:07
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/285.

**Closed** 2021-04-12 14:30 UTC
Labels: duplicate
