### ISSUE TITLE
Spelling- isn't it?

### ISSUE THREAD

**Issue by Iangh59** [ONLYOFFICE/DesktopEditors#1605] opened 2024-06-16 22:22 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

version 8.0.1.31 (deb)

### Expected Behavior

The spelling is wrong. **Isn't** is correct but shows as an error in OO. **Is n't** is not correct. There is no space between n't and the verb. 

### Actual Behavior

See above.

### Reproduction Steps

Write is n't and isn't.

### Additional information

N/A

**Comment by Rita-Bubnova** [comment] 2024-06-17 10:13
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/576.

**Closed by Rita-Bubnova** 2024-06-17 10:13 UTC
