### ISSUE TITLE
Portable version for Microsoft Windows

### ISSUE THREAD

**Issue by SimoLRepo** [ONLYOFFICE/DesktopEditors#1125] opened 2022-11-21 22:33 UTC
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hi, I need a portable version of ONLYOFFICE for Microsoft Windows. This is due not so much to any use on other PCs but to the fact that no data is left in other folders. Is it possible to create a launcher that allows this? Thank you.

**Comment by ShockwaveNN** [comment] 2022-11-22 06:50
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/151

**Closed by ShockwaveNN** 2022-11-22 06:50 UTC
