### ISSUE TITLE
Bullet lists display with random symbols as the bullet points

### ISSUE THREAD

**Issue by evind** [ONLYOFFICE/DesktopEditors#546] opened 2021-01-06 16:51 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
OnlyOffice is displaying incorrect bullet points in bullet lists.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I just installed OnlyOffice via [this AUR package](https://aur.archlinux.org/packages/onlyoffice-bin/), created a document (tested both .docx & .odt), then created a bullet list. The bullet points were some kind of left arrow/bracket. See the following screenshot. I tested out each available bullet type option and they are all wrong (except for the empty bullet circle and line). I have a feeling this may be some font/dependecy issue but was unsure where to post for help so I came here first.

![screenshot](https://i.imgur.com/uPFgVKr.png)

**What is the expected behavior?**
The selected symbol to be used for each item in the bullet list.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
OnlyOffice DesktopEditor 6.1.0-1
Arch Linux 5.9.14-arch1-1-vfio

**Comment by HectorB-2020** [comment] 2021-01-06 19:44
I guess I've reproduced this behavior on Windows version  6.1.0.90.
Still I'm not confident it's the same as you are describing.

My steps are the following. Though maybe this is an expected behavior of the program.

Assume we have a few lines of text and made them a bullet list of a certain kind.
Then we select one line and try changing its bullet style to different.
As a result all the lines got that style instead of only one line. 

![OO17](https://user-images.githubusercontent.com/64358003/103813065-8a31a280-5070-11eb-84b7-f73dc0928c03.png)

**Comment by evind** [comment] 2021-01-06 23:15
That is the case for me as well. It's not the issue I'm describing however. I should clarify that in my screenshot I have 8 separate lists each with a different symbol selected: black dot first, empty dot second, square third, and so on.

![gif](https://i.imgur.com/78hUhgh.gif)

**Comment by HectorB-2020** [comment] 2021-01-07 09:38
@evind, right, this is different. Yours is even more amazing. :astonished:
Let's wait what OnlyOffice rep is going to say. Based on their response I'd submit a separate case.

**Comment by matveevms** [comment] 2021-01-12 14:30
Hi, @evind 
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/501.

**Closed** 2021-01-12 14:31 UTC

**Comment by matveevms** [comment] 2021-01-12 14:53
Hi, @HectorB-2020 
Your problems are different. Could you please create a new issue?
