### ISSUE TITLE
Asian typography handling

### ISSUE THREAD

**Issue by Jisu-Woniu** [ONLYOFFICE/DesktopEditors#1439] opened 2023-12-04 10:51 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

In the current version of OnlyOffice (I am using Linux version on Arch Linux), the spaces between Chinese text and Western text (e.g. English) is not adjusted as in Microsoft Office and other document editors, this results in weird layout outcome. Also the line break does not work as expected.

This is the result in OnlyOffice:

![The result in OnlyOffice](https://github.com/ONLYOFFICE/DesktopEditors/assets/31986081/7ab68c85-60e2-4550-8f27-5cb634309d93)

This is the result in Microsoft Office (in my Windows 11 VM):

![The result in Microsoft Office](https://github.com/ONLYOFFICE/DesktopEditors/assets/31986081/d53756ed-0472-4d2d-bc46-48d03c29c137)

Microsoft Office has this setting specially for Asian typography:

![In Chinese](https://github.com/ONLYOFFICE/DesktopEditors/assets/31986081/029927af-f333-42f5-82e4-044c0dc4227b)

... and in English:

![In English](https://github.com/ONLYOFFICE/DesktopEditors/assets/31986081/1f76f284-ccc4-42c4-b50e-1517fb9e2dcc)

**Comment by ElenaMaaya** [comment] 2023-12-05 15:41
Hi @Jisu-Woniu ! Thank you for contacting us!
This is a known Bug 57262 in our  issue tracker.
Problem reproduces in Document Server.

**Comment by Rita-Bubnova** [comment] 2023-12-05 15:45
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2504.

**Closed by Rita-Bubnova** 2023-12-05 15:45 UTC
