### ISSUE TITLE
List Formatting Lost on Close (after a successful save)

### ISSUE THREAD

**Issue by rgdev-1134** [ONLYOFFICE/DesktopEditors#1447] opened 2023-12-19 21:13 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package), Linux (RPM package)

### Version information

7.5.1.23 (and the prior 2-3 versions also)

### Expected Behavior

Lists default to being formatted with a space. When changed to a tab and saved, the document should open with the list formatted using a tab. 

### Actual Behavior

I changed the format on the list from a space to a tab, saved the document, closed it and re-opened. All changes saved except the list formatting, which was defaulted back to a space. 

### Reproduction Steps

1. Create a new document.
2. Create a list in the document.
3. Change the indent character to a tab (under right click > Adjust list indents).
4. Save the document and close it.
5. Re-open and see that the space character is used for the list, not the tab character.

### Additional information

Also, IMO, the default should be a tab, not a space. Using a space causes the text to not be aligned if more than one line is entered which looks unprofessional.

**Comment by matveevms** [comment] 2023-12-20 11:06
Hello, @rgdev-1134.
The problem was previously reproduced in the same way on DocumentServer.
This case will be fixed in the next release.
Thanks for your feedback.

**Comment by Rita-Bubnova** [comment] 2024-02-01 08:39
Desktop Editors v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-02-01 08:39 UTC
Labels: confirmed-bug, fixed-release
