### ISSUE TITLE
Page Border on Documents

### ISSUE THREAD

**Issue by muraleekrishnan4** [ONLYOFFICE/DesktopEditors#806] opened 2022-01-16 21:14 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

**Operating System**
Linux

**Version information**
6.4.2.6

**Software**
OnlyOffice Document

**Expected Behavior**
Create a page border on each page (just as the Page border in MS Word). This is a very basic feature most of us needs.

**Actual Behavior**
OnlyOffice Document has a similar border feature which puts a border on each paragraph, image, etc. If we split the paragraph into two pages, it can break the border also. Also, the content size decides the border size.

**Screenshot of feature I want:**

![image](https://user-images.githubusercontent.com/63204975/149678269-6858f800-d289-4039-ab20-28f38f7bc4e6.png)

`Copyrights of above Image: YouTube - Learn Basics`

**Screenshots of Issue**
_Breaking the border:_
![image](https://user-images.githubusercontent.com/63204975/149678104-1495c4a5-d775-44cf-9212-2d7a2219144d.png)

_Size of the content decides the Page Border:_
![image](https://user-images.githubusercontent.com/63204975/149678126-bbc41bde-28ae-459a-8a60-54a946375221.png)

**Comment by ShockwaveNN** [comment] 2022-01-17 07:09
Hi, this is duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1407

**Closed by ShockwaveNN** 2022-01-17 07:09 UTC
