### ISSUE TITLE
being able to have link started with a+ in mailto:myemail+blabla@corps.com

### ISSUE THREAD

**Issue by JOduMonT** [ONLYOFFICE/DesktopEditors#922] opened 2022-05-18 04:34 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

mailto:myemail+blabla@corps.com don`t work
while mailto:myemail@corps.com

**Comment by TatianaKirillova** [comment] 2022-05-18 13:02
Hello, [@](https://github.com/michal-barteczko)[JOduMonT](https://github.com/JOduMonT)
Thanks for your request!
I can confirm that the problem exists. I created ticket 57221 in our private  tracker with your issue.
Problem reproduces in Document Server.

**Comment by TatianaKirillova** [comment] 2023-02-01 12:09
Hello, @JOduMonT!
Problem fixed. Please update your version of desktop editor to version 7.3.0.

**Comment by DenisDeeSign** [comment] 2023-02-01 12:10
Since version is released I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by DenisDeeSign** 2023-02-01 12:10 UTC
Labels: bug, fixed
