### ISSUE TITLE
DesktopEditors blurry on Gnome with fractional scaling 

### ISSUE THREAD

**Issue by d3vilguard** [ONLYOFFICE/DesktopEditors#1415] opened 2023-11-10 08:55 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.5.0

### Expected Behavior

On Gnome (Wayland) when fractional scaling is enabled, the application should scale to 125% without the interface and displayed documents being blurry.

### Actual Behavior

In it's current state, when fractional scaling is applied globally in Gnome (125%) the application does scale to 125% (100% in application's settings for scaling) but it's a blurry mess. 

### Reproduction Steps

1. Have Gnome 45 (Wayland) and enable fractional scaling
2. Set to enable fractional scaling `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`
3. Open gnome's display settings and choose 125% scaling
4. Open DesktopEditors
5. Observe UI elements and displayed documents in glorious blur

### Additional information

1920x1080 screen on a 13.3" notebook. 
Application scale is fine with no blur on KDE Wayland when scaling to 125% is applied globally on the desktop. 
At this state the application is unusable because of the blur on Gnome with fractional scaling, and the latter is unusable on a 13.3 notebook with no scaling enabled.

**Comment by Pshemas** [comment] 2023-11-11 12:07
the same on my end. This leads me to ditch OnlyOffice for time being, until fix / workaround shows up. It seems OnlyOffice (flatpak version) opens in Xwayland, not a true Wayland session. Tried forcing it but no success so far - each time I disabled access to X11 I got:

```
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```
Tried also following variables:

QT_QPA_PLATFORM=wayland
QT_SCALE_FACTOR=1
XDG_SESSION_TYPE=wayland
GDK_SCALE=1

**Comment by d3vilguard** [comment] 2023-11-11 12:45
@Pshemas
thought it could be flatpak so went ahead and tried the RPM before opening a report here.

**Comment by matveevms** [comment] 2023-11-13 13:00
Hello @d3vilguard 
Thank you for report!
I can confirm that the problem exists. I created ticket 65078 in our issue tracker with your issue.

**Comment by matveevms** [comment] 2023-11-20 15:14
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/561.

**Closed** 2023-11-20 15:21 UTC
Labels: confirmed-bug, duplicate
