### ISSUE TITLE
=TEXT(…;"TTT") isn't correctly evaluated after opening a document

### ISSUE THREAD

**Issue by lal12** [ONLYOFFICE/DesktopEditors#1190] opened 2023-02-02 16:35 UTC
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (Deb package)

### Version information

7.2.1.36

### Expected Behavior

After opening a document the `=TEXT(…;"TTT")` fields should correctly be displayed.

### Actual Behavior

After opening a document the `=TEXT(…;"TTT")` fields will display `TTT`.

### Reproduction Steps

- Write a date e.g. `21.02.2023` into A2
- Add `=TEXT(A1;"TTT")` into B2, it should now display the Weekday
- Save the document
- Close the document tab
- Open the saved document again
- Instead of the Weekday it will display `TTT` until double clicking and pressing enter

### Additional information

I use Arch Linux, the .xlsx format and German language settings.

**Comment by alinasafonova** [comment] 2023-02-15 15:15
Hello, @lal12

This issue is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/1138
Thank you for report.

**Closed** 2023-02-15 15:20 UTC
Labels: duplicate
