### ISSUE TITLE
[Bug] Hebrew text renders LTR instead of RTL

### ISSUE THREAD

**Issue by biggles5107** [ONLYOFFICE/DesktopEditors#819] opened 2022-01-20 17:36 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.0.127, Pop!_OS 21.10

### Expected Behavior

The Hebrew text in the attached document should display right-to-left in line with the English text (here just a transliteration of the Hebrew). The correct rendering is shown on the right side of the screenshot in LibreOffice.

[hebrew test.odt](https://github.com/ONLYOFFICE/DesktopEditors/files/7907269/hebrew.test.odt)

### Actual Behavior

OnlyOffice (left) displays the Hebrew text left-to-right, making the Hebrew unreadable. Setting the language to Hebrew does not make a difference, nor does having the Hebrew be the only thing on the line.

![gnome-shell-screenshot-d7dt5w](https://user-images.githubusercontent.com/7585954/150390376-dfa651d2-476b-467a-9c73-a829114c3c5b.png)

### Reproduction Steps

1. Type some English text.
2. Without pressing <kbd>Return</kbd>, switch to a Hebrew keyboard and type some Hebrew.
3. Observe that the Hebrew does not render right-to-left as it should.

### Additional information

Example was made using SBL Hebrew font (not necessary to reproduce the bug) and SIL Hebrew keyboard (maybe necessary to reproduce the bug?). Both are freely available.

**Comment by biggles5107** [comment] 2022-01-20 17:41
Using the native Hebrew keyboard makes no difference.

**Comment by MehdiChinoune** [comment] 2022-01-21 04:28
https://github.com/ONLYOFFICE/DocumentServer/issues/19

**Comment by ShockwaveNN** [comment] 2022-01-21 07:52
Sorry, but we're not supporting RTL right now

We're working on it but it very complicated problem and we cannot provide any time frame for a solution

Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

**Closed by ShockwaveNN** 2022-01-21 07:52 UTC
