### ISSUE TITLE
Add "Paste as Plain Text" hotkey

### ISSUE THREAD

**Issue by LeBrick-Studio** [ONLYOFFICE/DesktopEditors#1160] opened 2022-12-15 08:21 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Add an option to paste text without any copied formatting by `Ctrl+Shift+V`, which is a very common and well-known combination:

![изображение](https://user-images.githubusercontent.com/93297305/207808618-ac6f44b4-c563-4658-b9fd-b7070e4a0db4.png)
Chrome

![изображение](https://user-images.githubusercontent.com/93297305/207808643-3b7e5a5f-025a-4614-bedb-de68b6cff5d9.png)
Edge

![изображение](https://user-images.githubusercontent.com/93297305/207808689-b0462903-eae3-4d91-a5a8-f096bf9f7584.png)
Google Docs

**Comment by HectorB-2020** [comment] 2022-12-16 10:26
Oh man, people have been asking for this for ages. :smiling_face_with_tear: 
* https://github.com/ONLYOFFICE/DesktopEditors/issues/165
* https://github.com/ONLYOFFICE/DesktopEditors/issues/468
* https://github.com/ONLYOFFICE/DesktopEditors/issues/525
* https://github.com/ONLYOFFICE/DocumentServer/issues/1002
* https://github.com/ONLYOFFICE/DocumentServer/issues/1582
* https://github.com/ONLYOFFICE/DocumentServer/issues/1633
* https://github.com/ONLYOFFICE/DesktopEditors/issues/843
However I would personally prefer MS Word way of "Paste special", `Ctrl`-`Shift`-`V` is reserved there for other nice stuff.

**Comment by Rita-Bubnova** [comment] 2022-12-19 10:00
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1002. 

The issue actual in Document Server.

**Closed** 2022-12-19 10:09 UTC
Labels: duplicate
