### ISSUE TITLE
OnlyOffice does not get the focus when opening a subsequent file on Linux

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#587] opened 2021-03-22 15:59 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
When OnlyOffice is already open and you open a new file using the file manager, OnlyOffice opens the file in the background but does not get the focus.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* open OnlyOffice
* go to the file manager (e.g., dolphin, nautilus)
* open an OOXML file

**What is the expected behavior?**
OnlyOffice opens the file in the background but does not get the focus

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
DE 6.2.0 on Debian Bullseye / X11 / KDE

**Comment by Iangh59** [comment] 2021-03-23 07:02
As an aside Libreoffice also does not get focus on Linux when opening another file. I'm using Kubuntu. Could it be OS related?

**Comment by parrenin** [comment] 2021-03-23 08:04
I don't think it is OS related.
There was the same problem with gedit, but then the gedit developers fixed it.
So it seems there is something to do at the app level.

**Comment by matveevms** [comment] 2021-03-24 07:36
@parrenin
Thank you for report.
I can confirm - this is bug, issue 49255 in our private issue tracker.

**Comment by parrenin** [comment] 2022-04-08 13:22
Still present in 7.0.2.

**Comment by HectorB-2020** [comment] 2022-11-25 20:29
@parrenin & @Iangh59 I guess something similar is observed on Windows as well. Though not sure the root cause is the same.
I reported an issue #1052 as well as some other guys: #921

**Comment by parrenin** [comment] 2024-01-31 13:07
This bug seems to be fixed in 8.0.0.

**Comment by Rita-Bubnova** [comment] 2024-02-01 13:07
This has been fixed ([ONLYOFFICE/sdkjs@12e7079](https://github.com/ONLYOFFICE/desktop-apps/commit/1cd2f8b7ae99caaffa62f4971e7fe378435a4ab6))  in the version 8.0.0.

DesktopEditors v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-02-01 13:07 UTC
Labels: confirmed-bug
