### ISSUE TITLE
[Feature request] UI customize

### ISSUE THREAD

**Issue by nguyenkien** [ONLYOFFICE/DesktopEditors#454] opened 2020-09-08 15:16 UTC
A little customize to save vertical space
![Screen Shot 2020-09-08 at 22 09 15](https://user-images.githubusercontent.com/1940081/92495041-a20f2c00-f220-11ea-80c6-7de26414ada0.png)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
MacOS Catalina, Desktop app

**Comment by janxkoci** [comment] 2021-07-23 08:25
I think it makes more sense to put the action buttons left to the ribbon instead of the tabs. This way they stay in the same context (quick actions next to full actions, tabs next to other tabs).

And to see the document's name the tabs could be made a little wider (tooltip on hover could be also used in addition).

**Comment by ShockwaveNN** [comment] 2021-07-23 10:26
@Medanna please take a look

**Comment by Medanna** [comment] 2021-08-03 16:17
Hi @nguyenkien , @janxkoci , thank you for your ideas. There are several situations when such toolbar is needed, for example, to see file name and current user's profile. But for those users who needs a simple toolbar, we will add an option to switch to a compact toolbar view.

**Comment by Rita-Bubnova** [comment] 2023-08-25 07:27
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/646.

**Closed by Rita-Bubnova** 2023-08-25 07:27 UTC
Labels: duplicate
