### ISSUE TITLE
"Subscript" shortcut overlap with "zoom in" shortcut.

### ISSUE THREAD

**Issue by chaq094** [ONLYOFFICE/DesktopEditors#105] opened 2018-04-25 06:16 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Both subscript mode and zoom in function are triggered when pressing Crtl + Plus sign (+).

**Which versions of DesktopEditors?**
DesktopEditor version 4.8.7.392

**Which OS are affected by this issue?**
Ubuntu 16.04

**Comment by ShockwaveNN** [comment] 2018-04-25 07:09
Yeah, thanks, seems this is a bug, cannot reproduce on any system, but reproduces as you mention on my pc. Created an issue in external bug tracker (#37577)

**Comment by ShockwaveNN** [comment] 2018-12-22 09:00
Version 5.2.4 of DesktopEditors was released and issue should be fixed.

**Closed by ShockwaveNN** 2018-12-22 09:00 UTC
Labels: bug
