### ISSUE TITLE
Store formatting style settings globally

### ISSUE THREAD

**Issue by Heiss** [ONLYOFFICE/DesktopEditors#838] opened 2022-01-28 12:23 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hey,

i cannot found any related issue to this. Also i think that this is a desktop only feature, because web versions should not store something like this (maybe?).

My suggested feature is:
If i change or add a new formatting style in only office, it is only stored and loaded in a document file. So if you change the formatting style in one document, open up a new one, the changes of the formatting styles will not be copied over or are available (for new created one) for style selection. So you need to do this style changes over and over again for multiple documents and new documents.
This would add a more user-friendly behaviour to OnlyOffice, because i think that this is a feature, people uses a lot from other software.

I hope this is possible to implement.

**Comment by ShockwaveNN** [comment] 2022-01-28 14:25
I think it's duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1071

I agree with you that on cloud solution it may be harder to implement, but currently, we have a little activity on this for both DesktopEditors or DocumentServer so I'll mark it as duplicate

Thanks for your report anyway

**Closed by ShockwaveNN** 2022-01-28 14:25 UTC
