### ISSUE TITLE
Scrollbars in DesktopEditor windows on High DPI display

### ISSUE THREAD

**Issue by silicahd** [ONLYOFFICE/DesktopEditors#136] opened 2018-08-15 04:43 UTC
I think this is a bug. Also I cant even find a way to add the --force-scale=2 argument  as the onlyoffice desktop is missing from usr/shared/desktop

any ideas? I know this is because of the high dpi i just cant figure out how to increase it to 200

https://ibb.co/d9wvMU
![image](https://user-images.githubusercontent.com/668524/60588215-00c85280-9d9f-11e9-8a95-88173496fcc0.png)

**Comment by ShockwaveNN** [comment] 2018-08-15 07:35
@virgiltu could you correctly fill issue template, also note your monitor resolution

**Comment by virgiltu** [comment] 2018-08-15 17:38
Tried everything, does not seem to work at all. On windows it works great only Ubuntu seems to have this issue on the same computer.

**Comment by ShockwaveNN** [comment] 2018-08-15 17:44
@virgiltu https://github.com/ONLYOFFICE/DesktopEditors/issues/136#issuecomment-413118253 still actual

**Comment by ShockwaveNN** [comment] 2018-08-24 07:05
@virgiltu While you creating new issue this form is shown https://github.com/ONLYOFFICE/DesktopEditors/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by graynk** [comment] 2018-11-20 07:39
For me it's like this:
Behavior is shown on the screenshot in the first post, editors don't not fill the whole window, no matter the size.
Steps to reproduce: open DesktopEditors.
Expected behavior: content fills the whole window.
Desktop editors version: 5.1.29.350. OS: KDE Neon 5.14 (based on Ubuntu 18.04). I have two monitors, main one is 2560x1440, the secondary is 1920x1080. Don't know if the issue was in previous versions, it's my first time installing Editors.

**Comment by ShockwaveNN** [comment] 2019-07-03 11:31
Same issue https://github.com/ONLYOFFICE/DesktopEditors/issues/225

**Comment by ddshore** [comment] 2019-07-15 15:00
I had this same problem on a previous version of onlyoffice.  Just upgraded today to version 5.3.95.43 and can confirm the problem is exactly the same as before.   Attaching a screenshot.  Also have HiDPI display. 

![image](https://user-images.githubusercontent.com/171169/61226053-5f6ac600-a6e7-11e9-8c15-bc9ab55b36dc.png)

**Comment by hoshi411** [comment] 2019-07-27 05:40
Me too
![onlyoffice](https://user-images.githubusercontent.com/8462696/61990480-647f2c00-b07c-11e9-9094-1df15fb52c1f.png)

Surface Pro 3 Ubuntu 18.04 KDE Neon

**Comment by umasse** [comment] 2019-08-07 12:49
One more here. Manjaro KDE, OnlyOffice editors freshly installed.
![image](https://user-images.githubusercontent.com/4088459/62624086-94eb8380-b922-11e9-8495-4caa695c6a4d.png)

**Comment by niciuffo** [comment] 2019-10-14 22:13
Same issue:
Arch Linux + KDE, 15 inch 4k display

Default behavior (editor takes up 1/4 of the screen):
![default](https://user-images.githubusercontent.com/8481428/66786259-1130b300-eee0-11e9-9f0a-237b9e5aea38.png)
`QT_FONT_DPI=163 QT_SCREEN_SCALE_FACTORS=1 QT_SCALE_FACTOR=1 onlyoffice-desktopeditors` (editor takes up all the screen, still tiny):
![font+scaling](https://user-images.githubusercontent.com/8481428/66786261-1130b300-eee0-11e9-83f0-370be07f8e34.png)
`QT_FONT_DPI=163 QT_SCREEN_SCALE_FACTORS=1 QT_SCALE_FACTOR=1 onlyoffice-desktopeditors --force-scale=2` (properly scaled):
![font+scaling+force_scale](https://user-images.githubusercontent.com/8481428/66786262-1130b300-eee0-11e9-906d-ae9eba317a7e.png)

There are still some issues while scrolling, with weird flashes, but at least it's usable.

**Comment by JediBrooker** [comment] 2019-10-22 02:30
I can confirm that QT_FONT_DPI=163 QT_SCREEN_SCALE_FACTORS=1 QT_SCALE_FACTOR=1 onlyoffice-desktopeditors --force-scale=2 works on Manjaro KDE opening in the terminal. However, how do I make it so it works clicking on the icon in the menu? I edit the menu item and put that command in but it exits immediately. I edit the .desktop file with the same result.

**Comment by piiarp** [comment] 2020-02-04 10:33
Confirm solution:
`QT_FONT_DPI=163 QT_SCREEN_SCALE_FACTORS=1 QT_SCALE_FACTOR=1 onlyoffice-desktopeditors`
works for me on Pop! OS + KDE Plasma 1920x1080 without the need for `--force-scale=2`

**Comment by ShockwaveNN** [comment] 2021-10-08 08:42
Hi, is this issue still actual, we made a lot of changes since 2020 in handling HiDPI

If so, please state 

1. Your host os
2. Version of DesktopEditors and method of installation
3. Your monitor size in inches
4. Your display resolution

**Comment by DenisDeeSign** [comment] 2022-12-09 15:23
Closing the issue since there were no new reports during the past year. Feel free to open new issue if got any new troubles.

**Closed** 2022-12-09 15:23 UTC
Labels: bug
