### ISSUE TITLE
Right click context menu from slide locks up the active document editor

### ISSUE THREAD

**Issue by eSavior** [ONLYOFFICE/DesktopEditors#1261] opened 2023-04-01 09:50 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.x

### Expected Behavior

When I right click a slide thumbnail in the left column to bring up the context menu, I expect to be able to select a menu option and not have the whole document editor lock up. I also expect to not have to open the Windows Task Manager and force quit the "editors_helper" process that seems to be chewing up CPU cycles in an endless loop of some sort.

### Actual Behavior

What actually happens is the context menu displays, but then the whole document editor locks up for the active presentation document. After closing the whole Desktop Editors application, a process still remains running in the background called "editors_helper" and it is consuming a lot of CPU cycles that cause my computer's fan speed to noticeably increase.

### Reproduction Steps

Open the attached document in any OnlyOffice 7.3.x version:
[20230401 BSF Leader's Meeting (draft).pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/11128981/20230401.BSF.Leader.s.Meeting.draft.pptx)

Select slides 8-11 in the left hand column. Right click on any of the selected slides to bring up the context menu.  

### Additional information

This issue happens on multiple Windows machines that I have access to. One is a custom build desktop running the latest current version of Windows 10 21H2, another is an Asus laptop running Windows 11. I also use Desktop Editors 7.3.x on a macOS 10.14.x (Mojave) machine, but cannot replicate the issue on that platform.

Only current workaround I have is to go back to Desktop Editors 7.2.1, where the issue does not manifest.

**Comment by LuckySpecialist** [comment] 2023-04-13 22:29
Hi, @eSavior!
I can't reproduce your problem on 3 of my PCs (Windows 10/11 Pro 22H2 x64).
Do you have version 21H2 on all PCs?
Have you tried reinstalling the app?
_Please note that during the installation you did not have any processes running from ONLYOFFICE Desktop Editors (including editors_helper.exe )._

**Comment by eSavior** [comment] 2023-04-14 09:58
Was editing my presentation just now in OnlyOffice Desktop Editors 7.2.1 on Windows 10 21H2 and the problem just happened again (before, I thought this issue only applied to Desktop Editors 7.3.x). 

This time, I right clicked on the endlessly CPU consuming editors_helper.exe file in Task Manager and created a process dump file. I am not skilled enough to load these into WinDbg to determine what might be locking up in the process, but maybe someone more technical than myself can use this to see why the Desktop Editors process is confused and going into an endless loop. The dump file is too large to load into GitHub, so here is a link to the dump file (link expires 7/13/2023):
https://drive.proton.me/urls/MXX2TY8GVW#lmcup3ytqbnn

I will try installing Desktop Editors on a Windows installation that has never had it installed before and see what happens. It will need to wait a few days as I have pressing projects right now. Thanks for helping with the investigation into this issue!

**Comment by eSavior** [comment] 2023-04-17 01:58
Installed a Win10 22H2 VM tonight and also could not reproduce the issue in OnlyOffice Desktop Editors 7.3.x. I think there may be some other steps required to get the issue to reproduce, such as editing the file directly from my NextCloud drive folder (my normal use case). Will post the next time this happens.

**Comment by LuckySpecialist** [comment] 2023-04-17 09:11
Thanks for the reply.
Tell me which version of Nextcloud you have installed and I will try to reproduce the problem?

**Comment by eSavior** [comment] 2023-04-17 11:24
Hi, Denis. I got this information from the General tab on the Nextcloud Settings panel:

Nextcloud Desktop Client
Version 3.8.0 (Windows). For more information please click [here](https://docs.nextcloud.com/desktop/3.8/).

Using virtual files plugin: wincfapi

windows-10.0.19044

Hope this helps to reproduce the issue. I doubt that it matters, but my Nextcloud server is hosted with murena.io.
------- Original Message -------

**Comment by eSavior** [comment] 2023-04-18 19:41
Hi, Denis. While I know it's possible to use the "Connect to cloud" feature in the Desktop Editors software, I don't actually do that. I just use the Nextcloud Desktop Client to sync the files to my local disk, as one would typically do with a DropBox, Google Drive, or Microsoft OneDrive cloud drive sync app.

As far as murena.io is concerned, I'm just a customer, so I don't know what version of Nextcloud they have deployed there. I can probably track that information down if necessary, it would just require some cooperation on their support part. From my perspective, I've noticed they seem to keep the server side software reasonably up-to-date as there is downtime and obvious new features deployed every several months.

Since I don't use the "Connect to cloud" feature of the Desktop Editors, I doubt that it matters what version of Document Server they are running...but it might. Just say the word and I'll contact their support to try and get that information.

Thanks again for striving to get to the bottom of this interesting issue!

**Comment by LuckySpecialist** [comment] 2023-04-21 09:29
OK, thanks for the clarifications.
I will try to reproduce the problem and report the result later

**Comment by LuckySpecialist** [comment] 2023-04-21 13:46
I tried to repeat the problem...
For this:
On my Windows 11 Pro 22H2 system (OS Build 22621.1555), I installed Nextcloud Desktop Client 3.8.1 (Windows), using virtual files plugin: winpcap, windows-10.0.22621 and connected with it to my Nextcloud server version 24.0.12.
Uploaded your file to the sync directory with Nextcloud and opened this document using ONLY OFFICE Desktop Editor 7.3.3.50 (x64 exe).
Next, according to your scenario, in the presentation editor, I selected slides 8 to 11 on the thumbnail panel and opened the context menu. The menu opened correctly.
Have you tried updating the OS and the Nextcloud client?

**Comment by eSavior** [comment] 2023-04-23 10:06
Hi, Denis. I've got deadlines again so I'll probably be able to take a closer look on my Windows 11 machine on Tuesday, 4/25.

I might not have been clear in the original bug report, but the context menu also displays on my machines when the bug happens, but at that point, everything is frozen in the presentation editor tab and you have to close it out forcefully as you can no longer interact with anything in the editor for that document. This also includes not even being able to select an item on the context menu.

I think you probably would have noticed this, though. Just wanted to make sure that you didn't close it out before you tried to actually select one of the menu items :-)

------- Original Message -------

**Comment by LuckySpecialist** [comment] 2023-04-24 07:58
In this case, a video demonstration of the problem would be very useful.

**Comment by eSavior** [comment] 2023-04-25 07:42
Before we go down the video demonstration route, I think I have just absolved Nextcloud of any responsibility with further testing. 

I created a new local user account in my Windows installation and could *not* reproduce the issue from that account. So this problem may be more due to some leftover scraps of user configuration info from previous OnlyOffice DesktopEditors versions I had been running on this machine. 

I have uninstalled and reinstalled OnlyOffice DesktopEditors on multiple occasions, but it does not clear up the issue on my primary user account. Please let me know if there are some instructions for manually removing all traces of the OnlyOffice DesktopEditors from the local user account and I will see if that clears up this problem once and for all.

**Comment by LuckySpecialist** [comment] 2023-04-25 13:24
The folder contains the application settings for working with portals and files for recovery, so they remain when the application is deleted. For the sake of a single case, I think it makes no sense to deal with the problem.
If the problem turns out to be massive and easily reproducible, it's worth it. If you have a scenario for your case - write. We will definitely review and try to fix it in future releases.

Thanks for the feedback.

**Comment by eSavior** [comment] 2023-04-25 13:32
Roger that. The problem has been manifesting itself to me for almost half a year now, so it’s definitely a big deal to me :-) But until others come in on this thread to say they’re having the same issue, I agree that I must be an unusual case. Good news is that I know how to work around the problem now!

**Comment by LuckySpecialist** [comment] 2023-08-01 11:19
Since the problem does not repeat, we close the issue.
If it happens again, you can open it again.

**Closed** 2023-08-01 11:21 UTC
