### ISSUE TITLE
Ctrl+Backspace not working

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#161] opened 2019-01-15 08:37 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Ctrl+Backspace doesn't delete the entire word as it should and does across all operating systems.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Write something, use "Ctrl+Backspace" to delete an entire word. It doesn't work, only a single character is deleted.

**What is the expected behavior?**
Should delete an entire word.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v5.2.4

**Comment by ShockwaveNN** [comment] 2019-01-15 10:20
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/161

**Closed by ShockwaveNN** 2019-01-15 10:20 UTC

**Comment by uncertainquark** [comment] 2019-01-16 03:13
You mean to say duplicate of #152? You have linked to bug #161, which is this same bug report.

**Comment by ShockwaveNN** [comment] 2019-01-16 06:56
@uncertainquark yes, of course, sorry
