### ISSUE TITLE
When editing existing .pdf file Ctrl+S shortcut does nothing

### ISSUE THREAD

**Issue by Ephirion** [ONLYOFFICE/DesktopEditors#1688] opened 2024-09-27 17:52 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

8.1.1.27 (rpm)

### Expected Behavior

When editing an existing .pdf document pressing Ctrl+S should save changes, like it does when saving an existing .docx file.

### Actual Behavior

Currently pressing Ctrl+S while editing existing .pdf files does nothing.

### Reproduction Steps

1. Get any .pdf file that wasn't created in ONLYOFFICE like this sample pdf
[sample-pdf-file.pdf](https://github.com/user-attachments/files/17167817/sample-pdf-file.pdf)
2. Open it, make changes, press Ctrl+S
3. Observe that the file isn't saved

**Comment by TatianaKirillova** [comment] 2024-10-07 14:45
Hello @Ephirion !
Thanks for reaching out! The issue is fixed and will be included in the next release.  Don't miss updates. Have a nice day!

**Comment by Rita-Bubnova** [comment] 2024-10-08 05:39
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2835.

**Closed by Rita-Bubnova** 2024-10-08 05:39 UTC
Labels: confirmed-bug, fixed-release
