### ISSUE TITLE
`--system-title-bar` on 125-175% zoom broke button locations

### ISSUE THREAD

**Issue by sergeantbl** [ONLYOFFICE/DesktopEditors#929] opened 2022-05-26 16:33 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hey everyone,

I'm using OnlyOffice and I was wondering if it's possible to use the minimize/ maximize/ close button of the Linux Mint UI. 

Linux Mint version: 20.3 Cinnamon; Cinnamon version 5.2.7

**OnlyOffice buttons** 
![OnlyOffice_buttons](https://user-images.githubusercontent.com/78814465/170531849-6a1fec83-106f-4330-a7bf-d220b66d1c1f.png)

**KeepassXC buttons**
![KeepassXC_buttons](https://user-images.githubusercontent.com/78814465/170531853-0776db98-44dc-463d-aabc-2d80511081a3.png)

Best,

**Comment by ShockwaveNN** [comment] 2022-05-27 14:40
Hi, could you check how it will look with `onlyoffice-desktopeditors --system-title-bar` launch param

(You can revert it back with `--custom-title-bar` call)

**Comment by sergeantbl** [comment] 2022-05-27 16:42
Hey @ShockwaveNN thanks for the reply. It goes in the right direction but the result is not satisfying

![OnlyOffice_with_system_bar](https://user-images.githubusercontent.com/78814465/170742575-9072cdc3-49b4-4341-9f8d-95ebac1af805.png)

**Comment by ShockwaveNN** [comment] 2022-05-29 19:39
@sergeantbl To be clear - you like the button styles but there is something wrong with the layout, am I right

Because I can reproduce problem with the layout in the left part of the window on my Kubuntu system

**Comment by sergeantbl** [comment] 2022-05-30 12:05
Exactly I like the button styles but the rest is misaligned. I guess the chaos is caused by the OnlyOffice button in the top left.

**Comment by ShockwaveNN** [comment] 2022-05-31 11:49
We already got an issue 56515 about strange behavior in left part

There is workaround - you can change interface zoom in DesktopEditors settings to 100% or %200 and the problem is gone

But we'll try to fix for other zoom levels in future

**Comment by ShockwaveNN** [comment] 2022-05-31 15:42
This issue is fixed in https://github.com/ONLYOFFICE/desktop-apps/commit/c083f09df972a214e1cf27ee2e392007d78cb45d and will be released in next major release

**Comment by sergeantbl** [comment] 2022-05-31 21:15
Thank you! Really cool that I as a normal user can participate in the improvement of your software. Much looking forward to the next release.

Best wishes from Berlin

**Comment by ShockwaveNN** [comment] 2022-09-23 16:16
DesktopEditors v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions

**Closed by ShockwaveNN** 2022-09-23 16:16 UTC
Labels: bug, fixed
