### ISSUE TITLE
Save as... in the Mac File Menu is saving the current document and not saving as a new document

### ISSUE THREAD

**Issue by 2bmade** [ONLYOFFICE/DesktopEditors#1321] opened 2023-07-05 06:07 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.4 (539) Apple Silicon

### Expected Behavior

When I use the MacOS menu (or shortcut) to save a document as a new document ("Save As..") OO should save the current open document as a new document asking for a location and file name.

### Actual Behavior

When I use the MacOS menu to save a document as a new document ("Save As..") OO will save the current open document. The shortcut shift+cmd+S works as expected.

### Reproduction Steps

1. open an existing document
2. choose "Save As..." from the menu bar

**Comment by Gingetsu** [comment] 2023-07-05 09:20
Hello, @2bmade !
I can't reproduce your problem. Could you attach a video for a better understanding of the problem, please?

**Comment by 2bmade** [comment] 2023-07-05 11:45
https://github.com/ONLYOFFICE/DesktopEditors/assets/94042657/07afb9ba-253e-4efd-bba5-836cb7cdf79b

**Comment by kimbostroem** [comment] 2023-07-12 07:26
I confirm this bug. I tried it on two different machines, one Silicon, one Intel, both current MacOS system, and in both cases "Save As" does not do anything visibly. No dialog box appears to save the document somewhere. It seems the document is simply saved as if I had clicked "Save", which is unexpected behavior.

**Comment by kimbostroem** [comment] 2023-07-12 07:27
This applies to Writer and Worksheet documents. Haven't tried the others, though.

**Comment by RolandBBerlin** [comment] 2023-08-13 12:33
Just tested Version 7.4.1 (540) on Apple Silicon - the bug ist still there. This applies to all types of documents, tested document, spreadsheet, presentation and form templates.

**Comment by maruacat** [comment] 2023-10-02 09:05
Hello @2bmade 
I have great news. We've fixed this issue https://github.com/ONLYOFFICE/web-apps/commit/54293818b966b48503477c1d7cfdf89900ec292e and it should work fine in the new version of the editor.
Have a good day!

**Comment by Rita-Bubnova** [comment] 2023-10-19 11:21
DesktopEditors v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-10-19 11:21 UTC
Labels: confirmed-bug, fixed-release
