### ISSUE TITLE
The spell checker no longer works

### ISSUE THREAD

**Issue by Piscatorius** [ONLYOFFICE/DesktopEditors#356] opened 2020-04-14 17:16 UTC
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.
**What is the current behavior?**
I am using the App OnlyOffice Desktop Editors on an iMac (21.5-inch, Late 2013) under macOS Catalina 10.15.4. On Thursday, April 9, 2020 I received the update to version 5.5.1. I am really happy that an annoying bug has finally been fixed: Fonts installed by the user himself can now finally be used again. Since the installation of the new version, however, a new bug has crept into the program: In version 5.5.1 the spell checker unfortunately no longer works.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The error occurs every time I want to create a new document or open an existing document. Incorrectly written words are not recognised, which means that spelling mistakes are not underlined in red. Changing the text language or the document language has no effect on the spell checker function. In the advanced settings the spell checker is turned on.
**What is the expected behavior?**
I expect the spell checker to work as it did in the previous version. Incorrectly spelled words have been underlined in red by the spell checker so far. In the new version, it no longer does so.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Version 5.5.1 of the OnlyOffice Desktop Editor for Mac is affected by this problem. I am using the app on an iMac (21.5-inch, Late 2013) under macOS Catalina 10.15.4. In the previous version 5.4.2 the spell checker was still working.

**Comment by DenisDeeSign** [comment] 2020-04-15 08:28
Hello, @Piscatorius.
Can you specify what option is set primary in System Preferences > Language & Region > Preferred Languages?

**Comment by Piscatorius** [comment] 2020-04-15 10:48
Hello @DenisDeeSign,
Thank you for your reaction. My system language settings under System Preferences > Language & Region > Preferred Languages are as follows: 1 – Dutch (primary language), 2 – English, 3 – German; Region: Netherlands.

**Comment by DenisDeeSign** [comment] 2020-04-16 10:22
@Piscatorius, thank you for your report.
I can confirm - this is a bug, issue 45182 in our internal issue tracker.

**Comment by Piscatorius** [comment] 2020-04-16 11:54
Hello @DenisDeeSign,
Thank you for the confirmation.

**Comment by thomas-mac** [comment] 2020-05-13 00:17
This bug is caused by an int64 identifier truncated to 32 bits. It has already been fixed in the repository, but for some reason the Mac desktop version is not built from the 5.5.1 source tree.

Until a new version is released, you can fix this yourself. 
Install the Mac version of ONLYOFFICE 5.5.1 to the Applications folder and run it, test if the bug is really still there, if so, quit ONLYOFFICE, download [onlyoffice.txt](https://github.com/ONLYOFFICE/DesktopEditors/files/4619076/onlyoffice.txt), save it to your Downloads folder and use the following command in a Terminal to patch ONLYOFFICE:

xxd -r ~/Downloads/onlyoffice.txt /Applications/ONLYOFFICE.app/Contents/Frameworks/libascdocumentscore.dylib

(If you get a "permission denied" error, make sure you're logged in as an administrator, and if it still doesn't work, use "sudo" in front of the command [sudo xxd...].)

Restart the app and the spell checker should work again.

**Comment by thomas-mac** [comment] 2020-05-15 08:33
If you are on macOS 10.14 or later, you also have to resign the app for the patch to work. Use this command in a Terminal:

codesign -f -s- --deep /Applications/ONLYOFFICE.app

If you don't have the necessary developer tools installed, macOS will offer to download them at this point.

**Comment by klocus** [comment] 2020-06-10 10:38
I can confirm that @thomas-mac solution works!

**Comment by Piscatorius** [comment] 2020-07-31 10:12
Good news: Yesterday I received the update to version 5.6.0. After installing the new version the spell checker finally works again.

**Closed** 2020-07-31 10:18 UTC
Labels: bug
