### ISSUE TITLE
Not connect to cloud where custom port used (8080 and 8083)

### ISSUE THREAD

**Issue by ww7** [ONLYOFFICE/DesktopEditors#577] opened 2021-03-09 18:50 UTC
MobileEditors works, but DesktopEditors can't connect to OnlyOffice community installation where used custom port.

We point to example.com:8080 but DesktopEditors trying to reach 80 port

**Comment by DenisDeeSign** [comment] 2021-03-26 16:08
Hello @ww7,
what exactly did you run on port 8080? Onlyoffice CommunityServer or some DMS, e.g. Nextcloud?

**Comment by ww7** [comment] 2021-04-19 01:28
We run OnlyOffice on customized ports 8080 and 8443, as 80 and 443 used by Apache.
This issue on macOS OnlyOffice application, what can't connect to our server where non-default port used.
![](https://files.ww7.work/screen/tmp/Screenshot%202021-04-19%20at%2004.24.03.png)

**Comment by DenisDeeSign** [comment] 2021-04-20 16:11
I was unable to reproduce the issue with SSL connection on customized port, but reproduced with non-secure connection and created the issue 49784 in our private issue tracker.

**Comment by DenisDeeSign** [comment] 2023-04-25 15:13
The issue is finally fixed by https://github.com/ONLYOFFICE/desktop-sdk/commit/b71c354dc50858402398b15578f5751b9410d0c5 and fix will be available in the next major release.

**Comment by DenisDeeSign** [comment] 2023-06-15 09:18
DesktopEditors v7.4.0 are released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by DenisDeeSign** 2023-06-15 09:18 UTC
Labels: bug, fixed
