### ISSUE TITLE
Dark background is not applied to styles

### ISSUE THREAD

**Issue by mikhailnov** [ONLYOFFICE/DesktopEditors#1156] opened 2022-12-11 19:50 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

0

### Expected Behavior

.

### Actual Behavior

.

### Reproduction Steps

I choose a dark theme and a dark background of a text document:

![image](https://user-images.githubusercontent.com/15802528/206925453-9d2d0d6f-dee7-4e2d-9f4d-af5f1a2dfaa1.png)

But background of styles names is still white:

![2022-12-11_22-47](https://user-images.githubusercontent.com/15802528/206925427-7cdcc483-3834-4104-860f-6f42b2560e59.png)

It is not good because it hirts eyes a bit (and I have to use the styles panel to apply styles to text frequently).

**Comment by mikhailnov** [comment] 2022-12-11 19:51
oops, it should be in the document server, I think, please move this issue if needed

**Comment by HectorB-2020** [comment] 2022-12-12 09:28
@mikhailnov, there are plenty of topics regarding dark themes. 
Please read discussion in #1047.

**Comment by mikhailnov** [comment] 2022-12-12 09:37
> @mikhailnov, there are plenty of topics regarding dark themes. Please read discussion in #1047.

ok, thanks

**Comment by Rita-Bubnova** [comment] 2023-08-15 15:51
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/1047.

**Closed by Rita-Bubnova** 2023-08-15 15:51 UTC
