### ISSUE TITLE
Change document defaults in the app

### ISSUE THREAD

**Issue by mjh8431** [ONLYOFFICE/DesktopEditors#1629] opened 2024-07-06 18:53 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

OnlyOffice needs a way to change the document settings, e.g. margins, tabs, line spacing, fonts, etc. in the app. The current method of copying the new.*x file from ../converter/empty/en_US to another location, opening OnlyOffice, making the changes, and then copying the file back to ../converter/empty/en-US is a pain. Plus, every time there is an update to OnlyOffice the process has to be repeated. If it was part of the internal configuration it could be a one-and-done setting. MSWord and LibreOffice both have this ability, as do several other office suites. With how long OnlyOffice has been around and how popular it is, this should be implemented.

**Comment by TatianaKirillova** [comment] 2024-08-08 19:53
Hello,  @mjh8431 
Thanks for your request!
I can confirm - this is know bug, issue #47180 for your problem.

**Comment by mjh8431** [comment] 2024-08-08 20:12
Hopefully, someone is working on it. This is a big drawback to using OnlyOffice as a daily driver. On a Mac, it is a small inconvenience because copying the default file is relatively easy, but in linux it is a major inconvenience because of linux permission conventions.

This really needs to be a priority fix.

-----------------------------
Martin Harris
***@***.***

**Comment by Rita-Bubnova** [comment] 2024-08-09 08:25
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/746.

**Closed by Rita-Bubnova** 2024-08-09 08:25 UTC
Labels: feature request
