### ISSUE TITLE
Auto resize multiple columns

### ISSUE THREAD

**Issue by mcanepa** [ONLYOFFICE/DesktopEditors#595] opened 2021-04-07 19:53 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
I select all cells in spreadsheet by clicking on the button between column A and row 1, then double click on the border between column A and B for example, then column A gets auto resize based on column A content

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I would expect to having all columns to autoresize, since I select the whole spreadsheet

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 6.0.0.110 On Debian 9.

**Comment by mcanepa** [comment] 2021-04-07 19:55
I would expect the same behavior on manually selected columns or rows. If I select columns C, D and E then the double click to auto resize should happen on those selected columns. The same applies to row selection...

**Comment by Rita-Bubnova** [comment] 2021-04-08 08:41
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/604.

**Closed** 2021-04-08 08:45 UTC
Labels: duplicate
