### ISSUE TITLE
Request - Roman numerical page numbers in text documents

### ISSUE THREAD

**Issue by xoxoMarzy** [ONLYOFFICE/DesktopEditors#440] opened 2020-08-13 11:42 UTC
Hey!
I want to request a feature, I need roman numericals as  page numbers  for the table of contents or glossary in a text document. 
It would be especially helpful for people who have to write scientific paper since it is common practice.

Thank you very much!

**Comment by Rita-Bubnova** [comment] 2023-08-11 14:26
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1251.
 I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-08-11 14:26 UTC
