### ISSUE TITLE
Minimize Button Speed

### ISSUE THREAD

**Issue by kojq** [ONLYOFFICE/DesktopEditors#1122] opened 2022-11-21 19:39 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1

### Expected Behavior

The button quickly minimize the application as expected.

### Actual Behavior

The button takes a noticeably longer duration of time to complete the action compared to the close or maximize (restore) buttons. It can inconsistently take from a second to several seconds for the action to be completed.

### Reproduction Steps

Install OnlyOffice and ensure that it is maximized when used. If the window is collapsed or tiled in any way, the minimize button works as intended.

**Comment by HectorB-2020** [comment] 2022-11-25 19:58
Wow, indeed! :smirk: 
I wouldn't say this is a major issue, but it's reproduced indeed. :+1:

**Comment by kojq** [comment] 2023-04-14 14:20
In this case, you can close the issue.

**Comment by XDmitryK** [comment] 2023-06-27 09:12
@HectorB-2020 @kojq 
We have released version 7.4.0, can you confirm if this issue still exists?

**Comment by kojq** [comment] 2023-06-27 18:55
I used the Flathub Flatpak with this issue no longer being present.

**Comment by DenisDeeSign** [comment] 2023-06-30 12:12
I'm close this issue since the problem is solved. Feel free to create a new one if you got further questions.

**Closed by DenisDeeSign** 2023-06-30 12:12 UTC
