### ISSUE TITLE
[Right To Left] for Arabic text

### ISSUE THREAD

**Issue by chebkhaland** [ONLYOFFICE/DesktopEditors#1314] opened 2023-06-20 11:44 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

The Arabic text does not display correctly, as Arabic letters and words are written from right to left, while the text appears left to right.
Thank you very much.
![Screenshot 2023-06-20 123821](https://github.com/ONLYOFFICE/DesktopEditors/assets/100202538/9d596ef0-5c89-46b3-9472-453832378a37)

**Comment by DenisDeeSign** [comment] 2023-06-20 16:16
Sorry, RTL is not implemented yet

Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

**Closed by DenisDeeSign** 2023-06-20 16:16 UTC
