### ISSUE TITLE
Automatic hyphenation seems not to be supported

### ISSUE THREAD

**Issue by Lars-Br** [ONLYOFFICE/DesktopEditors#381] opened 2020-05-10 22:39 UTC
I could not find a way to enable automatic hyphenation. I also did not find a way to insert a soft hyphen.

When I open docx documents created in Microsoft Word which have automatic hyphenation enabled, the hyphens are missing and the words at the end of the lines are not broken up. 

When I manually insert a soft hyphen in Word, it's not imported into OnlyOffice, either. 

It would be nice if this important feature could be added. (At least for German with its very long words, it really is important.)

**Comment by Rita-Bubnova** [comment] 2020-05-12 09:20
Hello, @Lars-Br .
Thank you. I can confirm - this is known issue 35881 in our private tracker.
This enhancement relevant to DocumentServer (https://github.com/ONLYOFFICE/DocumentServer/issues/707).

**Comment by jasond2020** [comment] 2020-08-09 14:10
OnlyOffice is really great Software with fantastic compatibility with MS Office and I use it on a daily basis and recommend it to friends and customers alike; but this is a real showstopper. Please implement this function! I would never even have thought that there is a Word Processing Software without hyphenation nowadays - it is such a basic feature. Everybody who works with texts in a more than casual way needs this function!

**Comment by HectorB-2020** [comment] 2022-10-23 20:29
Let me step in up vote this request. It's a pity hyphenation is not supported yet.

**Comment by Inrumpo** [comment] 2022-11-08 15:37
I just came across this issue in search of a way to enable auto-hyphenation in OnlyOffice. Many of my personal gripes are in this «private tracker» – for years. I hope some of those features will finally be implemented.

**Comment by reckel-jm** [comment] 2023-02-10 11:16
Yep, hyphenation is really important. OnlyOffice is a great tool but not usable for my usecases unless it has implemented auto hyphenation.

**Comment by trofim24** [comment] 2023-08-24 07:27
duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/707
so I closed this issue as duplicate

**Closed by trofim24** 2023-08-24 07:27 UTC
Labels: feature request
