### ISSUE TITLE
Some shortcut not working with different keyboard layout

### ISSUE THREAD

**Issue by alessandriniluca** [ONLYOFFICE/DesktopEditors#1071] opened 2022-10-24 13:13 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

When pressing Alt+= the equation editor should appear

### Actual Behavior

Since in some keyboard (for example in my case, the italian keyboard) the symbol "=" is obtained by pressing "Shift"+"0", the combination "Alt"+"Shift"+"0" does nothing, and the equation editor does not appear.
Also pressing "Alt"+"0" does not work

### Reproduction Steps

With an Italian keyboard, open the text editor and try to press the combination "Alt"+"=" (obtained by "Alt"+"Shift"+"0").

### Additional information

Instead of fixing this, could be enough a way to remap OnlyOffice shortcuts, such that I could remap that functionality as I prefer.

**Comment by Rita-Bubnova** [comment] 2023-08-11 16:18
@alessandriniluca, Sorry for the long wait.
DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by alessandriniluca** [comment] 2023-08-22 13:19
Apologize if I am answering only now, but in the past days I was not at home.
Unfortunately also in v7.4.1 seems not being possible to open the equation editor with the combination "Alt"+"=" obtained by "Alt"+"Shift"+"0" with an italian keyboard.

**Comment by rsnegirev** [comment] 2023-08-24 14:44
Hi @alessandriniluca 

Use shortcut "Alt" + "+". It works on the Italian (Italy) keyboard. 

This error occurred because on different keyboards the same codes come from different keys, unfortunately:
https://www.toptal.com/developers/keycode

> Instead of fixing this, could be enough a way to remap OnlyOffice shortcuts, such that I could remap that functionality as I prefer.

This is the known feature request, number 48987.

Also we're moving this issue to DocumentServer repo, since it's our base product and problem actual there too.

**Comment by Rita-Bubnova** [comment] 2023-08-24 14:55
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1197.

**Closed by Rita-Bubnova** 2023-08-24 14:55 UTC
Labels: duplicate
