### ISSUE TITLE
Image drag-and-drop issue

### ISSUE THREAD

**Issue by vatterspun** [ONLYOFFICE/DesktopEditors#61] opened 2017-08-30 01:49 UTC
One of the most crucial functions of an effective Word processor (up there with nested bullets and spellcheck) is easily adding and organizing images.  As such, I'd say this is an important bug.

**Setup**: Win7x64 with version 4.4.1.342.  Haven't tested other operating systems or earlier versions.

**Steps**:

1. Open program, launch Document
2. Drag-and-drop two images

**Defect**: second image replaces first image (and successive images will replace the previous)

**Expected behavior**: both images appear either adjacent or above-and-below each other.

**Workaround**:  Press enter a few times before dragging and dropping a second image.

---

Related: #34

**Comment by flaminestone** [comment] 2017-08-31 11:16
This problem is already fixed and will be gone in the next version. Thank you for report.

**Comment by vatterspun** [comment] 2017-09-01 03:08
> This problem will be fixed in the next releases. Thank you for report

Great news, thanks.

**Comment by ShockwaveNN** [comment] 2021-10-08 07:38
I think we've already fixed this problem a long time ago, I'll close this issue but feel free to comment or create a new issue if the problem is somehow actual.

**Closed by ShockwaveNN** 2021-10-08 07:38 UTC
Labels: bug

**Comment by ggrrll** [comment] 2022-04-30 16:18
hi,  

it seems that is not working,  on a presentation ... which is quite annoying and surprising , given that is a basic feature...


thanks 

specs
* L mint 20.3
* ONLYOFFICE Desktop Editors version 7.0.1.37

**Comment by ShockwaveNN** [comment] 2022-05-01 06:47
@ggrrll Yeah, I agree seems this issue raised again, but please create a new so we not clobber this 6 years old issue
