### ISSUE TITLE
Date and time notation in Advanced Setting

### ISSUE THREAD

**Issue by PatLabGit** [ONLYOFFICE/DesktopEditors#465] opened 2020-09-19 05:38 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a Bug, maybe it's also feature request

**What is the current behavior?**
In regional Setting:
- I would like to use USA **but with the SI** numbering and system to be able to have a date like 19/09/2020 or 2020/09/19. and hours:minute like in Airport (see bug about France regional below)
- Regional France, French do not use hours with AM/PM but **exclusively** the 24hours system like in an airport e.g 08:00 or 14:00 or 22:00 (respectively 8AM / 2PM / 10PM), and this might be valid for most European countries.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open any spreadsheet, then File/Advanced setting... -> Regional Setting Select Francais (France) it shows hours in english speaking countries way only, not in the French way.

**What is the expected behavior?**
Having the 24hours S.I. like in an airport e.g 08:00 or 14:00 or 22:00 (respectively 8AM / 2PM / 10PM)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
First time onlyoffice, 
My OSes Ubuntu-MATE 20.04 and MX Linux 19.2 as well as your online app at https://personal.onlyoffice.com 
Desktop app version: ONLYOFFICE Desktop Editors version 5.6.4.20 (it is an .**AppImage** **not** a .deb package)

**Comment by HectorB-2020** [comment] 2021-01-04 12:45
I've recently submitted [a case](https://github.com/ONLYOFFICE/DesktopEditors/issues/542#issue-778068932). In my view they might be related.

**Comment by PatLabGit** [comment] 2021-01-11 07:10
> I've recently submitted [a case](https://github.com/ONLYOFFICE/DesktopEditors/issues/542#issue-778068932). In my view they might be related.

I read your report, wow that's **a serious date issue** on your spreadsheet. Thanks for the infos

**Comment by Rita-Bubnova** [comment] 2021-01-14 13:25
Hello.
@PatLabGit, perhaps this problem is a duplicate of ONLYOFFICE/DocumentServer#1100 ?

**Comment by HectorB-2020** [comment] 2022-12-10 19:42
@Rita-Bubnova, https://github.com/ONLYOFFICE/DocumentServer/issues/1100 is closed, so is https://github.com/ONLYOFFICE/DesktopEditors/issues/542.
Does it make sense to keep this one open?
@PatLabGit, can you check and confirm?

**Comment by Rita-Bubnova** [comment] 2023-08-15 10:52
This issue was closed due no response.

**Closed by Rita-Bubnova** 2023-08-15 10:52 UTC
