### ISSUE TITLE
DesktopEditors: /lib64/libcurl-gnutls.so.4: no version information available

### ISSUE THREAD

**Issue by RobbiNespu** [ONLYOFFICE/DesktopEditors#146] opened 2018-11-01 07:51 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Crash when launch
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I getting
```
$ /usr/bin/desktopeditors 
./DesktopEditors: /lib64/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)
Segmentation fault (core dumped)
```
**What is the expected behavior?**
No crash
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Fedora 29

**Comment by RobbiNespu** [comment] 2018-11-01 08:01
I have the lib but it can use it ?
```
$ ls /lib64/ | grep libcurl
libcurl-gnutls.so.4
libcurl.so.4
libcurl.so.4.5.0

$ ldd /opt/onlyoffice/desktopeditors/libascdocumentscore.so 
/opt/onlyoffice/desktopeditors/libascdocumentscore.so: /lib64/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)
	linux-vdso.so.1 (0x00007ffcf036b000)
	libhunspell.so => not found
	libPdfReader.so => not found
	libPdfWriter.so => not found
	libDjVuFile.so => not found
	libXpsFile.so => not found
	libHtmlRenderer.so => not found
	libUnicodeConverter.so => not found
	libooxmlsignature.so => not found
	libcef.so => not found
	libcurl-gnutls.so.4 => /lib64/libcurl-gnutls.so.4 (0x00007f4e2f807000)
	libgtkglext-x11-1.0.so.0 => /lib64/libgtkglext-x11-1.0.so.0 (0x00007f4e2f801000)
	libgdkglext-x11-1.0.so.0 => /lib64/libgdkglext-x11-1.0.so.0 (0x00007f4e2f796000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f4e2f700000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f4e2f5bb000)
	libgtk-x11-2.0.so.0 => /lib64/libgtk-x11-2.0.so.0 (0x00007f4e2f12a000)
	libgdk-x11-2.0.so.0 => /lib64/libgdk-x11-2.0.so.0 (0x00007f4e2f064000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007f4e2f038000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f4e2efe3000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f4e2eec2000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4e2eea1000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4e2ed1d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4e2eb57000)
	libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007f4e2eb2d000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f4e2eb0e000)
	libssh.so.4 => /lib64/libssh.so.4 (0x00007f4e2ea89000)
	libpsl.so.5 => /lib64/libpsl.so.5 (0x00007f4e2ea76000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f4e2e9e0000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f4e2e706000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f4e2e6b4000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f4e2e5c4000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f4e2e5a4000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f4e2e59e000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f4e2e54e000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f4e2e53c000)
	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f4e2e52d000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f4e2e513000)
	libGLU.so.1 => /lib64/libGLU.so.1 (0x00007f4e2e49f000)
	libXmu.so.6 => /lib64/libXmu.so.6 (0x00007f4e2e482000)
	libXt.so.6 => /lib64/libXt.so.6 (0x00007f4e2e417000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007f4e2e40c000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007f4e2e3ee000)
	libpangox-1.0.so.0 => /lib64/libpangox-1.0.so.0 (0x00007f4e2e3cc000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f4e2e3c4000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007f4e2e3b3000)
	libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00007f4e2e38a000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f4e2e266000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007f4e2e0be000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007f4e2e0a4000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007f4e2e058000)
	libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007f4e2e03a000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f4e2dff3000)
	libfreetype.so.6 => /usr/lib64/freetype-freeworld/libfreetype.so.6 (0x00007f4e2df35000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f4e2df01000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f4e2deea000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f4e2de2d000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4e2de27000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f4e2ddfc000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f4e2ddf3000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f4e2dde6000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007f4e2dddf000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007f4e2ddcd000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f4e2ddc0000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007f4e2ddb3000)
	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007f4e2ddae000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f4e2dda9000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f4e2dd71000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f4e2dcfe000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007f4e2dcf3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4e3046b000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007f4e2db6f000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f4e2db65000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f4e2db51000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f4e2db4b000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f4e2db31000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f4e2db12000)
	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f4e2daef000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4e2d955000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4e2d93a000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f4e2d931000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f4e2d88a000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007f4e2d885000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f4e2d873000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f4e2d846000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007f4e2d7e9000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f4e2d734000)
	libthai.so.0 => /lib64/libthai.so.0 (0x00007f4e2d728000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f4e2d6e9000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f4e2d6d6000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f4e2d6d1000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f4e2d69c000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f4e2d615000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f4e2d5c2000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f4e2d594000)
	libdatrie.so.1 => /lib64/libdatrie.so.1 (0x00007f4e2d58a000)

```

**Comment by ShockwaveNN** [comment] 2018-11-01 09:28
Maybe duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/146
Try fix https://github.com/ONLYOFFICE/DesktopEditors/issues/6#issuecomment-269725720

**Comment by RobbiNespu** [comment] 2018-11-01 09:42
I have this
```
rnm@robbinespu (/opt/onlyoffice/desktopeditors)] 
$ ls -la /usr/lib64/ | grep libcurl
lrwxrwxrwx.   1 root root       19 May 19 21:01 libcurl-gnutls.so.4 -> /lib64/libcurl.so.4
lrwxrwxrwx.   1 root root       16 Oct 12 00:03 libcurl.so.4 -> libcurl.so.4.5.0
-rwxr-xr-x.   1 root root   621304 Oct 12 00:03 libcurl.so.4.5.0


[rnm@robbinespu (/opt/onlyoffice/desktopeditors)] 
$ ls -la /lib64/ | grep libcurl
lrwxrwxrwx.   1 root root       19 May 19 21:01 libcurl-gnutls.so.4 -> /lib64/libcurl.so.4
lrwxrwxrwx.   1 root root       16 Oct 12 00:03 libcurl.so.4 -> libcurl.so.4.5.0
-rwxr-xr-x.   1 root root   621304 Oct 12 00:03 libcurl.so.4.5.0
```

symlink it
```
$ sudo ln -s /lib64/libcurl.so.4 libcurl-gnutls.so.4

$ ls -la /opt/onlyoffice/desktopeditors | grep libcurl
lrwxrwxrwx.  1 root root        19 Nov  1 17:38 libcurl-gnutls.so.4 -> /lib64/libcurl.so.4

```

but still failed to open
```
$ /usr/bin/desktopeditors 
./DesktopEditors: ./libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)
Segmentation fault (core dumped)
```

**Comment by HellRoad** [comment] 2018-11-01 16:51
Yes it is bug.
We trying fixed this problem in next update
Thanks for your feedback.

**Comment by metal3d** [comment] 2018-11-12 09:08
Hello,

In a future update ? my god... I need to work right now... any other possibility to make it working waiting the next update ?

**Comment by metal3d** [comment] 2018-11-12 09:17
Note: Appimage version is also broken:

```
./DesktopEditors: symbol lookup error: /lib64/libhogweed.so.4: undefined symbol: __gmpn_cnd_sub_n
```

**Comment by HellRoad** [comment] 2018-11-12 09:18
You make used of personal.onlyoffice.com
Currently the latest version of editors is online.

**Comment by beastiephish** [comment] 2018-12-04 04:29
+1 - Also having this issue.  Fedora 29.  

./DesktopEditors: /lib64/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)
Segmentation fault (core dumped)

**Comment by ShockwaveNN** [comment] 2018-12-10 14:14
Problem is actual on Ubuntu 18.10 on release `onlyoffice-desktopeditors 5.1.27-126`
But problem also fixed on latest dev version `onlyoffice-desktopeditors 5.1.4-4`

**Comment by fconn** [comment] 2018-12-17 14:59
Same issue, Fedora 29. Installed from copr repo.

```
./DesktopEditors: ./libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)
/usr/bin/onlyoffice-desktopeditors: line 1:  8251 Segmentation fault      (core dumped) desktopeditors
```

> But problem also fixed on latest dev version `onlyoffice-desktopeditors 5.1.4-4`  

Where I can get it? Thanks.

**Comment by ShockwaveNN** [comment] 2018-12-17 15:00
@fconn currently we do not provide public betas of our dev versions, sorry

**Comment by rgarcia89** [comment] 2018-12-18 10:01
So how long do we have to wait until we get a working onlyoffice version again? O_o

**Comment by fconn** [comment] 2018-12-18 11:39
@ShockwaveNN if you don't want to share developer version of DesktopEditors, at least provide us a possible workaround for this issue, until new release will become.

**Comment by ShockwaveNN** [comment] 2018-12-18 11:51
@fconn There is no easy workaround, the problem was in CEF and require rebuilding whole application, not a easy task.

**Comment by rgarcia89** [comment] 2018-12-18 13:13
Can I get the old version somewhere as rpm?

**Comment by ShockwaveNN** [comment] 2018-12-18 13:44
@rgarcia89 I think the reason of problem is updated some of system libraries on latest Fedora versions, so don't think old rpm of DesktopEditor to fix a problem, you need an older version of Fedora

**Comment by rgarcia89** [comment] 2018-12-18 13:54
Well that is not going to work... 
Do you already know more or less when a new build will be available?

**Comment by ShockwaveNN** [comment] 2018-12-18 13:56
@rgarcia89 we do not know exact date but I hope we will be ready before end of the year

**Comment by HellRoad** [comment] 2018-12-21 14:07
We released a new version Desktop Editors and fixed bug on Fedora 28-29
Thanks for your feedbacks

**Comment by rgarcia89** [comment] 2018-12-21 14:32
Works - thanks a lot guys.
Happy holidays

**Comment by fconn** [comment] 2018-12-21 16:02
I can confirm too, Fedora 29 works correctly.
![image](https://user-images.githubusercontent.com/37580200/50351169-661acb80-0552-11e9-8dbb-22cf01ef230e.png)

Спасибо, с наступающим Вас :)

**Comment by ShockwaveNN** [comment] 2018-12-21 16:04
Good to hear you guys, I'm closing this issue. Feel free to comment if you found some troubles with latest release

**Closed by ShockwaveNN** 2018-12-21 16:04 UTC
Labels: bug

**Comment by now-im** [comment] 2018-12-22 18:20
I am still getting this error:
```
onlyoffice-desktopeditors                                                                                                      
./DesktopEditors: /opt/onlyoffice/desktopeditors/libcurl-gnutls.so.4: version `CURL_GNUTLS_3' not found (required by /opt/onlyoffice/desktopeditors/converter/libkernel.so)
```

**Comment by HellRoad** [comment] 2018-12-26 14:48
@now-im 
We don't have build for Arch linux but we coming soon released Snap version DesktopEditors

**Comment by now-im** [comment] 2018-12-26 14:56
@HellRoad actually arch does not need a specific package to be installed on the system. The source file is often enough. It is not in the official arch repo, independent maintainer is not being able to maintain the package properly. That is the problem. Will test the package when snap is available.

**Comment by noraj** [comment] 2019-02-15 16:39
see #6 there is still the `/usr/lib/libcurl-gnutls.so.4` error in the last release.
