### ISSUE TITLE
autocorrect equation bracket is hide the plus or minus sign

### ISSUE THREAD

**Issue by muktyas** [ONLYOFFICE/DesktopEditors#1114] opened 2022-11-16 00:21 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1

### Expected Behavior

If we type (x-2) <space> then it must be still (x-2). Or if we type (x-2)^2 it must be automatically (x-2)^2. But the actually is, if we type (x-2) it is become (x2). It happend in 7.2.1 version. But the 7.1.1 version is does not have this problem.

### Actual Behavior

if we type (x-2) it is become (x2). For more information, please look at this screenrecord:
[https://drive.google.com/file/d/1vsmbDtBjdnWXoMoMSq5OzPo1wdQ3aPYr/view?usp=share_link](https://drive.google.com/file/d/1vsmbDtBjdnWXoMoMSq5OzPo1wdQ3aPYr/view?usp=share_link)

**Comment by TatianaKirillova** [comment] 2022-11-16 08:44
Hello, [@muktyas](https://github.com/michal-barteczko)
Thanks for your request!
I can confirm that the problem exists. I created ticket 59746 in our private  tracker with your  issue.

**Comment by TatianaKirillova** [comment] 2023-02-01 10:42
@muktyas,The problem has been fixed in version 7.3.0. Please update your version of the desktop editor

**Comment by DenisDeeSign** [comment] 2023-02-01 10:45
Since version is released I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by DenisDeeSign** 2023-02-01 10:45 UTC
Labels: bug, fixed

**Comment by muktyas** [comment] 2023-04-18 01:54
Now, the bracket is disappear. I use version 7.3.3.50 in linux mint
like this:

https://user-images.githubusercontent.com/13088121/232649407-eabb8068-eeaa-4fd9-b589-1d9a4ef2f364.mp4
