### ISSUE TITLE
DesktopEditor stopped opening in Fedora 33

### ISSUE THREAD

**Issue by t3kg33k** [ONLYOFFICE/DesktopEditors#665] opened 2021-07-14 16:57 UTC
**Do you want to request a *feature* or report a *bug*?** Repor a bug (issue)

**What is the current behavior?** App no longer opens

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Selecting the app does not open. Attempting to open a document does not open at all nor the Desktop Editor

**What is the expected behavior?** The app to open. Or, the document to open when selected.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?** DesktopEditor 6.3.1. Fedora 33. It has been working fine for the past few months until today. I had opened a document earlier this morning just fine. I closed it and later attempted to open the application and documents but would no longer open. No errors seen. I even complete Fedora updates and rebooted and it still will not open.

I have found the only way to open the application is via command line using the Flatpak command (this is a Flatpak install).

_flatpak run org.onlyoffice.desktopeditors
Gtk-Message: 10:26:25.390: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:26:25.391: Failed to load module "pk-gtk-module"
Gtk-Message: 10:26:25.391: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:26:25.391: Failed to load module "pk-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
QXcbConnection: XCB error: 8 (BadMatch), sequence: 2613, resource id: 79691855, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 2618, resource id: 79691855, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 2621, resource id: 79691855, major code: 130 (Unknown), minor code: 3_

**Comment by ShockwaveNN** [comment] 2021-07-15 08:37
Duplicate of https://github.com/flathub/org.onlyoffice.desktopeditors/issues/41

**Closed by ShockwaveNN** 2021-07-15 08:37 UTC
