### ISSUE TITLE
Embeding file into only office spreadsheet

### ISSUE THREAD

**Issue by wangtiankun123** [ONLYOFFICE/DesktopEditors#1390] opened 2023-10-16 06:17 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello, all,
as our company are starting to use Only Office, one of the specific functions is desirable is embeding a file into a OO spreadsheet or word doc as MS excel inset an object. Dont know if this is in progress or new feature. But, any updates would be appreciated!!!

Thanks.

**Comment by rsnegirev** [comment] 2023-10-20 10:52
Hi @wangtiankun123!

This is the new feature, issue 64777.

We'll write here about the progress on it.

Thank you for the request!

PS: We're also moving this issue to DocumentServer repo, since it's our base product and problem actual there too.

**Comment by rsnegirev** [comment] 2023-10-20 12:50
Also this issue is duplicate of this one https://github.com/ONLYOFFICE/DocumentServer/issues/1753, so we're closing it.

**Closed** 2023-10-20 13:12 UTC
Labels: duplicate
