### ISSUE TITLE
Persian language is not displayibg correctly

### ISSUE THREAD

**Issue by mmdmine** [ONLYOFFICE/DesktopEditors#413] opened 2020-06-22 10:24 UTC

**Comment by ShockwaveNN** [comment] 2020-06-22 10:27
Hi, please fill out issue template correctly. Specify product version, OS and attach some screenshots

**Comment by mmdmine** [comment] 2020-06-22 10:35
> Hi, please fill out issue template correctly. Specify product version, OS and attach some screenshots

Hey, sorry for that, but I've just installed it today (from flatpak) and then uninstalled it (after seeing it's not working with Persian).
Just MSOffice and LibreOffice works fine with Persian.
You can try it yourself. Copy this text to your Word Processor, it'll show it as squares.
سلام دنیا

**Comment by ShockwaveNN** [comment] 2020-06-22 10:40
Yeah. I can confirm. Seems this issue actual only for flatpak, I tested debian version and this text inserted fine.
Seems this is duplicate of https://github.com/flathub/org.onlyoffice.desktopeditors/issues/17

**Closed by ShockwaveNN** 2020-06-22 10:40 UTC
