### ISSUE TITLE
[Feature request] Allow to open documents in separate windows

### ISSUE THREAD

**Issue by artem-leonov** [ONLYOFFICE/DesktopEditors#41] opened 2017-05-10 08:51 UTC
**Do you want to request a *feature* or report a *bug*?**
It's a feature request

**What is the current behavior?**
Opening documents in separate windows is not supported

**What is the expected behavior?**
I want to open documents in separate windows. For example, I want to arrange document windows in various virtual desktop to quick switching between them.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I use ONLYOFFICE 4.3.2.318 in Windows 10

**Comment by vatterspun** [comment] 2017-06-10 23:28
Great suggestion.  I'd also like to see separate windows created via drag-and-drop similar to Firefox.

**Comment by K0R0L** [comment] 2017-08-11 07:25
in next release!

**Comment by vatterspun** [comment] 2017-08-19 03:00
> in next release!

Great news :)

**Comment by ChriKn** [comment] 2019-01-25 15:22
Sadly it seems this hasn't been resolved (at least on windows...) am I missing something ? It's great to be able to have 2 documents open at the same time...

**Comment by yconst** [comment] 2019-06-19 06:42
Just to point out that this feature is missing from Linux Onlyoffice as well.

This is a huge deal-breaker for an otherwise excellent office suite. Opening more than one document side-by side is essential for many tasks. Currently I am forced to open the second document in another program (!), which is of course far from ideal.

**Comment by IgorNFS** [comment] 2019-10-28 07:40
This is a really useful feature, I will look forward to it.

**Comment by ChriKn** [comment] 2020-02-27 16:05
Weird this hasn't been addressed or resolved...
Why on earth wouldn't you give people a way of working with two spreadsheets open at the same time i.e ?

**Comment by dfrau32** [comment] 2020-03-08 22:53
> Weird this hasn't been addressed or resolved...
> Why on earth wouldn't you give people a way of working with two spreadsheets open at the same time i.e ?

I agree, I am in need of this functionality right now. Also, very useful would be to be able to have two documents open and scroll both at the same time.

**Comment by vatterspun** [comment] 2020-05-10 00:40
> scroll both at the same time.

This is actually pretty unusual.  Synchronized scrolling is in Microsoft Word (and it has an oddity that means it only works sometimes) and WinMerge.  I haven't found it in any other programs on Windows.  I just say that to set expectations for ONLYOFFICE.

**Comment by ShockwaveNN** [comment] 2020-05-12 06:57
We implemented feature about extracting documents in several windows in DesktopEditors v5.5.1 so I'm closing this issue.
For 
> would be to be able to have two documents open and scroll both at the same time.

please create separate issue

**Closed by ShockwaveNN** 2020-05-12 06:57 UTC
Labels: enhancement

**Comment by XeJames** [comment] 2021-08-08 11:24
Wait, what?  You are closing the request?  Why?  The request is not about extracting documents or about scrolling, it is about working side-by-side on multiple documents.  I still cannot see any way to do that in 2021.  It's a huge hole in the otherwise excellent product.  A showstopper in many cases.  This is important to address.

Or am I missing something and you HAVE implemented side-by-side documents?  If so, I'd like to know how.

**Comment by ShockwaveNN** [comment] 2021-08-09 07:41
> The request is not about extracting documents or about scrolling, it is about working side-by-side on multiple documents.

You really telling I'm wrong about which feature user requested in 2017?

Original issue was about ability to extract doc to separate window (which was not available in 2017)
Like this

![image](https://user-images.githubusercontent.com/668524/128673406-242c68e7-1c51-4cd3-b7ca-8a34a2a17cce.png)

If you telling about something like this:
https://support.microsoft.com/en-us/office/view-and-compare-documents-side-by-side-52445547-7c07-475b-bb1d-22a98175ef04
Better create new issue

**Comment by XeJames** [comment] 2021-08-09 14:01
Thanks for the response Pavel.

I guess we are reading his request differently.  All I see him asking is the ability to see one document while working on another document, a very common task.  This may be accomplished by either the Microsoft way (thank you for the link) where you "arrange" using Microsoft Word's built-in system, or - and far better - simply allow opening a second INSTANCE of OnlyOffice.

My interest is due to a pharmaceutical client calling this inability to work on two - visible - documents simultaneously a "show stopper".  

But I won't pursue this.  I just had the same question as OP did - and I think you have given us a clear answer: "no, it cannot be done and no it is not being considered as a feature in the future".

**Comment by ShockwaveNN** [comment] 2021-08-09 14:18
Sorry, but I simply do not understand you

Working side-by-side as in MS Office is currently is not implemented, but I'm not meaning"We cannot do it", we may or may not - a lot of technical and performance issues with this

But as you client is asking "to see one document while working on another document" - it's doable right now, by extracting tab to separate window (like a shown on my screenshot) and I personally do not see any troubles working with several documents like this

**Comment by XeJames** [comment] 2021-08-09 14:24
LOL... HOW DID YOU DO IT!!??  I didn't even notice that you had done exactly what my client requires.   HOW did you get two windows open side-by-side?  (I feel really silly right now).

**Comment by ShockwaveNN** [comment] 2021-08-09 14:28
@XeJames Simply by drag-n-drop title of second document outside of main window

I've recorded video for you (sorry for wrong aspect ration, seems my video record tool do not like 21:9 display)

https://user-images.githubusercontent.com/668524/128722811-ce8e387a-c2ea-49b3-8d1b-14a0d40b2cd7.mp4

Please make sure that you using latest DesktopEditors (v6.3.1), we got a lot of issues with extraction of this tabs in previous releases

**Comment by XeJames** [comment] 2021-08-10 10:33
Wow.  I confirmed that I have 6.3.1 (504) but mine doesn't do that.  I drag the tabs and they only move horizontally.  They won't "detach" from the tab bar.  I don't see any setting anywhere to turn this feature off or on so I am greatly puzzled.

Any chance this is broken on Mac?  

And thanks so much for all of this effort on your part.  Very decent of you and I appreciate it a lot.

**Comment by ShockwaveNN** [comment] 2021-08-10 11:08
> Any chance this is broken on Mac?

You never mention it was on Mac, yeah I think it's not implemented on mac

We got issue 35421 about this
If you want - you may create new issue on GitHub about this situation on mac

Seems there was some troubles implementing it on mac

**Comment by XeJames** [comment] 2021-08-10 11:49
Ah.  THAT makes sense...  I'll do that, thanks.  

FWIW:  This actually solves the customers problem; they use only Windows.

**Comment by softboy99** [comment] 2024-04-07 05:38
Hi,
does this feature available for browser version?

**Comment by Rita-Bubnova** [comment] 2024-04-09 12:44
> Hi, does this feature available for browser version?

Create a new request in [DocumentServer ](https://github.com/ONLYOFFICE/DocumentServer/issues)and describe the problem in more detail.
