### ISSUE TITLE
Editor is blocked when document saving dialog is hidden

### ISSUE THREAD

**Issue by Kymoxis** [ONLYOFFICE/DesktopEditors#553] opened 2021-01-18 07:58 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
freeze

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**--
-Open some File 
-go to Save / Save as 
-File Manager Opens (Nautilus/ Thunar)
-accidentally click out of the File Manager Window
-File Explorer disappears
-OO freezes
-Have to kill OO. Unsaved Work is lost

**What is the expected behavior?**
-File Manager Should appear when Click the OO launcher again

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Version: 6.1.0.90, OO DE for Linux
OS: -Debian 10/11, xfce4
        -PoP_OS 20.10 gnome
        -Ubuntu 20.04 gnome

**Comment by matveevms** [comment] 2021-01-19 13:31
Hello, @MxMarl 
I can confirm - this is bug, issue 48304 in our private issue tracker.

**Comment by Rita-Bubnova** [comment] 2023-08-11 22:59
This issue fixwd (https://github.com/ONLYOFFICE/desktop-apps/commit/ed1a56a121b01bf7cf04582bfdb69db894fa2ea3).
@matveevms @MxMarl Please state is this problem still actual for you?

**Comment by matveevms** [comment] 2024-02-01 09:22
As stated above, the problem was fixed in one of the previous versions. We are closing this issue, but you can always write to us if you have any questions. Thank you for your request.

**Closed** 2024-02-01 09:25 UTC
Labels: confirmed-bug, fixed
