### ISSUE TITLE
Opening subsequent files using file manager isn't working properly

### ISSUE THREAD

**Issue by Iangh59** [ONLYOFFICE/DesktopEditors#529] opened 2020-12-11 17:48 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If I double-click on a file from my file manager, Dolphin, OO opens and shows the file contents. If I then open another file from within Dolphin the desktop focus does not switch to OO but remains on Dolphin. Maximising OO reveals two tabs with the file contents and an empty tab called "opening". Same result with subsequent files: a tab with contents and another "opening".
![2020-12-12time04-22](https://user-images.githubusercontent.com/62003324/101936079-3039ea80-3c34-11eb-8a9c-c7f13ea2f157.png)

Note, opening files from within OO opens files in tabs correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open file from within file manager.
2. Go back to file manager and open another file.

**What is the expected behavior?**
Opening any file from within the file manager should give focus to OO and show the file contents.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 6.1.0.90
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-56-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7.6 GiB of RAM

As far as I remember it worked fine previously. Haven't used OO for about 6 months.

**Comment by matveevms** [comment] 2020-12-14 12:10
Hi, @Iangh59 
I can confirm - this is bug, issue 48002 in our private issue tracker.

**Comment by parrenin** [comment] 2021-03-19 16:33
With Desktop Editors 6.2, the situation has improved since there is no phantom tab named "Opening...".
But it is still not perfect, since OODE does not get the focus.
The focus stays on the file manager.

**Comment by matveevms** [comment] 2021-03-22 15:50
@parrenin, yes indeed. This problem exists. Could you please create a new issue?

**Comment by matveevms** [comment] 2021-03-24 07:39
Original issue fixed in version 6.2 (https://github.com/ONLYOFFICE/desktop-apps/commit/86f39283d8a4f8d9a10416b8bc7bd540a91a01cf)

**Comment by ShockwaveNN** [comment] 2021-03-24 07:43
Origianl issue is fixed and released as v6.2.0 - I'm closing this issue

@parrenin reported a new issue and it's here https://github.com/ONLYOFFICE/DesktopEditors/issues/587

**Closed by ShockwaveNN** 2021-03-24 07:43 UTC
Labels: bug
