### ISSUE TITLE
Sort from Google files does not work

### ISSUE THREAD

**Issue by simplerethink** [ONLYOFFICE/DesktopEditors#1022] opened 2022-09-22 14:41 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.1.1.57

### Expected Behavior

When sorting high to low, I expected sort to arrange the data in the correct order.

### Actual Behavior

I'm working with csv files generated by Google Ads report export feature.

When sorting high to low, 97% is listed higher than 952%. 

I'd imagine this is happening because the `7` is higher than the `5`, but OO is not taking into account that this is a three-digit number vs two-digit.

I do not have this issue with Excel or Google Sheets.

### Reproduction Steps

1. Open this example file [example-sort-issue.csv](https://github.com/ONLYOFFICE/DesktopEditors/files/9626823/example-sort-issue.csv)
2. Set delimiter to comma
3. Sort `column A` Z -> A
4. You should see values are not sorted correctly

### Additional information

1. At the moment, I can only reproduce the issue with exported files, not files created within OO.
2. I have a colleague who is having the same issue, but using csv files from other sources.
3. I tried setting the column to different types, such as percentage. It did not fix the issue.

**Comment by rsnegirev** [comment] 2023-08-01 14:30
Hi @simplerethink 

I can't reproduce this behavior in the current version of the OnlyOffice Editor, so this problem was fixed in one of the previous updates.

So, I recommend you update the application, last version is 7.4.1.36.

**Comment by Rita-Bubnova** [comment] 2023-09-12 13:39
This issue was closed due no response.

**Closed by Rita-Bubnova** 2023-09-12 13:39 UTC
Labels: waiting feedback
