### ISSUE TITLE
Linux binaries crashes on startup on Wayland

### ISSUE THREAD

**Issue by WhyNotHugo** [ONLYOFFICE/DesktopEditors#382] opened 2020-05-11 00:52 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Crash on startup:
```console
$ onlyoffice-desktopeditors
This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
zsh: abort (core dumped)  onlyoffice-desktopeditors
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Run the binaries [here](https://github.com/ONLYOFFICE/DesktopEditors/releases) on Linux with any wayland compositor (crash will probably not happen on Xorg, but haven't checked).

**What is the expected behavior?**

Should start normally.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Haven't tried previous versions.

**Other notes**

This looks like something's misconfigured in the pipeline that builds the binaries themselves, and is likely not a code error in itself. I tries looking at how this is configured, but couldn't find the pipelines that do the building/releasing.

**Comment by ShockwaveNN** [comment] 2020-05-12 06:55
> Run the binaries here on Linux with any wayland compositor 

Hi, any advice on simplest way to setup system with Wayland?

**Comment by WhyNotHugo** [comment] 2020-05-12 15:49
I believe you can run `sway` (a light wayland compositor) inside Xorg, and it'll run wayland nested inside Xorg.
I don't have Xorg set up on my system, so I'm not entirely sure of the finer details, but IIRC, just running `sway` from a terminal should work.

As an alternative, I do believe that recent Ubuntu/Fedora releases let you pick wayland from the login screen.

**Comment by WhyNotHugo** [comment] 2020-05-12 15:51
I've failed to find the build scripts for these binaries, but if you can point me to them, I can try and pinpoint what's wrong there. I have an impression that the Qt build is missing wayland support for some reason

**Comment by ShockwaveNN** [comment] 2020-05-12 15:58
> I believe you can run sway (a light wayland compositor) inside Xorg, and it'll run wayland nested inside Xorg.

Ok, we'll try it. @XDmitryK please try to run DesktopEditors on Ubuntu with wayland server, I think this [instruction](https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-20-04-desktop) is enough 

> I've failed to find the build scripts for these binaries

All build instuction at https://github.com/ONLYOFFICE/build_tools repo

**Comment by XDmitryK** [comment] 2020-05-13 11:53
@WhyNotHugo 
I launched the desktop on Ubuntu 20.04 with WayLand (deb package)
What installation method did you use?
And also our need information about your OS
![Oracle VM VirtualBox 202](https://user-images.githubusercontent.com/46962983/81808925-27abf500-9529-11ea-9299-f8816a7ca5b4.png)

**Comment by WhyNotHugo** [comment] 2020-05-13 15:03
I installed via an [ArchLinux User Package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=onlyoffice-bin) which basically downloads upstream binaries.

Maybe it's running via XWayland. Can you try either:
- Running via a terminal after running `unset DISPLAY`, or
- Running via a terminal setting `QT_QPA_PLATFORM=wayland`?

That should force it to use Wayland, at which point you might see the error I'm mentioning. (Also, if you enable desktop scaling to something like 1.5x, you'll probably notice the version running via Xorg scales very blurry. This is due to an Xorg limitation).

**Comment by XDmitryK** [comment] 2020-05-14 10:16
@WhyNotHugo 
Unfortunately on Ubuntu this is not repeated
Can you send us an image of your system in a VM file?

**Comment by sheepymeh** [comment] 2020-10-17 10:22
I'd like to confirm that this issue is still present in the latest versions (6.0.0. and 5.6.4). I am running Arch Linux and Sway, and I have tried both the version from the AUR (updated today) and the latest AppImage.

The binaries work on XWayland (`QT_QPA_PLATFORM=xcb`) but this causes the editor to become blurry on displays with scaling enabled as mentioned before.

**Comment by andersfylling** [comment] 2020-12-02 16:16
Same issue here. Sway on arch linux. However, so far QT_QPA_PLATFORM=xcb seems to fix it.

**Comment by WhyNotHugo** [comment] 2020-12-03 20:06
Using `QT_QPA_PLATFORM=xcb` forces the application to run via XWayland, which has it's own set of issues. I'd rather just run the application natively.

@XDmitryK Can you try using the latest fedora image? It has a nice GUI to switch to use Wayland instead of Xorg.

However, did the application run okay for you after running `unset DISPLAY`? That should not be possible, since it should not be able to communicate with Xorg if this variable is unset.

**Comment by genofire** [comment] 2020-12-08 11:08
Version  v6.1.0 is out, still not compiled with wayland support

**Comment by major-mayer** [comment] 2020-12-11 09:30
I am using the latest version Manjaro (it's a rolling release) and installed the "onlyoffice-desktopeditors" from the official package repository and it's working just fine under Wayland.
I guess it's using XWayland tho, because everything is blurred on my 4K display with fractional scaling enabled. 
On the FullHD Monitor which is not using fractional scaling it's looking good.

So if it's possible to build the Qt application (it's not using electron right?) with native Wayland support, i would be very happy to test it :heart:

**Comment by WhyNotHugo** [comment] 2020-12-11 11:28
>  I guess it's using XWayland tho, because everything is blurred on my 4K display with fractional scaling enabled.

I'd guess it's using XWayland too. You can confirm this by running `xeyes`, and moving the cursor around on top of onlyoffice. If the eyes track the cursor, then the application is using xwayland.

If you're using sway, you can also confirm by inspecting the output of `swaymsg -t get_tree`.

**Comment by WhyNotHugo** [comment] 2020-12-11 12:02
>  I guess it's using XWayland tho, because everything is blurred on my 4K display with fractional scaling enabled.

I'd guess it's using XWayland too. You can confirm this by running `xeyes`, and moving the cursor around on top of onlyoffice. If the eyes track the cursor, then the application is using xwayland.

If you're using sway, you can also confirm by inspecting the output of `swaymsg -t get_tree`.

**Comment by major-mayer** [comment] 2020-12-11 12:13
Uhh nice tool, didn't know about this yet.
And yes as you expected, the eyes track the cursor over the whole onlyoffice window which does not happen on native GTK3 apps or things like Thunderbird and Firefox(-Wayland)

**Comment by duvh93** [comment] 2021-01-14 15:59
It'd be great if they could update to the latest version of QT in order to natively support Wayland protocol...

**Comment by major-mayer** [comment] 2021-03-18 22:46
Anything new here @ShockwaveNN @XDmitryK ?
Would be really nice if this could be fixed at some point.
Wayland support of most Qt apps is pretty solid nowadays, so I wonder why this couldn't get archived for onlyoffice too. 

If you really need it, I can configure you a vm with a Wayland session pre-set, but it shouldn't be too hard to reproduce this on your own. 

Just start your already working Ubuntu Gnome Desktop with session type Wayland (you can choose this with the bottom right gear icon if you are using GDM (depending on your theme)) and execute onlyoffice with the parameter `--platform wayland`. 
Et voilà Onlyoffice doesn't start anymore, because somehow it isn't compiled with Qt's Wayland support (that's where I can't help either unfortunately).

**Comment by XDmitryK** [comment] 2021-03-19 10:46
@major-mayer 
I confim this bug is reproduced. i posted this in our local bugtracker.(bug 49179)

**Comment by major-mayer** [comment] 2021-03-19 11:15
Thanks you for the confirmation 👍

**Comment by shih-liang** [comment] 2021-04-17 06:12
I guess adding 'qt-wayland' in [build_tools/automate.py#qt_params](https://github.com/ONLYOFFICE/build_tools/blob/bd3568eba0da2c90c279e1f7a95015b645aec95e/tools/linux/automate.py#L80) may resolve this issue.

**Comment by WhyNotHugo** [comment] 2021-05-12 16:29
Those scripts seem broken though. I ran:

```bash
git clone git@github.com:ONLYOFFICE/build_tools.git
cd build_tools
mkdir out
docker build --tag onlyoffice-document-editors-builder .
docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder
```

And it failed on the last command:

```
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/appletviewer to provide /usr/bin/appletviewer (appletviewer) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
Setting up libatk-wrapper-java-jni:amd64 (0.30.4-4) ...
Processing triggers for libc-bin (2.19-0ubuntu6.15) ...
There is only one alternative in link group java (providing /usr/bin/java): /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
Nothing to configure.
There is only one alternative in link group javac (providing /usr/bin/javac): /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
Nothing to configure.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0    844      0 --:--:-- --:--:-- --:--:--   844
100   196  100   196    0     0    317      0 --:--:-- --:--:-- --:--:--   317
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
install dependencies...
install qt...
Error (tar): 2
```

I haven't even made any changes to it. Is this currently being used to generate the builds?

**Comment by ShockwaveNN** [comment] 2021-05-13 07:07
@WhyNotHugo Problem with qt link described here - https://github.com/ONLYOFFICE/build_tools/issues/306

**Comment by patzm** [comment] 2021-12-13 17:02
For quite some time, this worked for me on Manjaro with Sway DM and the environment variable `` set. However, now I get
```
This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "QT_QPA_PLATFORM=wayland".
```
again. Also, I confirm that I have `qt5-wayland` installed:
```bash
$ pacman -Qs qt5-wayland
local/qt5-wayland 5.15.2+kde+r36-1 (qt qt5)
    Provides APIs for Wayland
```

**Comment by maximushugus** [comment] 2022-02-05 17:13
The problem is still here on version 7.0.0 : onlyoffice isn't compatible with wayland.
I tried to add the "-qt-wayland" parameter in [build_tools/automate.py](https://github.com/ONLYOFFICE/build_tools/blob/bd3568eba0da2c90c279e1f7a95015b645aec95e/tools/linux/automate.py#L80) and compiled but got this error : 
`ERROR: Unknown command line option '-qt-wayland'.
`

It could be great if devs could implement wayland support because it is blurry on my hidpi screen : is this feature planned ?

**Comment by ShockwaveNN** [comment] 2022-02-05 17:17
@maximushugus Sorry, the issue with Wayland is still actual and  I don't quite remember, but I think because we use rather old `CEF` as the base of our app

I cannot promise that we have enough resources to fix it soon, sorry

**Comment by maximushugus** [comment] 2022-02-05 17:21
> @maximushugus Sorry, the issue with Wayland is still actual and I don't quite remember, but I think because we use rather old `CEF` as the base of our app
> 
> I cannot promise that we have enough resources to fix it soon, sorry

What do you mean by "CEF" ?

**Comment by ShockwaveNN** [comment] 2022-02-05 17:24
Chromium Embedded Framework

**Comment by major-mayer** [comment] 2022-02-05 17:26
I'm don't know how you combine CEF and Qt (two desktop toolkits?) but CEF still does not feature native Wayland support for embedded apps.
So even upgrading wouldn't help...

**Comment by ShockwaveNN** [comment] 2022-02-05 17:27
So my memory is right, and yes we defenetly use CEF

**Comment by ShockwaveNN** [comment] 2022-04-11 13:09
@juxuanu Thanks, I'll show this to our devs

**Comment by romm1of** [comment] 2022-05-06 09:00
> @juxuanu Thanks, I'll show this to our devs

Any updates?

**Comment by ShockwaveNN** [comment] 2022-05-06 14:02
@romm1of Sorry, no updates

**Comment by kohane27** [comment] 2022-07-22 08:52
I just migrated to wayland and discovered that onlyoffice doesn't start. I'm using sway and I set the env variable `export QT_QPA_PLATFORM=wayland-egl` upon login. The solution is to tell onlyoffice to run `xcb` by editing the desktop file. Go to `/usr/share/applications/onlyoffice-desktopeditors.desktop`(src: [Desktop entries - ArchWiki](https://wiki.archlinux.org/title/Desktop_entries#Modify_environment_variables)):

add `env QT_QPA_PLATFORM=xcb` at the start of `Exec`, i.e., from 
`Exec=/usr/bin/onlyoffice-desktopeditors %U` to `Exec=env QT_QPA_PLATFORM=xcb /usr/bin/onlyoffice-desktopeditors %U`.

And onlyoffice launches successfully.

OS: EndeavourOS Linux x86_64
WM: sway

**Comment by juxuanu** [comment] 2022-07-22 09:20
Using Xwayland doesn't solve the underlying issue — Qt needs the wayland plugin.

**Comment by niksingh710** [comment] 2022-08-13 15:24
any further updates on this?
using Arch linux and facing the same issue.

**Comment by ShockwaveNN** [comment] 2022-08-14 05:49
@niksingh710 Sorry, no news, we'll report as soon as this issue is properly fixed

**Comment by Alex-Bujorianu** [comment] 2022-12-20 11:58
Can confirm that I am also affected by this issue. Additionally, the program does not seem to detect the correct DPI settings when running in XWayland.

**Comment by dvoloshyn** [comment] 2023-01-13 10:20
In version 7.2.1 it still fails to load plugin "wayland" though output says it's available.
```
This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Reinstalling the application may fix this problem.
zsh: IOT instruction (core dumped)  onlyoffice
```

**Comment by lal12** [comment] 2023-08-18 07:35
When I run `flatpak run org.onlyoffice.desktopeditors --enable-features=UseOzonePlatform --ozone-platform=wayland`
I get this:

![Bildschirmfoto vom 2023-08-18 09-32-55](https://github.com/ONLYOFFICE/DesktopEditors/assets/14139770/cd6d9bd9-f83f-483b-844a-855636e515b7)

**Comment by niksingh710** [comment] 2023-09-26 05:25
don't know if it may concern but for now m using onlyoffice-desktopeditors under `gamescope` and it works fine XD

**Comment by Pshemas** [comment] 2023-10-12 20:31
+1 would love to see Wayland support. I'm running latest Gnome on OpenSUSE TW and lack of this is a major pita.

**Comment by SHU-red** [comment] 2023-10-20 17:22
Same here
Fedora Workstation with mainly Sway but sometimes GNOME

Absolutely bad performance on my most loved office-suite

**Comment by TurtleMeds** [comment] 2024-04-19 03:14
@ShockwaveNN any updates on this old issue? Facing similar issue on Arch with hyprland compositor. Some of the tooltips are opening as windows, and as a result they are tiling.

**Comment by spikespaz** [comment] 2024-05-17 07:39
@TurtleMeds 

> ShockwaveNN, any updates on this old issue? Facing similar issue on Arch with hyprland compositor. Some of the tooltips are opening as windows, and as a result they are tiling.

Is this an issue you notice often? Other programs I have the same issue, opening as new windows, but not always. I wonder if there's a bug to be found and squashed in a shared library.

**Comment by niksingh710** [comment] 2024-05-17 11:42
okay so on `8.0.1-1` arch linux it is getting rendered using xwayland but working fine.

**Comment by uc-ai2** [comment] 2024-09-04 14:42
This issue is no longer reproduced when running desktopeditors without parameters, or with the "--platform xcb" parameter in the current version.

**Comment by Rita-Bubnova** [comment] 2024-09-04 15:10
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-09-04 15:10 UTC
Labels: confirmed-bug

**Comment by juxuanu** [comment] 2024-09-04 16:41
@Rita-Bubnova 
```
❯ flatpak run org.onlyoffice.desktopeditors 
F: No se comparte «/usr/share/icons/Adwaita» con el sandbox: La ruta «/usr» está reservada por Flatpak
F: No se comparte «/usr/share/themes» con el sandbox: La ruta «/usr» está reservada por Flatpak
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```
(v 8.1.1)

**Comment by sheepymeh** [comment] 2024-09-05 12:38
Same issue here persists on Arch Linux (installed from AUR):

```
$ onlyoffice-desktopeditors
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
$ onlyoffice-desktopeditors --version
ONLYOFFICE Desktop Editors ver. 8.1.1.27
```
