### ISSUE TITLE
Segmention fault (core dumped)

### ISSUE THREAD

**Issue by Lirabeth** [ONLYOFFICE/DesktopEditors#197] opened 2019-03-13 15:53 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
<pre>Segmentation fault (core dumped)
</pre>

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
#146 #6(comment) didnt work

i tried:
/snap/onlyoffice-desktopeditors
sudo ln -s /usr/lib64/libcurl.so.4 libcurl-gnutls.so.4

reply:<pre>ln: failed to create symbolic link &apos;libcurl-gnutls.so.4&apos;: File exists
</pre>

**What is the expected behavior?**
Open normaly

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
onlyoffice-desktopeditors  5.2.8                   30    edge      onlyoffice

problem occur while using stable and changed to edge to see some change

OS: Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Thanks in advance

**Comment by cm3z4** [comment] 2019-03-13 17:06
I've having this issue as well. I'm using the snap version 5.2.8 29 / stable.

OS: Pop!_OS
Release: 18.04.1-Ubuntu
Kernel: 4.18.0-16-generic

Logs:

`11:49:44 AM kernel: traps: desktopeditors[9277] general protection ip:7f2cfdd98ed6 sp:7ffe73202d98 error:0 in ld-2.23.so[7f2cfdd81000+26000]

11:49:44 AM kernel: audit: type=1400 audit(1552495784.035:236): apparmor="DENIED" operation="open" profile="snap.onlyoffice-desktopeditors.onlyoffice-desktopeditors" name="/etc/pop-os/os-release" pid=9277 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

11:49:44 AM snap-exec: AVC apparmor="DENIED" operation="open" profile="snap.onlyoffice-desktopeditors.onlyoffice-desktopeditors" name="/etc/pop-os/os-release" pid=9277 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

11:49:44 AM kernel: audit: type=1400 audit(1552495784.007:235): apparmor="DENIED" operation="open" profile="snap-update-ns.onlyoffice-desktopeditors" name="/etc/pop-os/os-release" pid=9293 comm="4" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

11:49:44 AM 4: AVC apparmor="DENIED" operation="open" profile="snap-update-ns.onlyoffice-desktopeditors" name="/etc/pop-os/os-release" pid=9293 comm="4" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

11:49:43 AM kernel: audit: type=1400 audit(1552495783.991:234): apparmor="DENIED" operation="open" profile="/snap/core/6531/usr/lib/snapd/snap-confine" name="/etc/pop-os/os-release" pid=9277 comm="snap-confine" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

11:49:43 AM snap-confine: AVC apparmor="DENIED" operation="open" profile="/snap/core/6531/usr/lib/snapd/snap-confine" name="/etc/pop-os/os-release" pid=9277 comm="snap-confine" requested_mask="r" denied_mask="r" fsuid=0 ouid=0`

Thanks, hope the logs help.

**Comment by erosval** [comment] 2019-03-14 09:07
I also have this problem using version 5.2.8 29 / stable.

**Comment by cm3z4** [comment] 2019-03-14 17:05
I just realized there is a repository specifically for the snap package --> https://github.com/ONLYOFFICE/snap-desktopeditors

Should have probably opened this issue there...

**Comment by ShockwaveNN** [comment] 2019-03-21 08:15
Closing as duplicate of https://github.com/ONLYOFFICE/snap-desktopeditors/issues/12

**Closed by ShockwaveNN** 2019-03-21 08:15 UTC
