### ISSUE TITLE
Allow comments to be shown on the right-hand side of the interface

### ISSUE THREAD

**Issue by emes81** [ONLYOFFICE/DesktopEditors#1523] opened 2024-03-11 10:07 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I would like to see OnlyOffice's implementation of comments optimised for two aspects:

1. Usability
2. Familiarity

### 1. Usability

For users of left-to-right languages, it is natural to look to the right (i.e. to the horizontal end) of the text to see comments. This is currently only possible in OnlyOffice in a transient way. Google Docs implements this better, allowing users to choose between hidden, transient, and pinned comments:

![Screenshot from 2024-03-11 10-45-01](https://github.com/ONLYOFFICE/DesktopEditors/assets/25403691/174c99a5-4a69-4a94-a775-591230ad9c53)
![Screenshot from 2024-03-11 10-47-14](https://github.com/ONLYOFFICE/DesktopEditors/assets/25403691/b3c270a4-73b1-47e5-a140-2a2f2b027f93)
![Screenshot from 2024-03-11 10-47-25](https://github.com/ONLYOFFICE/DesktopEditors/assets/25403691/e2cf1111-91f8-4884-89ad-4b8056ee49b4)
![Screenshot from 2024-03-11 10-47-35](https://github.com/ONLYOFFICE/DesktopEditors/assets/25403691/6c5883a2-1518-4ed5-ba56-8f7e2f2a4113)

MS Word allows less choice than OO, but still has an option (not pictured) to hide comments, which are placed in the familiar position on the right: 
![Screenshot from 2024-03-11 10-51-04](https://github.com/ONLYOFFICE/DesktopEditors/assets/25403691/620f05e2-c517-4bdf-974f-d170c3297b28)

OnlyOffice currently shows comments _both on the left and on the right_. This is extremely confusing for users. The non-transient positioning on the left is not a natural place for LTR language users to look for comments, and the transient positioning on the right (in the form of balloons) is too stop-start: comments seem to pop up unpredictably, as there is no clear visual guide for users as to where comments are located (the current implementation, where the commented text is highlighted neon, simply looks like the highlight tool has been used).

### 2. Familiarity
Both Word and Docs, as shown in the images above, always put comments on the right. I've been unable to identify a user benefit of OO departing from this paradigm and showing comments on the left. OO should at place comments on the familiar right-hand-side position (or give users the option to move the non-transient comments pane from the left to the right)

**Comment by matveevms** [comment] 2024-03-12 13:08
Hello, @emes81 . 
We already have such a proposal for improvement #64861.
Our developers are considering the option of independently adjusting the position of comment panels for users. 
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2440. 
Thank you for your request.

**Comment by emes81** [comment] 2024-03-12 13:11
Apologies, I see I already submitted this - I didn't recall making the previous post. Thanks for considering this.

**Comment by matveevms** [comment] 2024-03-12 15:17
Unfortunately, this is our internal bug tracking. We will keep you updated regarding changes in the status of your request.

**Closed** 2024-03-12 15:17 UTC
Labels: duplicate
