### ISSUE TITLE
Spellcheck Broken Under Linux, DEB and FlatPak.

### ISSUE THREAD

**Issue by Daniel-McLarty** [ONLYOFFICE/DesktopEditors#1421] opened 2023-11-13 19:20 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.0

### Expected Behavior

I expect that if I spell something wrong it will spell check and give me the red underline.

### Actual Behavior

It will do nothing and will not spell check.

### Reproduction Steps

1. Open any of the editors
2. Write something wrong
3. Nothing tell you it was wrong

### Additional information

I have tried the DEB and the FlatPak to no change. Yes I have it on in the settings and yes my locale has "en-US.UTF-8 UTF-8" uncommented and generated. It worked under Windows last time I checked, so it may be a Linux thing or it could be a new version thing as I never updated my Windows version of the app. Also I could of sworn that spell check did work for me at one point on this Linux install, maybe an update broke it.

**Comment by maruacat** [comment] 2023-11-14 13:48
Hello, @Daniel-McLarty!
Please tell me if the problem is reproduced in the new version of the editor 7.5.1?

**Comment by Daniel-McLarty** [comment] 2023-11-14 14:48
Something in the update fixed it for me, which is strange because the change log said nothing about spell check.

**Comment by Rita-Bubnova** [comment] 2023-11-14 14:50
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-11-14 14:50 UTC
