### ISSUE TITLE
Crusor size resets to default on cinnamon, when hovering certain elements

### ISSUE THREAD

**Issue by mateusauler** [ONLYOFFICE/DesktopEditors#967] opened 2022-07-03 02:13 UTC
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1.0.215

### Expected Behavior

The mouse cursor size remains the same independently of which mode it's in and which element it's hovering.

### Actual Behavior

Cursor changes size to the default when hovering elements such as a spreadsheet's cells, or the main screen.
It remains the same size when hovering the status bar and the tabs.

### Reproduction Steps

1. Go to Cinnamon's settings and change your cursor size.
2. Open OnlyOffice.
3. Hover the main screen or a spreadsheet's cells.
4. Notice the change in size of the cursor.

### Additional information

This is quite inconsistent. I have only been able to consistently reproduce it by hovering the spreadsheet's cells.

This was tested on real hardware and a VM under QEMU.
Both running Linux Mint Cinnamon 20.3.
Cinnamon version: 5.2.7

**Comment by ShockwaveNN** [comment] 2022-07-04 07:25
I think it may be a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/566

**Comment by simonsaysthis** [comment] 2022-08-11 05:17
I have exactly the same problem on Cinnamon with 200% scaling

**Comment by ShockwaveNN** [comment] 2022-08-11 07:21
Closing this issue, since there is no feedback from OP

**Closed by ShockwaveNN** 2022-08-11 07:21 UTC
Labels: waiting feedback

**Comment by mateusauler** [comment] 2022-08-11 10:27
Sorry for the long wait. I didn't see the notification. I believe it might be indeed a duplicate. I'm not at home right now, so when I get there, I'll analyze it further and comment here.

**Comment by ShockwaveNN** [comment] 2022-08-11 10:36
@mateusauler Ok, thanks, feel free to comment if you find out some proofs that it's separate issue
