### ISSUE TITLE
4.2.5.312 Linux Bug - Font in "Open Local Files" is Missing

### ISSUE THREAD

**Issue by HolgerSontag** [ONLYOFFICE/DesktopEditors#52] opened 2017-06-28 18:38 UTC
Hi,

currently, the open files dialog looks like this for me:
![open document_009](https://user-images.githubusercontent.com/29298555/27654026-3f9748c8-5c41-11e7-877f-06626555534e.png)

I click on File -> Open local file -> Browse and that is the result.

All other fonts look fine and the application is running well. I assume that there is a certain font that I need to install to make this work.

I am running Arch Linux (x64, in english) and I am using the AUR version, but I tried all other versions and they all have the same issue.

I am new to Desktop Editors, so I am not sure if this ever worked properly.

cheers,
Holger

**Comment by lcalaresu** [comment] 2017-07-03 20:38
Same problem here for me! 
Everything looks fine editing documents and spreadsheets. I am even using Japanese and Korean fonts without any problem.
The "open local file" dialog however @_@

I am also using Arch Linux x64 in English (British English to be accurate).

Do you have any clue?

**Comment by uncagedfaraday** [comment] 2017-07-23 07:31
The same exact problem occurs for me, also in Arch Linux x64. My issue occurs in the "open local file" dialog box and in the "Save As" window. When I open desktopeditors in the terminal, all hell breaks loose. Here's a pic: http://i.imgur.com/7WzO0MJ.png.

**Comment by n1441** [comment] 2017-08-07 22:13
Still there.

OS: `Fedora 26 (Workstation Edition)`
DE: `gnome-shell-3.24.3-1`
Software: `onlyoffice-desktopeditors-4.4.1-53`

Reproduced with both wayland and xsession sessions. #58 is a duplicate, and I have a feeling that #28 and #36 are related to this.

**Comment by K0R0L** [comment] 2017-08-08 08:26
We'll try to fix it for the next release

**Comment by Ufeldraku** [comment] 2017-08-11 03:37
K0R0L just became best husbando.

**Comment by n1441** [comment] 2017-08-14 16:35
@K0R0L gratz

**Comment by pizzadude** [comment] 2017-09-03 22:42
Same here, Ubuntu MATE 17.10 (beta)

**Comment by keypey** [comment] 2017-10-07 12:35
Still, same there;

OS: Debian/stretch
DE: XFCE 4.12
Software: onlyoffice-desktopeditors-4.4.1-338

**Comment by jbcoliveira** [comment] 2017-10-11 13:25
Same problem here. 

Manjaro 17
Fedora 26

**Comment by diazbastian** [comment] 2017-10-30 03:14
I can confirm it in fedora 26 and fedora 27 (beta) using Desktop Editors 4.4.1.338.
I guess the solution will come in the big [update to version 5](http://www.onlyoffice.com/blog/2017/09/first-look-at-onlyoffice-online-editors-v-5-0/) (with a very sexy new UI)

**Comment by NathanMaia** [comment] 2017-11-08 16:35
Same for me. Ubuntu 17.10

**Comment by PastorBirt** [comment] 2017-11-24 16:23
Same problem for me using Korora 26 (a Fedora 26 derivative).

**Comment by pizzadude** [comment] 2017-12-08 04:52
I think an outdated CEF caused this, as "Private Internet Access VPN" had the same issue.

**Comment by n1441** [comment] 2017-12-24 19:59
Just updated to `onlyoffice-desktopeditors-4.8.0-83` on Fedora 26 and can confirm the issue is fixed.

Thank you guys!

**Comment by ShockwaveNN** [comment] 2017-12-25 08:05
@n1441 yeah, good to hear.
This problem should be fixed in `onlyoffice-desktopeditors` 4.8

**Closed by ShockwaveNN** 2017-12-25 08:05 UTC
Labels: bug
