### ISSUE TITLE
Chinese garbled characters

### ISSUE THREAD

**Issue by muzhi9018** [ONLYOFFICE/DesktopEditors#1574] opened 2024-05-22 05:40 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

8.0.1

### Expected Behavior

Normal file opening

### Actual Behavior

Opening a file may result in garbled Chinese characters
<img width="1794" alt="image" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/38956027/7b93c732-ae23-43cd-9745-f8a08192509c">
[批量供应商出账金额.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/15398477/default.xlsx)

**Comment by ElenaMaaya** [comment] 2024-05-28 12:55
Hello @muzhi9018!
Thanks for your report! 
Sorry, I can't reproduce this problem on Windows 11 and macOS Monterey Version 12.7.3 in Document Server Version 8.0.1, Desktop Editor version  8.0.1. Please give more details to the problem (operating system settings). Where you open a file, locally or on a portal?  Thank you!

**Comment by ElenaMaaya** [comment] 2024-05-28 14:14
@muzhi9018, problem reproduces in Desktop Editor macOS Monterey 12.7.3 v. 8.0.1.
This is a known Bug 65158 in our  issue tracker. 
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/1428

**Closed** 2024-05-28 14:35 UTC
Labels: duplicate
