### ISSUE TITLE
Creating a new document from the right-click context menu results in an unecessary tab titled "Opening..."

### ISSUE THREAD

**Issue by PJSingh5000** [ONLYOFFICE/DesktopEditors#536] opened 2020-12-30 01:14 UTC
**Do you want to request a *feature* or report a *bug*?**

**Report a Bug**

**What is the current behavior?**

Right clicking on the ONLYOFFICE icon in the Ubuntu Dock and selecting "New Document", New Spreadsheet", or "New Presentation" opens two new tabs in ONLYOFFICE:
- Tab for the new document
- Tab titled "Opening..."

![ONLYOFFICE opening tab](https://user-images.githubusercontent.com/19394936/103323038-f415d080-4a0e-11eb-9ca1-a69aeb82c5f2.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Add the ONLYOFFICE application to the Ubuntu Dock.

2. Click on ONLYOFFICE in the Dock to launch it.

3. Right click on the ONLYOFFICE icon in the dock to display the context menu.

4. Select "New Document".

5. A new tab labeled "Document 1.docx" will be added to the ONLYOFFICE window.

6. Notice that _another_ tab labeled "Opening..." also appears in the ONLYOFFICE window.

![image](https://user-images.githubusercontent.com/19394936/103322822-d98f2780-4a0d-11eb-85fd-1effa98e0ea9.png)

7. Each time a new document is created, using the Right click context menu, a new document tab and an "Opening..." tab are added. Repeat steps 3 and 4 to demonstrate this.

**What is the expected behavior?**

The superfluous "Opening..." tab should not be created when a new document is added from the right click context menu in the Ubuntu Dock.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

- onlyoffice-desktopeditors 6.1.0-90
- Ubuntu 20.04.1 LTS
- I do not know if this worked in previous versions of DesktopEditors.

**Comment by PJSingh5000** [comment] 2020-12-30 01:36
A also noticed that simply left-clicking on the launcher in the Ubuntu dock multiple opens multiple tabs titled "Opening..."

So selecting "New" from the context menu is not required to experience this bug.

![image](https://user-images.githubusercontent.com/19394936/103324341-25919a80-4a15-11eb-94e1-62490d90720e.png)

**Comment by Rita-Bubnova** [comment] 2020-12-30 11:06
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/529.

**Closed** 2020-12-30 11:07 UTC
