### ISSUE TITLE
Default print preferences

### ISSUE THREAD

**Issue by ayotree** [ONLYOFFICE/DesktopEditors#1493] opened 2024-02-05 05:18 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

version 8.0.0.99

### Expected Behavior

Onlyoffices should favor the printer settings, or skip Onlyoffice's printing settings and open the system printing dialog by default.

### Actual Behavior

Since #1313 was closed, I need to open a new issue
My printer was set to print on both sides.
Onlyoffice always set it to one side, I need to change it to both sides everytime I print a new document.
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/8979247/332c9c99-895c-4c89-9a28-2eb61d612dfa)

**Comment by Rita-Bubnova** [comment] 2024-02-06 10:14
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/1313.
[Issue](https://github.com/ONLYOFFICE/DesktopEditors/issues/1313) has been reopened.

**Closed by Rita-Bubnova** 2024-02-06 10:14 UTC

**Comment by raceviper13a** [comment] 2025-03-19 11:41
Please prioritize this.
