### ISSUE TITLE
 MailMerge - milestone 2023 of an old request

### ISSUE THREAD

**Issue by HerrJM** [ONLYOFFICE/DesktopEditors#1386] opened 2023-10-12 15:02 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello!
I've seen two requests from 2021 of MailMerge in the Desktop version of OnlyOffice. So far I understood, you had issues with it, but how advanced is the work on this feature please?
We can't really use the DesktopEditor as alternative for now because of this.
Thank you

**Comment by Rita-Bubnova** [comment] 2023-10-13 07:25
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/733.

**Closed by Rita-Bubnova** 2023-10-13 07:25 UTC
