### ISSUE TITLE
SMB-locked file not opening as read-only on MacOS

### ISSUE THREAD

**Issue by SteffeyDev** [ONLYOFFICE/DesktopEditors#1606] opened 2024-06-17 20:25 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

8.0.1

### Expected Behavior

When I open a .docx file on an SMB share that is locked because someone else has it open, I expect it to open the file in read-only mode, like it does on Windows 10

### Actual Behavior

On MacOS 14.5, when connecting to SMB share using Finder, it does not open a locked file as read-only, and allows me to overwrite the other user's changes.

### Reproduction Steps

1. Connect to same SMB share on MacOS and Windows
2. Open same .docx file on Windows first, then MacOS
3. Notice that both are opened in read-write mode, and thus can overwrite each other

### Additional information

My SMB server is Samba on Linux, with locking enabled. I've confirmed with `smbstatus` on the SMB server that the Windows OnlyOffice DE does lock files, but the MacOS OnlyOffice DE does not lock the file. I've also used WireShark to verify that no locking SMB commands are sent over the network.

**Comment by LuckySpecialist** [comment] 2024-06-21 08:22
Hi @SteffeyDev, it's already discussed in #1413.
I will add your request to Bug 48823.
Thanks for the feedback

**Comment by Rita-Bubnova** [comment] 2024-06-24 08:03
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/1413.

**Closed by Rita-Bubnova** 2024-06-24 08:03 UTC
Labels: feature request
