### ISSUE TITLE
Add support for Aarch64

### ISSUE THREAD

**Issue by liberodark** [ONLYOFFICE/DesktopEditors#1201] opened 2023-02-09 07:49 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hi,

I want to use your software on manjaro aarch64 you can make a build for arm64 ?
Have see you have a build for apple silicon too.

Best Regards

**Comment by MaicolFA** [comment] 2023-02-21 00:13
yes, compatibility with ARM devices is required.
very necessary.
onlyoffice needs compatibility with: windows arm and linux arm

**Comment by alfredonodo** [comment] 2023-07-07 15:02
Hi,
do you have any updates on this?
Thank you

**Comment by Rita-Bubnova** [comment] 2023-08-18 11:11
Hello, @liberodark, @ghost, @alfredonodo.
Support ARM for Linux - this is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/270.
Support ARM for Windows - this is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/988.
You can follow these issues for updates.

So I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-08-18 11:11 UTC

**Comment by defencedog** [comment] 2025-02-07 01:26
With rising SBC popularity certainly OnlyOffice will be great for ARMBIAN under GNOME
