### ISSUE TITLE
How to build DesktopEditors in windows ?

### ISSUE THREAD

**Issue by wxz879526** [ONLYOFFICE/DesktopEditors#932] opened 2022-05-28 11:51 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

How to build DesktopEditors in windows ?

**Comment by ShockwaveNN** [comment] 2022-05-29 19:31
Hi, I'll mark this as duplicate of https://github.com/ONLYOFFICE/build_tools/issues/105#issuecomment-643986828

Sorry, but we still have no proper instruction for windows build

**Closed by ShockwaveNN** 2022-05-29 19:31 UTC
