### ISSUE TITLE
Gradient fill style radial does not appear as expected

### ISSUE THREAD

**Issue by mrosemeier** [ONLYOFFICE/DesktopEditors#1420] opened 2023-11-13 14:25 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

 7.5.0.127

### Expected Behavior

Observation from a PPT imported slide: Color gradient fill style radial should start at a custom center position, e.g., at shape corners, and zoom into the radial center:
![expected](https://github.com/ONLYOFFICE/DesktopEditors/assets/8947203/f0276476-2abb-45ae-a7a8-591a577c47d7)

### Actual Behavior

Radial center and zoom seem not editable:
![buggy](https://github.com/ONLYOFFICE/DesktopEditors/assets/8947203/b6cdf8ec-ee17-4ada-af09-bb1b3e5f29d8)

**Comment by Rita-Bubnova** [comment] 2023-11-14 09:58
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1971.

**Closed** 2023-11-14 16:50 UTC
Labels: duplicate
