### ISSUE TITLE
change position of pop-up on track change mode 

### ISSUE THREAD

**Issue by ggrrll** [ONLYOFFICE/DesktopEditors#684] opened 2021-07-26 13:28 UTC
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.2.0.148

### Expected Behavior

pop-up  should not cover text, where cursor is, while typing

### steps 

* switch on track change-mode
* set zoom to fit screen width
* write a whole paragraph (full page width)

### Actual Behavior

pop-up  covers text, where cursor is, while typing (the pop-up it's on the right of the screen, but still to much on the left _when file is zoomed to fit width of the screen_)

**Comment by ShockwaveNN** [comment] 2021-07-26 13:41
Hi, could you record video with this problem?

**Comment by ggrrll** [comment] 2021-07-26 15:43
it's quite simple:

*switch on track change-mode
* set zoom to fit screen width 
* write a whole paragraph (full page width)

the pop-up window that tells you about modification, comments, etc... covers what you writing, at the extreme right of the line 
(in order to be able to see what I am writing  I have to decrease the zoom)  

it would be nice to change somehow the position/size/shape or the pop-up

thanks

**Comment by Rita-Bubnova** [comment] 2021-07-27 07:07
This issue actual in Document Server.
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/878.

**Closed** 2021-07-27 07:10 UTC
Labels: waiting feedback

**Comment by ggrrll** [comment] 2021-07-27 09:34
ok thanks -- well, with that name, it was almost impossible to find it :sweat_smile:

**Comment by ShockwaveNN** [comment] 2021-07-27 10:20
@ggrrll I agree with you, changed title of issue, if you got better ideas - I open to them )
