### ISSUE TITLE
Credentials are asked again, while I should stay logged in

### ISSUE THREAD

**Issue by biva** [ONLYOFFICE/DesktopEditors#599] opened 2021-04-19 14:02 UTC
I guess it's a bug

**What is the current behavior?**
1. Configure the connection to a Nextcloud server
2. Enter the credentials and successfully log in
3. Close Desktop Editor
4. Open it again
5. Connect to cloud (the same Nextcloud server)
6. Credentials are asked again

**What is the expected behavior?**
I would like to stay logged in, without having to enter all the credentials each time

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
version 6.2.0.148 on Windows 10
I don't think it worked before.

**Comment by seldon1000** [comment] 2021-04-21 12:39
Same here. OnlyOffice doesn't remember the connection.

OS: Arch Linux
OO version: 6.2.0.148
Nextcloud version: 20.0.9 (provided by Hetzner)

I can't tell if it has ever worked.

**Comment by Rita-Bubnova** [comment] 2021-06-01 11:35
Hello, @biva.
Sorry, I can't reproduce your problem. I use ONLYOFFICE Desktop Editors version 6.2.0.148, Nextcloud 21.0.1, Windows 10.

Could you share your Nextcloud and attach a video with the problem?
Please send an information to support@onlyoffice.com with the subject line "Github DesktopEditors#599".

**Comment by biva** [comment] 2021-06-01 20:48
I don't use the desktop anymore. But I remember that this was kind of solved if a specific box is ticked during login. Sorry to not help more.

**Comment by ShockwaveNN** [comment] 2021-06-02 05:49
@biva In that case I'll close this issue

**Closed by ShockwaveNN** 2021-06-02 05:49 UTC
