### ISSUE TITLE
OnlyOffice corrupts my pptx

### ISSUE THREAD

**Issue by marco-calautti** [ONLYOFFICE/DesktopEditors#952] opened 2022-06-10 11:01 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.1.0.215

### Expected Behavior

After saving the pptx, Microsoft Powerpoint should be able to open it without errors

### Actual Behavior

After saving the pptx with only office, Powerpoint says the pptx is corrupted, and forces me to exit.

**Comment by ShockwaveNN** [comment] 2022-06-10 11:29
Hi, sorry to hear that

> 7.2.0.215

Is there a typo in this version? We didn't release v7.2

> After saving to pptx

We definitely need original file before saving to pptx with ONLYOFFICE

**Comment by marco-calautti** [comment] 2022-06-10 15:46
Hi, I fixed the typo. I do not have the original version, since I applied many changes, but I have isolated the slide that causes the error. This contains some animations (although other slides also contain animations but do not cause any issue).

Both Office 2010, as well as Office online tells me the file is corrupted
[test(2).pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8880311/test.2.pptx)

**Comment by ShockwaveNN** [comment] 2022-06-10 15:49
To be clear - if this is already a broken file - sorry, but I don't think we can reverse-engineered it to find the reason it was broken

Maybe you can find original file in, before saving it via our product in some version history of DMS?

**Comment by marco-calautti** [comment] 2022-06-10 15:52
As I said, the file was fine before modifying it with OnlyOffice. The problem is that after modifying it with OnlyOffice, OnlyOffice is fine with the file, while MS Office says it is corrupted.

**Comment by marco-calautti** [comment] 2022-06-10 15:54
I can share with you the original pptx, if you like, but this file is so different from the one I got, after modifying it with OnlyOffice, which I do not think it is going to be any useful. Here is the original file:
[12min_PODS2021 - Marco Calautti.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8880359/12min_PODS2021.-.Marco.Calautti.pptx)

**Comment by ShockwaveNN** [comment] 2022-06-10 16:15
Ok, got you, I thought only saving this file in pptx is enough to raise exceptions in MS Office

I understand that you need to do some modification to that file and after that save to pptx and file is broken

Not sure that it's enough info, but we'll try to reproduce this problem

**Comment by dikey0ficial** [comment] 2023-02-20 21:28
The same when trying to upload to Google Docs.

**Comment by dikey0ficial** [comment] 2023-05-02 16:31
> I don't think this case is the same.
@XDmitryK I've just updated to 7.3.3.50, and, as I see, this issue does not appears again. So I think there were the same bug

**Comment by Rita-Bubnova** [comment] 2023-08-03 10:51
@dikey0ficial Thank you for answear.
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-08-03 10:51 UTC
