### ISSUE TITLE
Error(s) while saving edits to LibreOffice docx in ONLYOFFICE, unable to close ONLYOFFICE

### ISSUE THREAD

**Issue by crlorentzen** [ONLYOFFICE/DesktopEditors#473] opened 2020-10-02 14:02 UTC
My mother encountered this issue, and I was able to use her document as a base for reproduction.
She just recently installed ONLYOFFICE as a replacement to LibreOffice. I suggested it since it is more similar to MS Office and is supposed to be better at MS Document formats due to, If I understand correctly, the use of the OOXML format internally, instead of doing format juggling like Libre/OpenOffice.

## Discovery

She was working on updating a docx (Word 2007-365) which was originally created in LibreOffice. When she tried to save, the file she was updating in ONLYOFFICE, she encountered an error: "An Error has occurred while saving the file."

- After this error she tried the close the document tab, and/or the entire window one of two results were seen
  - The button shows a click action but doesn't close
  - It offers to save the file before closing

- If one gets the save offer one can say no and ONLYOFFICE will close
- If one says yes to the save offer one will get the same error. And we can try to close the window again.
- If there is no save offer, which will happen after a few trials, then the window won't close and must be killed (Task Manager/taskkill)

- The lost file will be available in the Recover files section when starting ONLYOFFICE again, trying to save these will show the same issue that caused them to be lost. 

## Bug Description
Error while trying to save a docx document originally created in LibreOffice (or elsewhere) and edited in ONLYOFFICE. After multiple attempts to save when closing ONLYOFFICE, window stops offering to save and is not close-able.

![image](https://user-images.githubusercontent.com/25350890/94882046-e3b48080-0434-11eb-9b09-e5cd95f97eb8.png)

## Reproduction
- Tested on
  - Windows 10 x64 1503, 1904, and 2004
  - ONLYOFFICE Desktop Editors version 5.6.4.20
- File used in reproduction: 
[test.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/5315697/test.docx)
- Video to gif reproduction: (Incorrectly made gif, let me know if a higher quality is desired)
![test.gif](https://user-images.githubusercontent.com/25350890/94883813-95ee4700-0439-11eb-8618-ece1392b1f5a.gif)

1. Open test.docx with ONLYOFFICE
1. Make a change to the document, I select the first line and hit Ctrl-E to center the line
1. Attempt to save the file. Encounter error.
1. Attempt to close the window. Say yes to save (may require more than one time to start getting no save offer)
1. Attempt to close the window/tab. Encounter failure to close either the tab or the ONLYOFFICE window.

I hope that the contrived example can help discover what is getting stuck in ONLYOFFICE. 

### Related Windows Event Log
Potentially
```
The program editors.exe version 5.6.4.20 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: e44
 Start Time: 01d69865decfa2e5
 Termination Time: 4294967295
 Application Path: C:\Program Files\ONLYOFFICE\DesktopEditors\editors.exe
 Report Id: 5b8ebc2f-3eed-4800-bc31-accdc71da0b2
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Top level window is idle
```

**Comment by Rita-Bubnova** [comment] 2020-10-02 15:11
Hello, @crlorentzen.
Thank you for detailed report.

I can confirm - bug reproduce in Desktop Editors version 5.6.4.20 (OS: Windows 10 Home 2004).
In the test ONLYOFFICE Desktop Editors version 6.0.0.110, the problem is not reproduced.
We hope to release this version as next major update, but currently I cannot give you any ETA.

**Comment by ShockwaveNN** [comment] 2020-10-16 09:22
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.

**Closed by ShockwaveNN** 2020-10-16 09:22 UTC
Labels: bug, fixed
