### ISSUE TITLE
Remember last scroll position when opening document 

### ISSUE THREAD

**Issue by ags1234** [ONLYOFFICE/DesktopEditors#1318] opened 2023-06-30 17:02 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

When closing documents, remember last scroll position and automatically scroll there when opening that document again.
This would greatly help when editing larger documents.

**Comment by Rita-Bubnova** [comment] 2023-07-05 07:32
This is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/277.

**Closed** 2023-07-05 07:36 UTC
Labels: duplicate

**Comment by hovereffect** [comment] 2025-01-02 13:50
This issue is still a problem, why is it marked as Closed? @DenisDeeSign

**Comment by Rita-Bubnova** [comment] 2025-01-09 10:53
@hovereffect, The issue is closed as it is a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2289.
