### ISSUE TITLE
Window is unable to capture focus when opening a document with an already running instance 

### ISSUE THREAD

**Issue by mateusauler** [ONLYOFFICE/DesktopEditors#968] opened 2022-07-03 02:21 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1.0.215

### Expected Behavior

The OnlyOffice window should pop up when a document is opened from the file browser.

### Actual Behavior

The file browser loses focus (i.e. the status bar is greyed out) but the OnlyOffice window does not pop up.

### Reproduction Steps

1. Open OnlyOffice.
2. Open the file browser.
3. Open a document.
4. Notice the window did not gain focus properly.

### Additional information

This was tested on real hardware and a VM under QEMU.
Both running Linux Mint Cinnamon 20.3.
Cinnamon version: 5.2.7

**Comment by ShockwaveNN** [comment] 2022-07-04 07:26
I think it may be a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/921

**Comment by mateusauler** [comment] 2022-08-11 10:28
I also commented this on #967, but sorry for the wait. I also think this might be a duplicate and will analyze further when I get home.

**Comment by ShockwaveNN** [comment] 2022-08-11 10:36
@mateusauler Ok, thanks, I'll close this issue, but feel free to comment and I'll reopen it if you find some proofs that it's a separate issue

**Closed by ShockwaveNN** 2022-08-11 10:36 UTC
Labels: waiting feedback
