### ISSUE TITLE
Ctrl+T should open a new tab i.e. the OnlyOffice Home tab

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#168] opened 2019-01-15 10:16 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Ctrl+T does nothing.

**What is the expected behavior?**
Ctrl+T should open a new tab i.e. the OnlyOffice Home tab. This brings it inline with browsers, file managers and other apps on all platforms and is an expected behavior.

![screenshot from 2019-01-15 15-45-43](https://user-images.githubusercontent.com/22585732/51173956-a44ea500-18dc-11e9-8cf3-119a881a20fe.png)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v5.2.4

**Comment by uncertainquark** [comment] 2019-01-16 04:07
Can you assign an "Enhancement" label to this?

**Comment by ShockwaveNN** [comment] 2019-01-16 06:58
@uncertainquark done

**Comment by Medanna** [comment] 2019-03-27 14:37
Hello @uncertainquark, thank you for your enhancement. 
Opening a new tab with Ctrl+T key is an expected behavior for browsers, but it's expected that an empty tab is opened, not the start page. It lacks hotkey for quick file creation, isn't it? We mean that Ctrl+N is more regular shortcut in desktop apps for it. There are some questions to solve to add Ctrl+N combination, i.e. how to choose filetype which you need to create. It will be decided soon.

**Comment by uncertainquark** [comment] 2019-08-09 04:36
Any update on this?

**Comment by Medanna** [comment] 2019-08-09 09:55
Hi @uncertainquark it's under discussion.

**Comment by Rita-Bubnova** [comment] 2020-09-05 20:13
Keyboard shortcut Ctrl+N to create a new file is discussed here https://github.com/ONLYOFFICE/DesktopEditors/issues/200.

**Comment by ShockwaveNN** [comment] 2020-09-06 07:26
I'll close this issue since Ctrl+N will not used as shortcut

**Closed by ShockwaveNN** 2020-09-06 07:26 UTC
Labels: enhancement
