### ISSUE TITLE
Feature request: Tool to insert summary inside document

### ISSUE THREAD

**Issue by danielmaurer** [ONLYOFFICE/DesktopEditors#65] opened 2017-09-23 18:19 UTC
Summary that is Table of contents is essential to work on a document. It's a feature very important.

**Comment by ShockwaveNN** [comment] 2017-09-25 08:08
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/20

**Closed by ShockwaveNN** 2017-09-25 08:08 UTC
