### ISSUE TITLE
Cannot display fonts in their Chinese names

### ISSUE THREAD

**Issue by pikakolendo02** [ONLYOFFICE/DesktopEditors#710] opened 2021-09-15 22:56 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.3.1.56

### Expected Behavior
![图片](https://user-images.githubusercontent.com/15796641/133523351-2dbe27de-2b93-4ac2-bd5c-2c83d7a5e043.png)
Chinese fonts show their Chinese names so I can find them easily, like MS Office.

### Actual Behavior

![图片](https://user-images.githubusercontent.com/15796641/133523899-f19ab9ff-22ef-4ec1-9094-59773b582d5d.png)
Only English names show, so they mix with English-only fonts and hard to find.

And then OnlyOffice cannot recognize the font name in Chinese when edit a file created by MS Word.
For example, "等线" (DengXian) is actually a sans-serif font but OnlyOffice display it as serif.
![图片](https://user-images.githubusercontent.com/15796641/133520713-7b3964e2-9a5a-4848-a06f-48aca4c0f4c6.png)
![图片](https://user-images.githubusercontent.com/15796641/133521406-27dae873-7d30-4359-b214-796584be0775.png)
I need to manually select it and change the font into DengXian.

### Reproduction Steps

Create an new .docx file in MS Office (Windows), input a Chinese charater, save it.
Share the file with Linux and open with OnlyOffice.
The font may change.

### Additional information

Thanks for the awsome free office suite!

**Comment by Rita-Bubnova** [comment] 2021-09-16 07:49
Hello, @pikakolendo02.
This issue is actually in Document Server.
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/332.

**Closed** 2021-09-16 07:51 UTC
