### ISSUE TITLE
Autofill Formula for same column not working

### ISSUE THREAD

**Issue by kiraitachi** [ONLYOFFICE/DesktopEditors#510] opened 2020-11-16 12:03 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Clicking on the low right edge of a formula cell does not autofill the formula for the whole column
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/40744673/99250426-e8c66700-280b-11eb-9f15-bebb54631d92.png)
![image](https://user-images.githubusercontent.com/40744673/99250439-f0860b80-280b-11eb-8bf5-1300194e68cf.png)
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Kubuntu 20.10 and version of Desktop Editor 6.0.1

**Comment by Rita-Bubnova** [comment] 2020-11-18 16:00
Hello, @kiraitachi.
Sorry, I can't reproduced your problem, autofill is works.
I am using Kubuntu 18.04 and ONLYOFFICE Desktop Editors version 6.0.1.32.

Could you attach a video with problem?

**Comment by HectorB-2020** [comment] 2021-01-04 11:56
Hi @kiraitachi !

Do you mean "single click" or "double click" on the "low right edge of a formula cell"?

In MS Excel double click cause auto-filling this column up to the lowest cell on the neighboring column.

Here is an example:
![OO1](https://user-images.githubusercontent.com/64358003/103532582-9533d980-4e9c-11eb-93c8-d13f31fde79c.png)

And here is expected result after the "double clicking" on the dot highlighted in red:
![OO2](https://user-images.githubusercontent.com/64358003/103532642-ac72c700-4e9c-11eb-923d-5f582bbbd7d5.png)

My version 6.1.0.90.

BTW, @Rita-Bubnova if it's not the same, I'll submit a separate feature request.

**Comment by kiraitachi** [comment] 2021-01-04 12:02
Hi @HectorB-2020 indeed that is the feature I'm talking about. Sorry I hadn't responded earlier.

@Rita-Bubnova as @HectorB-2020  showed. Double click will autofill those values with the formula stated on the cell. This is usefull when you have around 5000 cells to fill-up automatically, since drag down becomes a pain...

Cheers!

**Comment by HectorB-2020** [comment] 2021-01-04 13:02
@kiraitachi , please pay attention that even in MS Word this works only with adjacent columns like in my example above: "A" and "B". It _won't_ automatically work like in your screenshot - columns "A" and "C".

**Comment by kiraitachi** [comment] 2021-01-04 14:56
> @kiraitachi , please pay attention that even in MS Word this works only with adjacent columns like in my example above: "A" and "B". It _won't_ automatically work like in your screenshot - columns "A" and "C".

Hi @HectorB-2020

If you look at my example what is actually doing is autofilling a formula from the C1 cell. The C1 cell has a referrenced value from A1, so autofilling in C2 should automatically detect the next value in the array which is A2 for that given cell. Maybe it was a complicated example, but it was my real life scenario.

**Comment by Rita-Bubnova** [comment] 2021-01-11 15:57
@kiraitachi, 
Am I correct understanding that this issue is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/403 ?

**Comment by kiraitachi** [comment] 2021-01-11 17:33
> @kiraitachi,
> Am I correct understanding that this issue is a duplicate of #403 ?

After reviewing #403  yes indeed seems like a duplicate.

Thanks @Rita-Bubnova  for double checking. Is there any ETA to implement this? Its a core feature, very much needed for lots of companies during their Key Performance Indicator "excel" builds...

**Comment by Rita-Bubnova** [comment] 2021-01-12 08:15
@kiraitachi, sorry, currently we have no ETA.

We are closing this issue, because the issue is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/403.

**Closed** 2021-01-12 08:21 UTC
Labels: waiting feedback
