### ISSUE TITLE
Unused space between tab and body

### ISSUE THREAD

**Issue by SoftExpert** [ONLYOFFICE/DesktopEditors#820] opened 2022-01-21 05:51 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.0.127

### Expected Behavior

No unused space between the tab and its content should exist.

### Actual Behavior

After creating a new Spreadsheet, Document or Presentation, under the tab there is an empty area, wasting screen space:
![image](https://user-images.githubusercontent.com/1254018/150472595-8e1e3fc7-7b99-4cbf-b435-7414b70d86bb.png)

I occurs also when opening an existing file.

### Reproduction Steps

Start ONLYOFFICE
1. create a new Spreadsheet, or Document or Presentation

### Additional information

Screen resolutions tested:
1920x1080
2560x1440

My desktop environment is KDE
![image](https://user-images.githubusercontent.com/1254018/150473302-5d778130-f732-40aa-9af5-982274cffa3f.png)

**Comment by ShockwaveNN** [comment] 2022-01-21 07:56
Hi, you got very interesting borders of DesktopEditor window (orange ones)

Do you enable some additional settings?

I'm on Kubuntu 20.04 with KDE 5.18.5 and have no borders and no extra lines

![image](https://user-images.githubusercontent.com/668524/150488398-e4706182-e449-4829-a7ac-931b3f9a2f8f.png)

**Comment by SoftExpert** [comment] 2022-01-21 17:23
Hi,
I had enabled the system titlebar - it better integrates with the desktop.
![image](https://user-images.githubusercontent.com/1254018/150571151-ce55b669-3773-4c05-a963-6c05ee40f401.png)
When setting the option to custom then the unused space dissapears.

As for the borders: BreezeEnhanced with Tzen-Dark color theme and Kvantum Tzen-Dark theme tweaked a little bit.

**Comment by SoftExpert** [comment] 2022-01-21 19:17
I forgot to add:  the previous version (6.*) did not had this issue when then titlebar was set to system.

**Comment by ShockwaveNN** [comment] 2022-01-23 10:20
Can confirm it

Got same result by editing `~/.config/onlyoffice/DesktopEditors.conf` and changing `titlebar=system`:


![Screenshot_20220123_131427](https://user-images.githubusercontent.com/668524/150673931-a8cd4f96-f32f-4db4-a795-8e6fcb0a4e9d.png)

I've created issue 55041 in our private issue tracker to handle this situation

**Comment by Blacksuan19** [comment] 2022-01-28 03:28
this might be related, on a tiling wm with system titlebars the titlebar is cut in the middle
![2022-01-28_11-26](https://user-images.githubusercontent.com/10248473/151482256-5049afb0-6abe-40b3-bb1f-60b541265a22.png)
![image](https://user-images.githubusercontent.com/10248473/151482343-63773c95-a471-402c-b928-5fa8558c7781.png)

**Comment by ShockwaveNN** [comment] 2022-01-28 07:50
> on a tiling wm.

Hi could you clarify which OS it was and which tiling wm you've using, I'll try to reproduce it also, because I'm not sure that those are 100% related to same problem

**Comment by Blacksuan19** [comment] 2022-01-28 08:12
> > on a tiling wm.
> 
> Hi could you clarify which OS it was and which tiling wm you've using, I'll try to reproduce it also, because I'm not sure that those are 100% related to same problem

on arch with bspwm, setting the app scaling to 100% fixes that white line and then it turns into this issue, empty space below titlebar

![image](https://user-images.githubusercontent.com/10248473/151510910-b7ad3ea7-e2aa-4562-8df5-0f6e01d24921.png)

**Comment by ShockwaveNN** [comment] 2022-01-28 15:12
@Blacksuan19 Tried to setup `bspwn` on my arch in VirtualBox and got an only black screen

Maybe that's because I'm not familiar with tiling systems at all, tried several workarounds but no result

So I think we should wait until the original issue is resolved and if not - we investigate `bspwm` issue separately

**Comment by ShockwaveNN** [comment] 2022-02-03 12:38
I think we've fixed this problem in https://github.com/ONLYOFFICE/desktop-apps/commit/7d60392f974357ef55bda24b9bc87b6cc814bcae

It will be released as 7.0.1

You can try out it by[ this link](https://s3.eu-west-1.amazonaws.com/repo-doc-onlyoffice-com/onlyoffice/testing/ubuntu/onlyoffice-desktopeditors_7.0.1-15_amd64.deb)

But please not this is not a stable version and can contain any number of bugs, but problem with title bar should be fixed

**Comment by SoftExpert** [comment] 2022-02-03 13:51
I confirm, it now displays correctly (with both _system_ and _custom_ options in the **titlebar** parameter):
![image](https://user-images.githubusercontent.com/1254018/152355444-5de26636-8e1f-49a7-a317-ec7148c42240.png)
Thank you for the quick fix !

**Comment by ShockwaveNN** [comment] 2022-05-20 14:47
I'll close this issue since it should be resolved

**Closed by ShockwaveNN** 2022-05-20 14:47 UTC
Labels: bug, fixed
