### ISSUE TITLE
Document Editor does not indicate spelling errors in uppercase words.

### ISSUE THREAD

**Issue by joselmm** [ONLYOFFICE/DesktopEditors#1441] opened 2023-12-06 12:30 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

 7.5.1.23

### Expected Behavior

I hope the editor highlights the spelling error with a red line underneath uppercase words.

### Actual Behavior

The editor does NOT indicate the spelling error with a red line underneath uppercase words.

### Reproduction Steps

1. Set the dictionary language to Spanish (Spain).
2. Type the misspelled word in uppercase (for example, "MURCIELAGY," which should be correctly spelled as "MURCIELAGO").
3. Once you type the last letter of the word, press the spacebar.
4. The red line will not appear underneath the misspelled word (which does appear with "Murcielagy" and "murcielagy").

### Additional information

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/95531879/3fa82291-38d0-4d6e-bed2-f58063704aa9)

**Comment by HectorB-2020** [comment] 2023-12-11 18:35
I beg your pardon, isn't a default proofing setting?
`File` -> `Advanced Settings` -> `Proofing`

**Comment by joselmm** [comment] 2023-12-12 00:55
> I beg your pardon, isn't a default proofing setting? `File` -> `Advanced Settings` -> `Proofing`

thanks it worked ;) but the spanish dictionary is still quite incomplete.

**Comment by ElenaMaaya** [comment] 2023-12-13 11:13
Hello @joselmm!
Thank you for report!
The problem is not repeated in Desktop Editor version 7.5.1 on Windows 11. 
Please check these settings File -> Advanced Settings -> Proofing -> clear both checkbox "Ignore words in UPPERCASE" -> Apply

Hi @HectorB-2020, thanks :)

**Comment by Rita-Bubnova** [comment] 2024-01-09 08:58
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-01-09 08:58 UTC
