### ISSUE TITLE
Document cannot be edited nor saved while in Collaboration Display Mode Final  + File corruption in any mode

### ISSUE THREAD

**Issue by bhlevca** [ONLYOFFICE/DesktopEditors#1042] opened 2022-10-08 23:26 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2

### Expected Behavior

Editing shoudl be available in Collaboration ->  Display Mode -> Final, 

It allows for clean editing while the deleted parts are hidden.

### Actual Behavior

The document cannot be edited nor saved while in Collaboration Display Mode Final, while the editing and saving works while the viewing is set to only markup or markup and balloons the document

### Reproduction Steps

1) write a text
2) save it
3) enable tracking
4) modify some text
5) co to Collaboration ->  Display Mode -> Final
6) try to edit or save

**Comment by bhlevca** [comment] 2022-10-12 03:19
I have more on this. This version also does not allow saving in Final mode. This is absurd. I understand that this is a preview but why not allow saving?

In addition, I have a large file and at some point, the editor was probably corrupted and saved the file as a 0 (zero) size file, making me l lose everything I edited today.  

Saving as docx or odt din not work. I managed to save only in epub and pdf.

 I will have to manually edit the work I have done today starting from a recovery file that luckily was saved earlier today and read from the PDF file the changes that were tracked.

Could you create these recovery files more often until you manage to stabilize the product?  

I will have to switch back to LibreOffice or WPS until you fix this ugly bug.

**Comment by TatianaKirillova** [comment] 2022-10-12 09:58
Hello, [@](https://github.com/michal-barteczko)[bhlevca](https://github.com/bhlevca)
Thanks! I can confirm that the problem exists. I created ticket 59347 in our private  tracker with your issue.

**Comment by HectorB-2020** [comment] 2022-10-16 08:52
@bhlevca, you are reporting this for Linux (deb) but I've faced file corruption on the latest Window version as well. Thankfully I had a copy so I went on with its editing. What connects our cases is that we both used collaboration and tracking changes.

**Comment by TatianaKirillova** [comment] 2022-10-18 09:22
@bhlevca, the issue with not being able to print in Final/Original mode has been fixed in version 7.2.1.

**Comment by bhlevca** [comment] 2022-10-18 12:03
Thanks, this should not be considered fixed because file corruption is the more important bug. Unfortunately I put two problems in one because I thought that they are related

**Comment by ShockwaveNN** [comment] 2022-10-21 19:04
DesktopEditors v7.2.1 are released and this problem should be fixed

**Closed by ShockwaveNN** 2022-10-21 19:04 UTC
Labels: bug, fixed

**Comment by bhlevca** [comment] 2022-10-21 20:35
OK, so that includes the  file corruption fix?

**Comment by ShockwaveNN** [comment] 2022-10-21 20:40
I think so

**Comment by sskdv** [comment] 2023-08-23 11:16
Good afternoon. Please tell me, was it possible to solve or defeat the problem with saving files? The case when when saving a file it becomes zero in size?!

**Comment by TatianaKirillova** [comment] 2023-08-23 14:04
@bhlevca Is your problem with saving the file still relevant?

**Comment by TatianaKirillova** [comment] 2023-08-23 14:28
@bhlevca thank you! 
I hope this problem doesn't reappear. If you have any questions, please contact us!

**Comment by sskdv** [comment] 2023-08-24 04:23
The problem is more urgent than ever. We have a domain network on Windows. The ball server is running on Windows Server 2012R. Client machines on Alt Linux 10.1. Working with the ball on SMB. The strangest thing is that the situation with saving a file to zero happens rarely and with different files. Sometimes saving takes place normally. I dug all over the Internet and came to the conclusion that there is a whole bunch of problems. Too rattling a mixture of Windows Xp + Linux and working through samba. Taking into account the specifics of the protocol (at the time of saving, the session started to edit the file does not work out to the end, or somehow ends incorrectly). Also, bugtrackers managed to dig up the fact that two identical products OnlyOffice and P7 Office have one similar problem on Unix systems. As an option to solve the problem, it is to ask developers to implement the function of an additional (Enabling at the request of the user) function of the main file saving, and an additional backup copy, for example, to a local folder. Other solutions to the problem on the data

**Comment by trofim24** [comment] 2023-08-24 06:03
@sskdv if you need help please create new issue and describe your problem with additional information about running systems and all steps to reproduce

this issue is only "save" in "Final/Original mode"
