### ISSUE TITLE
 [Feature] Request for CSV File export

### ISSUE THREAD

**Issue by Grumbyy** [ONLYOFFICE/DesktopEditors#751] opened 2021-11-05 09:32 UTC
*Well this issue has been reported 3 years ago and it appears to be possible using 'download as' but it's not an available option in ONLYOFFICE Desktop Editors version 6.4.2.6 :/*

Hey,

I think it would be a good idea to implement the feature 'change the csv separator' while saving/exporting a csv file.
It could be done using the same pop-in as when you open the csv file.
I know this feature is kind of already here using the server/nextcloud version but I would like to see it in the Desktop edition.

This lack of feature is the only thing keeping me back to switch completly to OnlyOffice for excel use :/

Thanks for taking the time to read my ticket,
Have a great day

**Comment by ShockwaveNN** [comment] 2021-11-08 08:05
I think you've already found out but this is duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/83

**Closed by ShockwaveNN** 2021-11-08 08:05 UTC
