### ISSUE TITLE
ODS: cells aren't displayed with the selected format after reopening file, if "use 1000 separator" was enabled

### ISSUE THREAD

**Issue by Micke3rd** [ONLYOFFICE/DesktopEditors#821] opened 2022-01-21 08:22 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.0.0.127

### Expected Behavior

after reopening file, cells displayed with the format they had on save.

Dont know if this worked in older versions.

### Actual Behavior

save document with a specific cell format and show this format after reopening, works, **except**:
format "number"  with "use 1000 separator" was enabled.
Its not only that the separator is not visible anymore after reopening, the whole format is reseted to default.

### Reproduction Steps

open spreadsheet
change "regional settings" to Deutsch/German
rightclick cell / number format / more formats / enable checkbox "use 1000 separator
save + close document
open document
check if format is visible

### Additional information

german layout DE
I assume the issue is based on the old conflict between english & german number format at **_comma_**  and  **_point_**

**Comment by LuckySpecialist** [comment] 2022-01-21 13:36
Hi @Micke3rd!
Sorry, I can't reproduce your problem. After reopening the saved document, the format remains the same as it was made (according to your scenario).
Maybe there are some more details or a video with a demonstration of the problem?

**Comment by Micke3rd** [comment] 2022-01-22 10:19
https://user-images.githubusercontent.com/16020794/150634553-9a9122f6-0cf6-4bc5-bf45-6c5a5c4275e2.mp4

Hi @LuckySpecialist, certainly, here the clip. You see there:
- set decimals to null
- set "use 1000 separator"  enabled

after reopening:
- decimals are back to default (2)
- "use 1000 separator"  is disabled

**Comment by LuckySpecialist** [comment] 2022-01-22 11:50
Thanks for the video, there are already many more details with it:

1. You use the ODS format, while our main one is XLSX (OOXML)
2. You use formulas in the document
3. In addition to using the thousandth separator option, you change other parameters (the number of decimal places).

I will check your more accurate scenario as soon as possible.
But, if the problem persists, I'm not sure that the fix will be quick, since the ODF format is not the main one for us.
Thank you for the feedback.

**Comment by Micke3rd** [comment] 2022-01-22 12:26
thank you for the quick reply. I checked it just now - you are right, this behavior does not exist with xlsx.
**I'll take this as solution.** I thought your main format is ODS, as not microsoft solution.

_3. In addition to using the thousandth separator option, you change other parameters (the number of decimal places)._
The effect from title happens also without changing number if decimals. But without a 2nd format change (which is stored if alone) it wasnt clear for me, if the spreadsheet just doesnt save format changes or if their is a exception on save or load.

**Comment by LuckySpecialist** [comment] 2022-01-24 08:26
I confirm the problem (Bug 55042 in our private tracker).
I hope the problem will be fixed quickly.
Thanks again.

**Comment by ShockwaveNN** [comment] 2022-01-24 08:33
I'll leave this issue opened until we resolved it

**Comment by LuckySpecialist** [comment] 2024-07-12 13:09
This problem is in the Document Server, fixed by [this commit](https://github.com/ONLYOFFICE/core/commit/efb9095dc5115a6276ced6aa6e7666e2e5f0da22) and will be included in version 8.1.1.

**Comment by Rita-Bubnova** [comment] 2024-07-18 13:18
DesktopEditors v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-07-18 13:18 UTC
Labels: confirmed-bug, fixed-hotfix
