### ISSUE TITLE
Pages are printed with delay and one-by-one

### ISSUE THREAD

**Issue by AKmatiAK** [ONLYOFFICE/DesktopEditors#923] opened 2022-05-18 09:26 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.1.0.215

### Expected Behavior

All pages printed at once

### Actual Behavior

Pages are printed one-by-one. Printer wait long time to print one page.

### Reproduction Steps

Print any document in onlyoffice

### Additional information

This might be related to #481

**Comment by ShockwaveNN** [comment] 2022-05-18 10:05
Hi, indeed it can be duplicate of #481

You can try to print your file to PDF, check it size and if it also big - I'm almost sure it's same problem

**Comment by ShockwaveNN** [comment] 2022-07-29 17:23
This issue was closed due to no response.

**Closed by ShockwaveNN** 2022-07-29 17:23 UTC
