### ISSUE TITLE
Search and replace for special characters works fine in the Document Editor but fail in Spreadsheet Editor

### ISSUE THREAD

**Issue by jpberdejo** [ONLYOFFICE/DesktopEditors#1520] opened 2024-03-05 15:54 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.0.1

### Expected Behavior

The Spreadsheet Editor search for special characters works the same as in Document Editor.

### Actual Behavior

The Spreadsheet Editor doesn’t search for special characters, but this function works fine in Document Editor.

### Reproduction Steps

1. Open an xlsx file with line breaks or tabs inside some cells.
2. Open search and replace (ctrl+H).
3. Search for ^l or ^t.

**Comment by rsnegirev** [comment] 2024-03-20 12:05
Hi @jpberdejo 

Searching for special characters is also not possible in other spreadsheet editors such as Excel, LibreOffice or Google Sheets.

**Comment by rsnegirev** [comment] 2024-08-13 11:06
We are closing this issue as the described behavior is not a bug.

**Closed** 2024-08-13 12:01 UTC
