### ISSUE TITLE
Spell checking language switches (back) to unwanted language

### ISSUE THREAD

**Issue by Inrumpo** [ONLYOFFICE/DesktopEditors#802] opened 2022-01-03 19:45 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

6.4.2.6

### Expected Behavior

After having chosen a language for spell checking, that language should stay the same until changed again by the user.

### Actual Behavior

Having set the spell checker to German (Switzerland), it will automatically switch back to German (Germany).

### Reproduction Steps

The issue is shown in this GIF:
![OnlyOffice changing languages issue](https://user-images.githubusercontent.com/11300164/147973024-2e3a22b5-a24b-4570-964e-42d946ee9e37.gif)

### Additional information

This file was originally created in Word 365.

I would like to be able to force OnlyOffice to stay at the selected language.

**Comment by Rita-Bubnova** [comment] 2022-01-05 10:32
Hello, @Inrumpo.
Could you attach a file with a problem?

**Comment by Inrumpo** [comment] 2022-01-07 16:32
> Could you attach a file with a problem?

Sure. Here is a file showing such issues:
[Vorlage Brief.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/7830056/Vorlage.Brief.docx)

Thanks for your help!

**Comment by Rita-Bubnova** [comment] 2022-01-10 12:28
Thank you for your file.
I think, this is duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/273.

**Closed** 2022-01-10 12:34 UTC

**Comment by JT8D-17** [comment] 2025-02-11 21:26
This issue is still present in 8.3.0.97 (on Linux at least). Spell checking language still resets to German despite the user interface, document language and system locale being English.
