### ISSUE TITLE
Make text as default field format on Ctrl + Shift + V

### ISSUE THREAD

**Issue by Grzanka99** [ONLYOFFICE/DesktopEditors#525] opened 2020-12-09 08:31 UTC
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When you paste some data in Spreadsheet (with Ctrl + Shift + V) number will change to other format. The, when you try to save them as a "text" (f.e ID, PESEL, Bank account number) it will stay "scientist format" until you re-paste value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try copy one field or couple of fields with big numbers and paste them in new spreadsheet, it will change format and visual aspect of data.

**What is the expected behavior?**
I understand that the Ctrl + Shift + V destroy formating, but maybe just set default field format as text until user change it?

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
 - version: **6.0.2.10**
 - OS: **MS Windows 10**, **Linux Manjaro**

**Comment by Rita-Bubnova** [comment] 2020-12-10 11:40
Hello, @Grzanka99. 
Can you attach video of this problem?

**Comment by Grzanka99** [comment] 2020-12-10 12:59
Hello, @Rita-Bubnova
Yes, there is [video](https://youtu.be/5JY43W9dBEs)
How you can see, I never typed 0 but data were overwritten

**Comment by BananaAcid** [comment] 2021-07-27 09:19
on mac COMMAND+SHIFT+V and on Windows CTRL+SHIFT+V -> Paste without format (cleaned).

got the same problem, usually pasting formatted text from websites and webmailer, and want it cleaned from formatting on pasting.

Usually works with windows default software and usually on default mac software. 


... but not in OnlyOFFICE Desktop.

**Comment by Rita-Bubnova** [comment] 2021-07-27 20:35
> on mac COMMAND+SHIFT+V and on Windows CTRL+SHIFT+V -> Paste without format (cleaned).
> 
> got the same problem, usually pasting formatted text from websites and webmailer and other textareas form different programs, and want it cleaned from formatting on pasting.
> 
> Usually works with windows default software and usually on default mac software.
> 
> ... but not in OnlyOFFICE Desktop.

I think, this is duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1002.

**Comment by Rita-Bubnova** [comment] 2021-07-27 20:46
> Hello, @Rita-Bubnova
> Yes, there is [video](https://youtu.be/5JY43W9dBEs)
> How you can see, I never typed 0 but data were overwritten

@Grzanka99, sorry for late response.
It is same behavior as MS Excel.

**Comment by bambirombi** [comment] 2022-04-05 12:17
I have the same problem in all linux distributions. There is no way to pasting without format in onlyoffice. I do not understand why this have not been solved since 2020. It is a must have.

**Comment by BananaAcid** [comment] 2022-04-08 11:22
New update and still missing.

**Comment by ShockwaveNN** [comment] 2022-04-08 12:06
I think we forgot to close this issue as duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1002

And yes, this feature are still not implemented, sorry

**Closed by ShockwaveNN** 2022-04-08 12:06 UTC
