### ISSUE TITLE
Word contractions aren't recognized as words

### ISSUE THREAD

**Issue by squidgyberries** [ONLYOFFICE/DesktopEditors#767] opened 2021-11-27 02:32 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

6.4.2.6

### Expected Behavior

Word contractions like "didn't" should be recognized as one word and then recognized as an actual word.

### Actual Behavior

Word contractions like "didn't" get partially underlined in red and won't be recognized as a word. For example, in "didn't", the "didn" part would get underlined.

### Reproduction Steps

1. Type a word contraction like "didn't"
2. Observe the red line

**Comment by ShockwaveNN** [comment] 2021-11-27 13:46
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/576

**Closed by ShockwaveNN** 2021-11-27 13:46 UTC
