### ISSUE TITLE
Date format YYYY-MM-DD is not recognized

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#542] opened 2021-01-04 12:43 UTC
**Do you want to request a *feature* or report a *bug*?**
Depends, could be either a bug or a feature.

**What is the current behavior?**
Date format YYYY-MM-DD is treated as an ordinary text which causes undesired behavior with auto-filling.
![OO4](https://user-images.githubusercontent.com/64358003/103535860-8bad7000-4ea2-11eb-8d4a-23522fefaa35.png)

Unfortunately the context menu "Number Format", "More formats" doesn't contain the required date format either:
![OO5](https://user-images.githubusercontent.com/64358003/103536298-4dfd1700-4ea3-11eb-8601-35254cc9714e.png)

**What is the expected behavior?**
The expected behavior is to recognize date format YYYY-MM-DD.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Windows 10 20H2
Only Office 6.1.0.90

**Comment by PatLabGit** [comment] 2021-01-11 07:39
dashes (-) are more readable than slashes (/) for some people (me included) and it's used in many countries.
Dates and times seems to be a serious problem with OnlyOffice
LO recognizes dates with dashes (-)...
It would be nice if OnlyOffice would do it as well as time in a 24h format with different format like column/slash/dash as well.

**Comment by Rita-Bubnova** [comment] 2021-01-14 07:20
Hello.
@HectorB-2020, perhaps this problem is a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1100 ?

**Comment by HectorB-2020** [comment] 2021-01-14 12:05
Correct.

**Comment by ShockwaveNN** [comment] 2021-01-14 12:15
In that case I'll close your issue
@HectorB-2020 I think it'll be good if you copy your detailed report as comment to original issue
Thank you for your report

**Closed by ShockwaveNN** 2021-01-14 12:15 UTC

**Comment by HectorB-2020** [comment] 2021-01-14 12:24
Sure thing!
