### ISSUE TITLE
Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg)

### ISSUE THREAD

**Issue by zhuohoudeputao** [ONLYOFFICE/DesktopEditors#895] opened 2022-04-21 13:48 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.2.5

### Expected Behavior

No warning when I run `apt update`.

### Actual Behavior

Warning like the title.

**Comment by ShockwaveNN** [comment] 2022-04-21 14:29
Hi 

> No warning when I run apt update.

Which OS are you using? And how did you installed key

I'm on Ubuntu 20.04 and got not warning on `apt update`

**Comment by zhuohoudeputao** [comment] 2022-04-21 16:23
> Hi
> 
> > No warning when I run apt update.
> 
> Which OS are you using? And how did you installed key
> 
> I'm on Ubuntu 20.04 and got not warning on `apt update`

I'm on Ubuntu 22.04.

**Comment by XDmitryK** [comment] 2022-04-22 08:05
@zhuohoudeputao 
I can confirm this is bug issue 56785 in our private issue tracker.
Thank you for report

**Comment by alexandervnuchkov** [comment] 2022-04-26 13:42
@zhuohoudeputao
A quick workaround for the issue can be the following:

- Run the command: `sudo apt-key export CB2DE8E5 | sudo gpg --dearmour -o /usr/share/keyrings/onlyoffice.gpg`

- Then add the following line to the _/etc/apt/sources.list.d/onlyoffice.list_: `deb [arch=amd64 signed-by=/usr/share/keyrings/onlyoffice.gpg] https://download.onlyoffice.com/repo/debian squeeze main` instead of the default one, or run the command: `echo deb [arch=amd64 signed-by=/usr/share/keyrings/onlyoffice.gpg] https://download.onlyoffice.com/repo/debian squeeze main | sudo tee /etc/apt/sources.list.d/onlyoffice.list`

This will remove the warning and allow you to update ONLYOFFICE Desktop Editors and other packages as usual until a fix is implemented.

**Comment by ShockwaveNN** [comment] 2022-04-26 15:30
@alexandervnuchkov Thank you for this workaround, I'll show it to our developers

P.S. Nice to see you, Alexander )

**Comment by ShockwaveNN** [comment] 2022-05-11 11:06
@Rongronggg9 We fixed those errors in this version of instruction on our staging helpcenter site
https://test-helpcenter.onlyoffice.com/installation/desktop-install-ubuntu.aspx

You can check it and we checked it on latest ubuntus and everything works fine with it
Soon it will be in production

**Comment by ShockwaveNN** [comment] 2022-05-11 14:07
@Rongronggg9 Are you sure that it's not created by default? I think I've checked in on clean ubuntu 22.04 installation and this directory is present

**Comment by Rongronggg9** [comment] 2022-05-11 14:22
The problem is not if it is created by default on Ubuntu 22.04, but the guide is for "Debian, Ubuntu and derivatives". Also, the creation of `$HOME/.gunpg` may rely on the DE user selected. I've checked that a clean Debian testing installation with KDE Plasma comes without `$HOME/.gunpg`.

In most cases, the absence of `$HOME/.gunpg` is not a big deal since `gpg --no-default-keyring --keyring gnupg-ring:/tmp/onlyoffice.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5` will get it created automatically. But in some cases it is. An example is when the current user is `root`. Some users get used to switching to the `root` user before installing packages.

```sh
> sudo su -
> gpg --no-default-keyring --keyring gnupg-ring:/tmp/onlyoffice.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
gpg: keyring '/tmp/onlyoffice.gpg' created
gpg: failed to create temporary file '/root/.gnupg/.#***.***.***': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
```

**Comment by Rongronggg9** [comment] 2022-05-11 14:28
Also, another problem is that by the documented way, the owner of the keyring will be the current user. That's not so good.

```
drwxr-xr-x 2 root     root     4096 May 11 21:49 .
drwxr-xr-x 9 root     root     4096 Apr 15 23:13 ..
-rw-r--r-- 1 root     root     8700 Feb 26  2021 debian-archive-bullseye-automatic.gpg
-rw-r--r-- 1 root     root     8709 Feb 26  2021 debian-archive-bullseye-security-automatic.gpg
-rw-r--r-- 1 root     root     2453 Feb 26  2021 debian-archive-bullseye-stable.gpg
-rw-r--r-- 1 root     root     8132 Feb 26  2021 debian-archive-buster-automatic.gpg
-rw-r--r-- 1 root     root     8141 Feb 26  2021 debian-archive-buster-security-automatic.gpg
-rw-r--r-- 1 root     root     2332 Feb 26  2021 debian-archive-buster-stable.gpg
-rw-r--r-- 1 root     root     7443 Feb 26  2021 debian-archive-stretch-automatic.gpg
-rw-r--r-- 1 root     root     7452 Feb 26  2021 debian-archive-stretch-security-automatic.gpg
-rw-r--r-- 1 root     root     2263 Feb 26  2021 debian-archive-stretch-stable.gpg
-rw-r--r-- 1 rongrong rongrong 2279 May 11 21:49 onlyoffice.gpg
```

It would be better if you change the command to this:

```sh
gpg --no-default-keyring --keyring gnupg-ring:/tmp/onlyoffice.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
chmod 644 /tmp/onlyoffice.gpg
sudo chown root:root /tmp/onlyoffice.gpg
sudo mv /tmp/onlyoffice.gpg /etc/apt/trusted.gpg.d/
```

**Comment by ShockwaveNN** [comment] 2022-05-11 14:40
Thanks I'll show this to our documentation team

**Comment by ShockwaveNN** [comment] 2022-05-11 14:48
Am I right that correct way will be
```
mkdir -p ~/.gnupg
chmod 700 ~/.gnupg
gpg --no-default-keyring --keyring gnupg-ring:/tmp/onlyoffice.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
chmod 644 /tmp/onlyoffice.gpg
sudo chown root:root /tmp/onlyoffice.gpg
sudo mv /tmp/onlyoffice.gpg /etc/apt/trusted.gpg.d/
```

Or first two lines will be no needed?

**Comment by Rongronggg9** [comment] 2022-05-11 14:54
Great. That's the right way. Thanks for your work.

It seems that in most cases in which the current user is not `root`, the first two lines are not needed, but I am not so sure if there are other cases. That's really OK to keep the first two lines in any case since they are always harmless.

**Comment by ShockwaveNN** [comment] 2022-05-12 10:20
New instruction is released [to production site](https://helpcenter.onlyoffice.com/installation/desktop-install-ubuntu.aspx)

This issue should be resolved

**Closed by ShockwaveNN** 2022-05-12 10:20 UTC
Labels: bug
