### ISSUE TITLE
[Bug] Input fields - v8.1.0 - PDF Editing - 'An error occurred during the work with the document'

### ISSUE THREAD

**Issue by jb2barrels** [ONLYOFFICE/DesktopEditors#1620] opened 2024-06-27 15:42 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (RPM package)

### Version information

8.1.0

### Expected Behavior

Be able to type in the PDF input field

### Actual Behavior

Upon starting to type in an input field, receive error:
"An error occurred during the work with the document. Use the 'Save as...' option to save the file backup copy to a drive"

### Reproduction Steps

1. Tested on both using OnlyOffice on Windows 11 (installed with exe) or Fedora 40 Linux (installed with flatpak)
2. Search Google for a sample pdf: "sample pdf with forms"
3. Download any sample PDF that has input fields with forms
4. Open the PDF file using OnlyOffice PDF
5. Try typing inside a fillable input field such as "Name" or "Address"
6. You will receive the error

### Additional information

Example screenshot of error:

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/129100561/d6425fdc-f522-4da5-bf0c-de1c5c39279c)

**Comment by Rita-Bubnova** [comment] 2024-06-28 09:59
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2768.

**Closed by Rita-Bubnova** 2024-06-28 09:59 UTC
