### ISSUE TITLE
font broke the editor

### ISSUE THREAD

**Issue by bill88t** [ONLYOFFICE/DesktopEditors#596] opened 2021-04-07 20:52 UTC
A little while ago I had 6.2.0 installed as a debian package (.deb). It was working fine. But then I installed the font inter. And then whenever I open a document or create a new one the desktopeditors completely hang up requiring a killall -s KILL to go away.
I switched to flatpak version 6.1.0 which turned out to work fine. (I thought it was 6.2.0 at the time) Now after the flatpak updated though the app hangs again. (It's now 6.2.0) I have completely removed the font off of the system and forcibly regenerated the font cache. Yet the app is still broken. I cannot provide you with any logs as your app does not spit out anything, even if run from terminal. While it's frozen it uses 1 core 100%. I left it there for 5 minutes and nothing. I'm on kubuntu 20.04 with all of the latest updates. I can provide the font file if required. I downloaded it from google fonts if I recall correctly.

**Comment by ShockwaveNN** [comment] 2021-04-08 07:25
@bill88t Hi, yes, please provide your font file

**Comment by bill88t** [comment] 2021-04-08 07:27
[Inter-VariableFont_slnt,wght.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/6276818/Inter-VariableFont_slnt.wght.zip)
compressed it as a .zip, since github doesn't allow .ttf.

**Comment by ShockwaveNN** [comment] 2021-04-08 07:56
@matveevms Please take a look

**Comment by matveevms** [comment] 2021-04-09 14:59
Hi. @bill88t 
How was the font installed? Using a font manager or copying to the global fonts folder / usr / share / fonts or to the user-specific ~ / .fonts folder created?

**Comment by bill88t** [comment] 2021-04-09 15:53
It was installed using the default kubuntu font app. The app gives me the option to install to the system or to the user. I selected system. Using `fc-list | grep Inter` I can see that it is installed to `/usr/local/share/fonts/i/`

Command line output:
```
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=ExtraLight
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Bold Italic
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=SemiBold
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Medium
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Light
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Medium Italic
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Light Italic
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=ExtraLight Italic
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Bold
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=SemiBold Italic
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=ExtraBold Italic
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Regular
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=ExtraBold
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Italic
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Thin
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Thin Italic
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Black
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter
/usr/local/share/fonts/i/Inter_VariableFont.ttf: Inter:style=Black Italic
```

I have renamed the font to see if the name of it was perhaps a problem.

**Comment by bill88t** [comment] 2021-04-09 17:33
I should make this clear. Removing the font from the filesystem and regenerating the font cache using `fc-cache -f -v` did not help.
I also tried deleting all the onlyoffice config files I could find. Also I can confirm this issue is applicable to the snap, flatpak and deb versions of the Desktop Editors.

**Comment by matveevms** [comment] 2021-05-05 15:25
I can't reproduce your problem after installing the font. Could you please provide your pc specifications?

**Comment by bill88t** [comment] 2021-05-05 19:31
I have reproduced it on 2 machines running kubuntu 20.04.2 LTS, they are using kernel 5.4.0-72-generic and affects all versions of the onlyoffice desktop editors (by versions I mean snap, deb, flatpak).
It's not a general font management issue because I have more 3rd party fonts installed.
I will reproduce it in a vm to generate the exact steps and let you know.

More spec information:

machine 1:
CPU: i5-10400F
GPU: Geforce GT1030
RAM: 32gb (31.3 usable)

machine 2:
CPU: Ryzen 3 3250U
GPU: Radeon Graphics
RAM: 8gb (5.8 usable)

both:
KDE Plasma version: 5.18.5
KDE Frameworks version: 5.68.0
Qt version: 5.12.8

**Comment by ShockwaveNN** [comment] 2021-07-16 11:28
I'll close this issue since issue is hard to reproduce, but if you able to - please comment here or create a new issue with reproducible scenario or a video at least

**Closed by ShockwaveNN** 2021-07-16 11:28 UTC
Labels: waiting feedback
