### ISSUE TITLE
Starting Onlyoffice always Creating Standard Templates

### ISSUE THREAD

**Issue by Axel-G** [ONLYOFFICE/DesktopEditors#416] opened 2020-06-26 09:45 UTC
I have no template directory in my home directory.

When starting onlyoffice, the three standard templates for writer, calc and presentation are always created in the home directory.

Thats not nice ;)

**Comment by ShockwaveNN** [comment] 2020-06-26 10:26
Seems like duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/355

**Comment by Axel-G** [comment] 2020-06-26 16:43
duplicate of #355

**Closed** 2020-06-26 16:42 UTC
