### ISSUE TITLE
Insert texts but they appear elsewhere rather than where the cursor is.

### ISSUE THREAD

**Issue by Lamb666** [ONLYOFFICE/DesktopEditors#1102] opened 2022-11-08 03:38 UTC
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

In a .docx document, insert Chinese characters and they appear at the cursor's location.

The problem did not exist in previous version.

### Actual Behavior

Insert Chinese characters and they appear at random places in the line, rather than the desired place.
Latin letters don't have this issue.

### Reproduction Steps

1. Place the cursor between characters.
2. Type Chinese characters.
3. The new characters appear elsewhere.

### Additional information

I use the default IBus input source for Chinese.

**Comment by ShockwaveNN** [comment] 2022-11-08 07:27
Hi, could you record a video of this problem?

**Comment by Lamb666** [comment] 2023-01-13 06:24
> Hi, could you record a video of this problem?

This problem appeared after a certain update, before that time it was all good and love the software.
Please look into the problem, thanks!

https://user-images.githubusercontent.com/32459505/212251587-4293f1a5-fa2b-4d79-ba0b-590327588edb.mp4

**Comment by weimzh** [comment] 2023-02-17 07:54
I've got the same issue:
https://www.youtube.com/watch?v=x1vreiZpYnQ

the latest 7.3.0 version still have the problem.  currently I'm using version 7.1.1 instead, which seems to be ok

**Comment by weimzh** [comment] 2023-02-17 13:27
I've got the same issue:
https://www.youtube.com/watch?v=x1vreiZpYnQ

the latest 7.3.0 version still have the problem. currently I'm using version 7.1.1 instead, which seems to be ok

@Lamb666 maybe you could temporarily downgrade to 7.1.1 version until this gets fixed, which does not have this issue

**Comment by Lamb666** [comment] 2023-02-17 15:56
@ShockwaveNN Please review this issue, it still remains unsolved in the latest 7.3.0 version.

**Comment by weimzh** [comment] 2023-04-23 06:44
This bug still exist in the latest 7.3.3 version.

**Comment by weimzh** [comment] 2023-06-20 06:53
This bug still exist in the latest 7.4.0 version.

**Comment by weimzh** [comment] 2023-06-23 04:02
> Please write how you install the Chinese language. Step by step. I can't reproduce. Thanks.

For Fedora 38 (with GNOME) which I am using:

1. Install WuBi Chinese Input Method:
```dnf install ibus-table-chinese-wubi-jidian```
2. Logout and login again
3. Click right top corner, and click the settings icon
4. Click 'Keyboard' from the left side
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/1220443/90d79e95-4d49-416f-b6fe-4ec6e5055e6f)
5. Click the plus sign under "Input Sources" from the right side
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/1220443/24a4af71-d3b9-47ce-b392-560208362e59)
6.  Select "Chinese (China)", and the WuBi Input Method
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/1220443/be46c60f-7923-42c1-b12c-f7eae6b4929e)
7. Now you should be able to switch to the WuBi Input method by clicking the 'en' button at the right top corner
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/1220443/a8778e58-8eac-4e5c-847c-2ae2ca75a266)
8. Launch ONLYOFFICE, create a text document.
9. Switch to WuBi Input Method, and type the following characters:
```g fgg dggg lh ggh uy agn wty fgh ```
the texts appeared should be:
```一二三四五六七八十```
10. Move the cursor between 八 and 十: 
```一二三四五六七八|十```
11. Type: ```vtn ```, the character 九 now appears after the character 十.
ie.
```一二三四五六七八十九```
The correct result should be:
```一二三四五六七八九十```

**Comment by Lamb666** [comment] 2023-08-14 03:11
It persists in the latest version 7.4.1. The last usable version is 7.1.1 (in which I have no choice but to stay).
Please fix this severe bug, which made it impossible to work with Chinese 🙏.

**Comment by maruacat** [comment] 2023-08-23 14:39
Hello @Lamb666 
Sorry for the long wait. 
I can confirm - this is bug. I created ticket #63793 with your issue.
Thank you for the report.

**Comment by HectorB-2020** [comment] 2023-11-11 14:54
Which version is it going tp be?

**Comment by Rita-Bubnova** [comment] 2023-11-14 12:32
DesktopEditors v7.5.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-11-14 12:32 UTC
Labels: confirmed-bug, fixed-hotfix

**Comment by matveevms** [comment] 2024-05-20 13:46
Hello, @Bryan2333 
Please tell me if the problem is repeated in other editors on your system?

**Comment by Bryan2333** [comment] 2024-05-20 14:01
> Hello, @Bryan2333 Please tell me if the problem is repeated in other editors on your system?

No, it only happens to OnlyOffice.
