### ISSUE TITLE
Additional scaling of the interface to 1.5 or 1.25 *feature*

### ISSUE THREAD

**Issue by Finist992** [ONLYOFFICE/DesktopEditors#399] opened 2020-05-28 10:22 UTC
Is it planned to introduce additional scaling of the interface to 1.5 or 1.25?
At least with --force-scale=1.5.
It needful because of original scalling menu and controls of OnlyOffice are displayed very small at FHD 14-15 inches. At the moment --force-scale can only zoom in 2 times.

**Comment by ShockwaveNN** [comment] 2020-05-28 10:27
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/53

**Closed by ShockwaveNN** 2020-05-28 10:27 UTC
