### ISSUE TITLE
Added fonts are not recognized when installing via Flatpaks

### ISSUE THREAD

**Issue by Sov3rain** [ONLYOFFICE/DesktopEditors#557] opened 2021-01-24 11:58 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When installing OnlyOffice editors (6.1) via Flatpak (FlatHub), added fonts like MS ones are not recognized and usable in said editors.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Install OnlyOffice Editors via Flathub
- Launch the document editor with any file
- Try to use a non-default font (like MS ones)
- Added font don't appear in the list

**What is the expected behavior?**

Added fonts should appear in the list.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Pop!_OS 20.04
OnlyOffice 6.1.0 FLATPAK

Snaps and .deb from the official website are fine. It seems to affect only flatpak version.

**Comment by ShockwaveNN** [comment] 2021-01-25 07:11
Hi, this is duplicate of https://github.com/flathub/org.onlyoffice.desktopeditors/issues/2

**Closed by ShockwaveNN** 2021-01-25 07:11 UTC
