### ISSUE TITLE
Blank list of files with Nextcloud

### ISSUE THREAD

**Issue by SavageAUS** [ONLYOFFICE/DesktopEditors#1178] opened 2023-01-11 21:28 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

Expect to see a list of the files on my nextcloud instance.

### Actual Behavior

Connect onlyoffice to nextcloud, load nextcloud to blank screen.
![onlyofficeDEC](https://user-images.githubusercontent.com/17326832/211921314-b78215b5-e866-4846-a83a-a25d6822e0e4.png)

### Reproduction Steps

Install Arch Linux.
Install OnlyOffice from the AUR or the flatpak
Connect to nextcloud

### Additional information

I have tried both the AUR version and the flatpak and both instances result in the screen attached where I cannot see or choose a document.
![onlyofficeDEC](https://user-images.githubusercontent.com/17326832/211921550-2ed7ab46-8b8a-4a5f-8bf7-4ec26c3587d9.png)

**Comment by paytime** [comment] 2023-01-18 22:39
Same issue with Nextcloud 25.

I am running Ubuntu 22.10 and using the SNAP version of OnlyOffice.

**Comment by nahoj** [comment] 2023-01-22 18:44
I have the same problem. Also Nextcloud 25 on YunoHost (Debian). OnlyOffice server 7.1.0. Works fine in Nextcloud's web interface.

DesktopEditors 7.2.2 on Ubuntu; same with v6.4.2.

**Comment by nahoj** [comment] 2023-01-22 18:47
@SavageAUS May I suggest renaming the issue to better reflect the problem, e.g. "Blank list of files with Nextcloud"?

**Comment by EmilioRui** [comment] 2023-01-24 09:03
Same problem here

**Comment by Silberlog** [comment] 2023-02-02 22:42
Same problem with ONLYOFFICE Desktop Editors version 7.3.0.184 on Debian 11 / Nexctloud 25.0.3 instance on Debian 11.
FYI, Windows Desktop Editors 7.3.0.184 connected to the same instance doesn't have the problem, only Linux client is impacted.

**Comment by ikueper73** [comment] 2023-02-24 10:30
Same issue 

Desktop Editor on Fedora 7.3.0.184 (flatpak)

Nexctloud 25.0.3 Snap

**Comment by cryptbrn** [comment] 2023-02-26 13:48
Same issue
- NextCloud 25.0.3 
- Desktop Editor 7.3.0.184

**Comment by freddy1301** [comment] 2023-02-27 15:41
I have the same issue. I always used this feature.
I assume that nextcloud isnt loading the informations of the files app because it didnt realized that the page got loaded by the user. Or Probably some kind of other performance optimization in nc25.

**Comment by paytime** [comment] 2023-03-05 23:42
This issue is still going on, making the desktop app unusable for me.

This is unique to Linux and does not happen on Windows.

**Comment by lmsecure** [comment] 2023-03-24 07:19
Hello. I research this problem. It's related with Chromium browser version which using in Onlyoffice-DesktopEditors. Windows version work normal because use Google Chrome 87, but Linux use Google Chrome 75. In app devtools  you can see errors with javascript code running. I think that NextCloud start using in latest version  new JS syntax. But Chromium browser cannot run. 
Development of Onlyoffice-DesktopEditor  should rebuild app with new Chromium version

**Comment by SpiderOnTheNet** [comment] 2023-05-21 15:58
I have the same problem. I have Nextcloud (25.0.6) on YunoHost (11.1.20) with ONLYOFFICE Document Server for YunoHost (7.3.3~ynh1). Works fine in Nextcloud's web interface.

**Comment by navkaran0305** [comment] 2023-06-21 22:03
Same problem here

OS - Pop!_OS 22.04 LTS
NextCloud Version - 25.0.3
OnlyOffice Version - 7.3.3.50 (flatpak)

**Comment by LuckySpecialist** [comment] 2023-08-16 10:04
Hello everyone!
On my system, everything is displayed correctly on Ubuntu 22.04.3 LTS.
Tested on Desktop Editors 7.4.1.36 (snap) + Nextcloud 25.0.10.
Is the problem still relevant to you?

**Comment by paytime** [comment] 2023-08-16 10:06
Works for me now too. Same Desktop Editors snap version on Ubuntu 23.04.

**Comment by Mer0me** [comment] 2023-08-16 10:26
Hmm, here the list of files appears again, I can click on .docx files but... it launches Onlyoffice on the browser via Nextcloud. The OO desktop client is not used in this case. Is it the normal behavior ?

**Comment by LuckySpecialist** [comment] 2023-08-16 13:33
@Mer0me in general, this is not quite normal behavior for an application.
Everything opens correctly for me (in my setup).

What type of package are you using, what operating system and versions of Desktop Editors and nextcloud server?
It is also advisable to write a script in which the problem is observed and make a separate issue if it is consistently reproduced.

**Comment by Mer0me** [comment] 2023-08-16 13:52
I've installed the .deb package onlyoffice-desktopeditors_amd64.deb version 7.4.1.36 (deb) on 2 different machines running Xubuntu, and tested them against 2 different Nextcloud Server :
- Nextcloud 27.0.2 with onlyoffice server version 7.2.2.56 and Nextcloud OnlyOffice app v8.2.0
- Nextcloud 27.0.2 with onlyoffice server version 7.4.0.163 and Nextcloud OnlyOffice app v8.2.0

Only one of my client machine have this behavior with the two servers : files are opened in the browser and not in the desktop client. On the other, all is fine, the desktop client is actually opening files correctly.

What can be the difference between the two machines ? I will try to figure out...

**Comment by Mer0me** [comment] 2023-08-16 14:55
Removing the nextcloud connection on Desktop Editor and recreating it with same parameters solved the problem. Thank you !

**Comment by Rita-Bubnova** [comment] 2023-08-16 14:57
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-08-16 14:57 UTC
