### ISSUE TITLE
Autosave feature

### ISSUE THREAD

**Issue by Prapor95** [ONLYOFFICE/DesktopEditors#1686] opened 2024-09-25 08:12 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

We need a full-fledged auto-save function, not a neutered version of it called auto-recovery. Auto-repair works terribly - the first time I needed it, it restored a file from a day ago - as a result, several hours of work were lost

**Comment by LuckySpecialist** [comment] 2024-09-26 16:08
Hi @Prapor95!
This is duplicate of #1674.
Try using our server-based editors, where changes are saved automatically.

**Closed** 2024-09-27 08:38 UTC
Labels: duplicate
