### ISSUE TITLE
Error opening JSON file while checking for updates

### ISSUE THREAD

**Issue by BLinus22** [ONLYOFFICE/DesktopEditors#1311] opened 2023-06-18 16:20 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.4.0.163

### Expected Behavior

When I click on the "Check for updates" button in the "About" tab in the ONLYOFFICE Desktop Editors it should check, if a newer version is available and show the result. (It already worked in previous versions)

### Actual Behavior

When I click on the "Check for updates" button in the "About" tab in the ONLYOFFICE Desktop Editors it shows the error message "Error opening JSON file."

### Reproduction Steps

1. Open the ONLYOFFICE Desktop Editors on your PC
2. Click on the "About" tab
3. Click on the "Check for updates" button

### Additional information

The error also occurs when opening the ONLYOFFICE Desktop Editors with "Check for updates automatically" enabled.
The ONLYOFFICE Desktop Editors is installed on Windows 11. (I selected Windows 10 in the selection for the operating system because Windows 11 is not available.)

Here is a screenshot of the error message:
![grafik](https://github.com/ONLYOFFICE/DesktopEditors/assets/117105618/b34d4158-f04f-424b-9385-03dad3ed7276)

**Comment by LuckySpecialist** [comment] 2023-06-19 11:16
Hi, @BLinus22!
Do you have same special environment in your network (domain, proxy etc)?

**Comment by LuckySpecialist** [comment] 2023-06-19 13:55
Can you show your sytem environment variables window?
To do this:
1. Press `Win + R`
2. Paste this command `rundll32.exe sysdm.cpl,EditEnvironmentVariables` in Open field
3. Press `Enter`

**Comment by BLinus22** [comment] 2023-06-19 17:19
Hi @LuckySpecialist,

> Do you have some special environment in your network (domain, proxy etc)?

No, I don't think so. Proxy is set to "automatically detect settings" and the pc is not in a domain (it is a private pc with a local user account).

> Can you show your system environment variables window?

Yes, here is a screenshot:
![grafik](https://github.com/ONLYOFFICE/DesktopEditors/assets/117105618/71716e34-6369-427f-b247-95afdd996392)

By the way, the language of my pc is german, I don't know if that makes a difference.

**Comment by FirefoxNL** [comment] 2023-06-20 06:59
I am experiencing the same issue on a Windows Server 2022 terminal server.
This server ís joined to a domain with a firewall but outgoing traffic is allowed.
I just updated OnlyOffice through the automatic updates, so checking for updates did work prior to updating to 7.4.0.163.
My language is in Dutch so it's not bound to a single language.

System variables and configuration below: 

![systeemvariabelen](https://github.com/ONLYOFFICE/DesktopEditors/assets/74513001/81717bdc-5842-4671-ab1b-d75a8210fae7)

![systeemvariabelen2](https://github.com/ONLYOFFICE/DesktopEditors/assets/74513001/f1c48b11-09c2-4cc1-a63f-586812035c95)

**Comment by LuckySpecialist** [comment] 2023-06-20 07:40
Hi, thanks for the info.
> Yes, here is a screenshot: ![grafik](https://user-images.githubusercontent.com/117105618/246892826-71716e34-6369-427f-b247-95afdd996392.png)

And what about user variables who has an error (in same window above)?

**Comment by BLinus22** [comment] 2023-06-20 11:39
Hi, sorry I forgot about these:

![grafik](https://github.com/ONLYOFFICE/DesktopEditors/assets/117105618/f76dac4d-c440-4ebc-b3d7-8e2913d1e951)

The blurred area is just my username (without spaces).

**Comment by LuckySpecialist** [comment] 2023-06-20 16:35
It looks quite normal, nothing criminal.

Is it possible to test such a scenario?
1. Open the temporary directory: `Win+R` > `%temp% `> `Enter`
2. Launch Desktop Editors
3. Go to the _**About**_ page
4. Click _**Check for updates**_
5. When an error message appears, **without closing this window**, look for a file `onlyoffice_<ID>.json` in the `temp` directory
6. Additionally, you can check for the presence of such a file `onlyoffice_<ID>.json` in the root of the system disk (C:\ by default)

**Comment by BLinus22** [comment] 2023-06-20 22:27
I have done the steps and found a matching file in the `temp` directory, I included the entire content of the file in the message. The last changed time of the file was the current time and date.
In the root of the system I did not find a matching file.

Here is the content of the file in the `temp` directory:
```
{
  "version": "7.4.0.163",
  "date": "Jun 11 06:36 UTC 2023",
  "releaseNotes": {
    "en-EN": "https://download.onlyoffice.com/install/desktop/editors/windows/onlyoffice/changes/changes.html",
    "ru-RU": "https://download.onlyoffice.com/install/desktop/editors/windows/onlyoffice/changes/changes_ru.html"
  },
  "package": {
    "win_64": {
      "url": "https://download.onlyoffice.com/install/desktop/editors/windows/onlyoffice/updates/editors_update_x64.exe",
      "installArguments": "/silent /update",
      "archive": {
        "url": "https://download.onlyoffice.com/install/desktop/editors/windows/distrib/onlyoffice/DesktopEditors_x64.zip",
        "md5": "b388b592e288ab1544bd218548e317c0"
      },
      "iss": {
        "url": "https://download.onlyoffice.com/install/desktop/editors/windows/distrib/onlyoffice/DesktopEditors_x64.exe",
        "md5": "e2e7662d87f3f2fc0eb0208088e79f74",
        "arguments": "/silent /update",
        "maxVersion": "7.3.3"
      },
      "msi": {
        "url": "https://download.onlyoffice.com/install/desktop/editors/windows/distrib/onlyoffice/DesktopEditors_x64.msi",
        "md5": "2f8c7f7afacbe95a2d5898b3f7ccbd4b",
        "arguments": "/qn /norestart",
        "maxVersion": "7.3.3"
      }
    },
    "win_32": {
      "url": "https://download.onlyoffice.com/install/desktop/editors/windows/onlyoffice/updates/editors_update_x86.exe",
      "installArguments": "/silent /update",
      "archive": {
        "url": "https://download.onlyoffice.com/install/desktop/editors/windows/distrib/onlyoffice/DesktopEditors_x86.zip",
        "md5": "92ef2ee0bc0c20b2ad39650afbf78abb"
      },
      "iss": {
        "url": "https://download.onlyoffice.com/install/desktop/editors/windows/distrib/onlyoffice/DesktopEditors_x86.exe",
        "md5": "5bfa22e846abc20b7d65bfc164cfd548",
        "arguments": "/silent /update",
        "maxVersion": "7.3.3"
      },
      "msi": {
        "url": "https://download.onlyoffice.com/install/desktop/editors/windows/distrib/onlyoffice/DesktopEditors_x86.msi",
        "md5": "285a89af690d40cc4537e12194782cf2",
        "arguments": "/qn /norestart",
        "maxVersion": "7.3.3"
      }
    }
  }
}
```

**Comment by LuckySpecialist** [comment] 2023-06-21 11:08
> I have done the steps and found a matching file in the `temp` directory, I included the entire content of the file in the message. The last changed time of the file was the current time and date. In the root of the system I did not find a matching file.

It's good
Now can you check the rights to the `temp` folder for the user who has the problem?

To do this, you need: 

1. Open the properties window for the `temp` folder
2. Go to the **_Security_** tab
3. Select the current user from the list
4. A list of permissions will be displayed for it in the window below
5. Additionally, you can also show an extended list of permissions by clicking on the **_Advanced_** button

**Comment by BLinus22** [comment] 2023-06-21 22:19
In the **_Security_** tab of the `temp` folder properties is no user list available. In the area for the users is a label with the text "No permissions have been assigned for this object.".

![grafik](https://github.com/ONLYOFFICE/DesktopEditors/assets/117105618/cbfb4237-0e0d-4130-a8d9-d31f50673ef6)

In the **_Advanced_** window is only a info that the current user is the owner of the folder, but the object still has no assigned permissions.

**Comment by LuckySpecialist** [comment] 2023-06-22 07:32
> In the **_Security_** tab of the `temp` folder properties is no user list available. In the area for the users is a label with the text "No permissions have been assigned for this object.".

Well, now everything has fallen into place.
Can you somehow comment on why your user does not have any rights to this folder, although by default it should?

**Comment by BLinus22** [comment] 2023-06-25 22:21
> Well, now everything has fallen into place. Can you somehow comment on why your user does not have any rights to this folder, although by default it should?

I've been thinking about it the whole time, but I don't have an answer to the question. I also looked on my other PC (Windows 10) and there no user has a right on the `temp` folder too. 
Are you sure that the user should have rights on the folder by default? Because I did not change the rights on the folders on both PCs.
Or is there any other case where the rights on the folder change?

Maybe you or someone else can check his PC for the configuration of the rights on the `temp` folder.

**Comment by LuckySpecialist** [comment] 2023-06-26 16:23
Let's try to figure it out together:

1. What type of account does your user have (local, domain, Microsoft)?
2. What rights does he have in the system (user or administrator)?

**Comment by BLinus22** [comment] 2023-06-26 16:53
1. The user has a **local** account
2. The account has **administrator** rights in the system

**Comment by LuckySpecialist** [comment] 2023-06-28 21:44
Hi, @BLinus22!
I checked on a couple more PCs, including by a local user without administrator rights in the system. The problem still hasn't been reproduced. All users have read access to the `temp` folder.
We need to understand why the user does not have read permissions on your system.
It may have been influenced by some third-party applications. There are no other ideas yet...

**Comment by Zamzam64** [comment] 2023-07-11 17:09
Hi Y'all,
Having same issue on a win10 x64 PC, i found out that no permissions at all are granted on %temp% folder. Screenshots are in french.
![Capture](https://github.com/ONLYOFFICE/DesktopEditors/assets/139258344/2c41e8dd-0915-45bf-9096-64189ae7ef05)
Strangely the other folders in %temp% do have permission as follow.
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/139258344/d553eda4-9ddd-45b4-8196-cd779c795695)
I then changed the permissions on the %temp% folder as the other folders and it worked.

Question being as said by LuckySpecialist: what made such a difference? I'm gonna check on my other PCs trying to find out the common factor and share the result on this forum.

Anyway thanks a lot for your expertise that helped me to fix this non blocking but annoying  issue

**Comment by LuckySpecialist** [comment] 2023-07-12 13:27
Hi @Zamzam64, it's good news that the problem was solved, but it's still unclear why the user didn't have access by default.

**Comment by Zamzam64** [comment] 2023-07-13 07:31
Hi Y'all,
I ran some further testing and found out that permissions on TEMP folder were removed as well when disconnecting user session and opening it again.
Then by de-activating progressively applications from Start-up tab in Task Mngr, I found the culprit: Old program Digiscan from PLUSTEK used for portable scanner ColorPage SF600 from Genius.
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/139258344/579dca5f-869c-4887-90d5-54ddda3de73f)

* Confirmed by:
--- testing all apps (but this one) activated in Start-up tab then close and reopen user session : permissions stay 
--- testing all apps (but this one) deactivated in Start-up tab then close and reopen user session : permissions erased 

Furthermore
--- running this DIGISCAN interactively creates same mess (Permissions on TEMP folder erased)

I did not try yet to set-up compatibility mode as this program back dated 2012, that will be next step and will let you know.

Hope this investigation will help other users to fix their own similar issue.

**Comment by LuckySpecialist** [comment] 2023-07-17 22:42
Hi @Zamzam64, do you need administrator rights when running the DIGISCAN application?

**Comment by Nukethefox** [comment] 2023-08-03 09:13
Hello everyone, I have the same problem.
Windows 11, every time I launch OnlyOffice, the "Error opening JSON file" appears. I searched for my "temp" folder and it has no permissions assigned. I don't have that "digiscan" program. What can I do?

**Comment by mbelletti** [comment] 2023-08-07 17:10
> 
> Is it possible to test such a scenario?
> 
>     1. Open the temporary directory: `Win+R` > `%temp% `> `Enter`

Hello.

I've the same problem: Error opening JSON file.
I found that onlyoffice_<>_x64.json is in C:\windows\temp instead in %temp% defined in user profile.
![Cattura](https://github.com/ONLYOFFICE/DesktopEditors/assets/493145/98d92959-4afa-425b-9413-a359e49f96e2)

Is the something that I can do?

Thank you

**Comment by LuckySpecialist** [comment] 2023-08-15 22:47
Hello @mbelletti, this is interesting.
Tell us more information about your system, the type of user account and the version of desktop editors that you use to check for updates?

**Comment by mbelletti** [comment] 2023-08-16 06:49
Hello @LuckySpecialist thank you for you reply.
That is my setup:
- win 10 pro on x64
- account is administrator
- Desktop Editors version 7.4.1.36 (x64 exe)

**Comment by LuckySpecialist** [comment] 2023-08-16 07:45
> Hello @LuckySpecialist thank you for you reply. That is my setup:
> 
> * win 10 pro on x64
> * account is administrator
> * Desktop Editors version 7.4.1.36 (x64 exe)

If an error occurs, are you physically connected to a PC or via a remote desktop?

**Comment by mbelletti** [comment] 2023-08-16 08:06
I'm connected via remote desktop

**Comment by LuckySpecialist** [comment] 2023-08-30 09:28
At this stage, we are closing this issue.

**Closed** 2023-08-30 09:48 UTC
