### ISSUE TITLE
Debian 10 XFCE, 1920x1080, large interface

### ISSUE THREAD

**Issue by SCratORS** [ONLYOFFICE/DesktopEditors#449] opened 2020-08-30 08:37 UTC
Interface onlyoffice default scaled 2x on 1080p in debian 10 xfce. it's very large
use --forced-scale=1 fix it.

**Comment by ShockwaveNN** [comment] 2020-08-31 06:22
Hi, could you provide information about real screen size of your display, if it's not very big, this issue may be duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/217

**Comment by SCratORS** [comment] 2020-08-31 09:31
14" 1920х1080.
Yes, it's duplicate #217

**Comment by ShockwaveNN** [comment] 2020-08-31 09:33
In that case I close this issue

**Closed by ShockwaveNN** 2020-08-31 09:33 UTC
