### ISSUE TITLE
Please add Page Borders to Document

### ISSUE THREAD

**Issue by tukykarmakar** [ONLYOFFICE/DesktopEditors#1542] opened 2024-03-30 10:34 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Please add the feature of Page Borders in OnlyOffice like it's there in Microsoft Word. In Word, I can select the margin I want and then make a page border along that margin, which can be further customized. I want the page border to look like what the top document has in the attached picture. If this feature is already available, then please let me know how to add the border.
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/42614682/eacb8a04-d143-4556-b588-4c965bc04421)

In OnlyOffice, there's no option for that, instead there's a paragraph border, which is unhelpful for my use-case. I want to create a page with a visible margin, not just a single paragraph having borders. Page border makes it easy to print out blank templates papers with margins.

I have mentioned this in the [OnlyOffice forum](https://forum.onlyoffice.com/t/how-to-add-page-border-in-only-office/2735) and a moderator named Alexander kindly raised the **internal tracksystem (59359)** for that. But since then, there has been no updates on this feature.

I'm trying to replace MS Office with OnlyOffice and lack of page border and annoying spellcheck language reset is preventing me from completely switching over.

**Comment by Rita-Bubnova** [comment] 2024-04-01 10:13
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1407. 

> I have mentioned this in the [OnlyOffice forum](https://forum.onlyoffice.com/t/how-to-add-page-border-in-only-office/2735) and a moderator named Alexander kindly raised the internal tracksystem (59359) for that. 

This issue 59359 about add custom theme to Desktop Editors. And this is a different task.

**Closed** 2024-04-01 10:13 UTC
Labels: duplicate

**Comment by Misokados** [comment] 2024-04-01 11:14
Dear @tukykarmakar 
Please do not post the same request in different communication channels. You have been provided with information about Page Borders (bug 48167) feature here: https://forum.onlyoffice.com/t/how-to-add-page-border-in-only-office/2735
In the same thread you discussed custom themes feature (bug 59359) with the moderator. I believe you may have mixed up bug numbers.
If you have any additional questions to your request, please post them on the forum since you started your communication there already.
