### ISSUE TITLE
Spell checker wrongly marks as wrong words with elision/apostrophe

### ISSUE THREAD

**Issue by Magneticdud** [ONLYOFFICE/DesktopEditors#1048] opened 2022-10-12 10:32 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.0.204

### Expected Behavior

Words like "doesn't", "cos'è", "dell'incanto" , "aren't" aren't marked as wrong

### Actual Behavior

Words with an apostrophe and elision are marked as wrong

### Reproduction Steps

1. Type a word with elision
2. See marked it as error

Tried with the spellchecker set to english and italian

### Additional information

Issue #1026 is similar, although original poster only mention one specific word and one specific language, instead the problem is generalized

**Comment by Magneticdud** [comment] 2022-10-12 10:51
![image](https://user-images.githubusercontent.com/2940598/195324119-be50c75e-0b77-4360-9c31-5b76bd5297cb.png)

**Comment by ShockwaveNN** [comment] 2022-10-12 11:03
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/576

**Closed by ShockwaveNN** 2022-10-12 11:03 UTC
