### ISSUE TITLE
[uncertain] Font Issues, systemwide following OnlyOffice Suite Update

### ISSUE THREAD

**Issue by whospoel** [ONLYOFFICE/DesktopEditors#1508] opened 2024-02-20 21:44 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.0.0

### Expected Behavior

Text is rendered normally

### Actual Behavior

Text rendering is broken since the update, not only in the software, but also in other apps/programs
Desktop environment or Webbrowsers are not affected. Sometimes text is illegible:
![2024-02-20 21_39_39-](https://github.com/ONLYOFFICE/DesktopEditors/assets/128981034/626c0798-4c4d-441d-8454-77bb72bc654a)

This still happens even with bigger fonts, here at 24:
![2024-02-20 21_41_05-_Document2 docx - ONLYOFFICE Desktop Editors](https://github.com/ONLYOFFICE/DesktopEditors/assets/128981034/06f45bcb-2364-4e48-bf3d-524388ba87f3)

### Reproduction Steps

For me it's just starting the software or any other program that seems to render text similarly to this software

### Additional information

First of all, I am sorry if this is unrelated to the software, but after extensive googling I think I have ruled out nearly everything else. So I am posting this here on the off-chance that someone knows what's up. Thank you for reading this.

I cannot pinpoint the culprit of the issue, nor can I claim that this is definitely caused by the software, however the problem was definitely not present before updating and was encountered immediately afterwards. I know this, since I was writing a paper at the time and did the update to have access to the plugin store specifically. The issue appeared as soon as the software started after updating. It's not only text either, but there are issues in the GUI as well, as seen in this screenshot. 
![2024-02-20 21_24_52-Window](https://github.com/ONLYOFFICE/DesktopEditors/assets/128981034/3a736a61-2253-42c7-9aaf-1da6ce30f143)

maybe relevant:

Screen Resolution: 1080p
Scaling: 100%
ClearType: On

**Comment by VladimirProkofiev52** [comment] 2024-02-21 11:18
Hello! @whospoel 
We noticed that your system font looks different.
Could you please tell us if you've changed the font on your system?
If you did, what font did you change it to?
Try resetting the system font settings to default and see if the issue persists.

Try launching our editor with the command: --disable-gpu
Here's how:

1. Right-click on the shortcut of our editor.
2. Select "Properties" from the menu.
3. In the "Shortcut" tab, append --disable-gpu to the "Target" field.
(It should look something like this: "C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe" --disable-gpu)
4. Apply the changes.

Is the text display issue only occurring in our application or in others as well?

Please provide the specifications of the computer where the issue is happening.

**Comment by VladimirProkofiev52** [comment] 2024-02-22 09:53
We're pleased that we could assist you in identifying the problem. However, regrettably, we're unable to aid in resolving it as it lies outside the scope of our application. 
It's possible that reinstalling your graphics driver could offer a solution, or you might consider installing a previous version of the graphics driver.

Since the issue doesn't originate from our editor, we'll close this ticket. 
Thank you for reporting it!

**Closed** 2024-02-22 09:57 UTC
