### ISSUE TITLE
[BUG] Doesn't open from the start menu but does with flatpak run command.

### ISSUE THREAD

**Issue by RDKRACZ** [ONLYOFFICE/DesktopEditors#666] opened 2021-07-14 19:46 UTC
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The app doesn't open from the start menu but it does when flatpak run command is used.

**Which version of DesktopEditors, and which OS are affected by this issue?**
Desktop Editors v6.3.1 FLATPAK on Ubuntu Cinnamon 21.04.

**Comment by Yuri6037** [comment] 2021-07-15 06:53
I have the same problem and I know why: the desktop Exec command line is broken: `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/usr/bin/onlyoffice-desktopeditors --file-forwarding org.onlyoffice.desktopeditors @@u %U @@`.

This command attempts to start `/usr/bin/onlyoffice-desktopeditors` but according to execvp the file does not exist:
`bwrap: execvp /usr/bin/onlyoffice-desktopeditors: No such file or directory`

**Comment by ShockwaveNN** [comment] 2021-07-15 08:13
Duplicate of https://github.com/flathub/org.onlyoffice.desktopeditors/issues/41

**Closed by ShockwaveNN** 2021-07-15 08:13 UTC
