### ISSUE TITLE
OpenOffice fails silently when saving a .docx file

### ISSUE THREAD

**Issue by stur86** [ONLYOFFICE/DesktopEditors#478] opened 2020-10-09 09:19 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
The problem is very similar to the one described in https://github.com/ONLYOFFICE/DocumentServer/issues/989. Saving a .docx file with certain specific characteristics (that I don't understand fully) results in a silent failure. If I check the terminal, the output is this error:

```
terminate called without an active exception
Received signal 6

==== C stack trace ===============================

 [0x7ff9abc2fd82]
 [0x7ff9ab0858a0]
 [0x7ff9aa922f47]
 [0x7ff9aa9248b1]
 [0x7ff9add93a75]
 [0x7ff9add71bc6]
 [0x7ff9add71bf3]
 [0x7ff9add718c6]
 [0x0000018e1e0b]
 [0x000001739c0a]
 [0x00000173a48d]
 [0x0000009f9728]
 [0x0000009ffe8d]
 [0x000000a012f4]
 [0x0000016bac75]
 [0x0000016baeb2]
 [0x0000016e216d]
 [0x00000151e492]
 [0x00000072d24d]
 [0x000000734c45]
 [0x0000007380b6]
 [0x00000053cbbf]
 [0x7ff9aa905b97]
 [0x000000713ca3]
[end of stack trace]
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The problem happens simply by saving a .docx by pressing Ctrl+S. The file it happens with to me is private and I can't share it; I am not sure how to create another one that still triggers the problem. However the similarity to the DocumentServer issue leads me to think that the same documents should trigger also this bug.

**What is the expected behavior?**
That the document is actually saved.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I'm currently using ONLYOFFICE Desktop Editors version 5.6.4.20 on Ubuntu Linux, version 18.04. It's the one provided by the Snap Store. This never happened to me before but I can not guarantee if it would have happened had I used this specific document, which is new.

**Comment by ShockwaveNN** [comment] 2020-10-09 09:28
> The file it happens with to me is private and I can't share it; I am not sure how to create another one that still triggers the problem

Could you try to remove all personal data from this file, replace it with some nonsense and attach it?

> However the similarity to the DocumentServer issue leads me to think that the same documents should trigger also this bug.

Problem is similar, but we are not 100% sure that it's the same problem, and for DocumentServer scenario was not with just single file, but with specific order of saving-opening files.

Also, FYI - we planning to release v6.0.0 in near future, I hope on next week if everything fine and it this is same issue as DocumentServer - it should be fixed, and in meantime - you can intalled older version of DesktopEditors, v5.6.0 - https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/ONLYOFFICE-DesktopEditors-5.6.0

**Comment by stur86** [comment] 2020-10-09 10:33
Here, this reproduces the issue for me. I edited it with Google Docs and redownloaded it, but still causes the problem. Note that when in Open Office it fails to save also in formats other than .docx.

[OOBugTest.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/5354263/OOBugTest.docx)

**Comment by ShockwaveNN** [comment] 2020-10-09 13:59
@stur86 We did some investigation, and indeed this is same issue as DocumentServer and seems we already have a similar report for DesktopEditors - https://github.com/ONLYOFFICE/DesktopEditors/issues/473

We thank you for pointing out this bug, but currently we cannot release DesktopEditors 5.6.5 with this bug fixed (because of our internal process of making release of v6.0).
I'm advicising to you to revert to version 5.6.0 until we release v6.0.0 with this issue fixed (we rechecked)
Sorry for your troubles.
I'll close this issue, but feel free to comment if have any troubles

**Closed** 2020-10-09 13:59 UTC

**Comment by soundsc** [comment] 2020-10-14 18:38
Confirmed. ~2 hours of work lost due to 5.6.4.20 silently failing to save on Debian 10. On Windows, the same document edited with the same version will also fail to save, but at least shows an error message. Downgrading to 5.6.0 seems to fix the issue (see @ShockwaveNN 's link above). Consider making 5.6.0 the default WWW download version to prevent data loss for random users. Other than that, cool software. Cheers!

**Comment by stur86** [comment] 2020-10-14 19:54
This. I understand not wanting to push the new version, but then a downgrade is in order. This bug is way too dangerous to simply leave be or have people sort it out themselves.

**Comment by ShockwaveNN** [comment] 2020-10-16 09:26
Sorry for your wait, DesktopEditors v6.0.0 are released and this problem should be fixed

**Comment by eldelacajita** [comment] 2020-10-18 18:23
Thanks for the update. This bug made me repeatedly and unknowingly loose hours of work, to the point that I can barely trust this software anymore.

**Comment by ShockwaveNN** [comment] 2020-10-19 07:21
@eldelacajita We are sorry for your lost work and will try to do anything in our power to not repeat this situation
