### ISSUE TITLE
Checkboxes from MS Office document are not displayed

### ISSUE THREAD

**Issue by Mer0me** [ONLYOFFICE/DesktopEditors#1383] opened 2023-10-11 12:11 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package)

### Version information

7.4.1.36

### Expected Behavior

OnlyOffice Desktop Editor should display all elements of a standard MS Office document, but official french government forms with checkboxes are not displayed correctly. Checkboxes are missing.

You can check here :
https://www.economie.gouv.fr/files/files/directions_services/daj/marches_publics/formulaires/EXE/imprimes_exe/EXE3-2019.doc

With Office 2010, document looks like this :
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/6248852/900fc401-6439-4c57-8d49-8a2beb213362)

### Actual Behavior

With OnlyOffice Desktop, document looks like this, even after docx conversion :

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/6248852/c059faa4-e2c4-41b1-85d2-ab17722d1591)

### Reproduction Steps

1. Download an office document with checkboxes, like this one : https://www.economie.gouv.fr/files/files/directions_services/daj/marches_publics/formulaires/EXE/imprimes_exe/EXE3-2019.doc
2. Open it on OnlyOffice Desktop Editor
3. See the checkboxes missing

### Additional information

Most of the french government forms on this page are not displayed correctly : https://www.economie.gouv.fr/daj/formulaires-marches-publics

**Comment by TatianaKirillova** [comment] 2023-10-12 13:40
Hello, @[Mer0me](https://github.com/Mer0me) 
Thanks for your request!
I can confirm - this is know bug, issue #44144 with your issue

Problem reproduces in Document Server.

**Comment by Rita-Bubnova** [comment] 2023-10-12 13:43
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2198. 
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by TatianaKirillova** [comment] 2024-10-03 10:21
@Mer0me I'm happy to report that the issue is fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/68b999b0e1c756183c31e582a5411cf85fd8cc2b) and will be included in the next release. Don't miss updates. Have a nice day!

**Comment by Rita-Bubnova** [comment] 2024-10-23 10:01
DesktopEditors v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-10-23 10:01 UTC
Labels: confirmed-bug, fixed-release
