### ISSUE TITLE
Strange bug when opening file on the cloud with the desktop edtior. 

### ISSUE THREAD

**Issue by louiesun** [ONLYOFFICE/DesktopEditors#1608] opened 2024-06-21 05:44 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.1.0

### Expected Behavior

The editors of the cloud file are same as the local file. 

### Actual Behavior

I'm sorry my English is not very good...
When I know v8.1.0 released
When I open a pptx file of my account on personal.onlyoffice.com(it is stll Document Server v8.0.1 up to the time I make the issue,  i think this why the bug occurs), I don't see the master button. 
But when I create a new local file, the button appears. 

### Reproduction Steps

1. create a account on personal.onlyoffice.com with language English. 
2. Download DesktopEditor and set language Chinese(or any). 
3. Open a Local file with editors using language Chinese. 
4. Open a cloud file with editors using language English!!!!! 

### Additional information

So I change the editor language to English(and my personal.onlyoffice.com editor language is chinese), and again open the cloud pptx file, the editor is chinese. '
So I guess we just edit the cloud file with the web editor instead of the local editor of the application. 
Just download the file and open in like a local file is okay! 
Or Downloading and uploading the file are wasting net? Can we send the local settings to the server? (But this won't work to the ppt master's disappreance because of the different versions, so I prefer to download the file and opening it with the local editor. )

**Comment by ElenaMaaya** [comment] 2024-06-28 08:18
Hello @louiesun!
Thanks for your report! 
I tried to reproduce this issue, but still unsuccessful. 
Could you make and attach a video (screencast) with a demonstration problem? 
 And, If you can, please attach test file for a more complete test.

**Comment by louiesun** [comment] 2024-06-28 11:00
Now the version os personal server has been 8.1.0, but it seems like tge bug of language is still there. (Or this is just a decision between local language and cloud language? )

https://github.com/ONLYOFFICE/DesktopEditors/assets/95512329/aef4e26e-b157-46fd-b53e-ae43e3ac98a4

**Comment by ElenaMaaya** [comment] 2024-07-01 14:31
Hello, @louiesun. You are right, it is not a bug, it is correct behavior. You open the editors from portal with cloud language.

**Comment by Rita-Bubnova** [comment] 2024-07-01 14:36
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-07-01 14:36 UTC
Labels: question
