### ISSUE TITLE
Filled round bullet points are showing as arrows 

### ISSUE THREAD

**Issue by Smartich0ke** [ONLYOFFICE/DesktopEditors#1506] opened 2024-02-20 10:01 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.0.0.99

### Expected Behavior

The bullet points show as filled round dots.

### Actual Behavior

Flat round bullet points are shown as left-pointing arrows in all fonts. I don't think this is a visual bug because they show in printing and in PDFs.
![Screenshot from 2024-02-20 20-24-23](https://github.com/ONLYOFFICE/DesktopEditors/assets/41409702/3a5d4c14-fba9-455a-a00f-c824229d35a5)
![Screenshot from 2024-02-20 20-26-01](https://github.com/ONLYOFFICE/DesktopEditors/assets/41409702/af7d6598-2588-4328-8397-3c76a51a01e6)

### Reproduction Steps

1. Open or create a new document.
2. write a list and format it with the unordered list tool, using the "filled round bullet" type or turn on the bullet tool before writing and expect the same result.
3. The bullets appear as arrows both in the document and the list menu.

### Additional information

The same behavior is visible across multiple different documents.

**Comment by matveevms** [comment] 2024-02-20 10:52
Hello, @Smartich0ke 
What system are you using?

**Comment by Smartich0ke** [comment] 2024-02-20 11:05
Ubuntu 23.10 with Gnome on xorg

**Comment by matveevms** [comment] 2024-02-26 14:48
I was unable to reproduce your problem on a clean Ubuntu 23.10 system running editor version 8.0.1.31. Try updating the editor to a new version. If the problem persists, then the problem is in the fonts installed on the system.

Editor version 8.0.1.31 is already available on the official website and in the near future it will be possible to update through the repository.

**Comment by dasbenjo** [comment] 2024-03-05 23:58
Which changes I have to make to the fonts, when this problem remains? Tested the new version 8.0.1.31 with flatpak and appimage on Kubuntu 23.10 (X11), but the problem remains. With other applications I can use the bullet point.
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/25540682/18a81904-3c14-4f09-9c21-21d78427970b)

**Comment by HectorB-2020** [comment] 2024-03-09 18:12
@Smartich0ke, I'm recalling some other issues related to bullets. Please take a look, some of them could resemble yours.

- https://github.com/ONLYOFFICE/DocumentServer/issues/2209
- https://github.com/ONLYOFFICE/DesktopEditors/issues/317
- https://github.com/ONLYOFFICE/DesktopEditors/issues/469
- https://github.com/ONLYOFFICE/DesktopEditors/issues/501
- https://github.com/ONLYOFFICE/DesktopEditors/issues/546
- https://github.com/ONLYOFFICE/DesktopEditors/issues/1095
- https://github.com/ONLYOFFICE/DocumentServer/issues/1127
- https://github.com/ONLYOFFICE/DocumentServer/issues/2372

**Comment by Heath123** [comment] 2024-04-30 22:42
I am also getting this issue. I'm on Ubuntu 23.10 and OnlyOffice 8.0.1.31 installed via Snap
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/13787163/0e21b4e8-171a-4a9b-baa1-b40daf5d9412)

**Comment by dasbenjo** [comment] 2024-05-27 22:17
could be a problem with Ubuntu 23.10. I am now on 24.04 and it is fixed. I get round bullet points as expected, no more weird arrows instead 🎉

**Comment by matveevms** [comment] 2024-08-15 18:27
I confirm, I was not able to replicate this on Ubuntu 24.04. We will close this Issue, but you can always write here if you have questions on this topic.

**Closed** 2024-08-19 08:59 UTC
