### ISSUE TITLE
Table of figures/Table of contents link mixup when doing select all -> right click -> update field in Document  Editor

### ISSUE THREAD

**Issue by Will-Banksy** [ONLYOFFICE/DesktopEditors#1569] opened 2024-05-07 14:06 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.0.1.31

### Expected Behavior

When I select all (ctrl + a) -> right click -> update field, each table of contents/figures/etc. should be updated to link to the corresponding header/figure/etc.

### Actual Behavior

When I select all -> right click -> update field, each table of contents/figures/etc. updates to link to either headings, figures, tables, etc., instead of the correct, corresponding ones, but does show the correct items.

So, each ToC/etc. will show the correct contents, but each will only link to one of the headers, figures, etc., e.g. the ToC and ToF will both link to headers, or both will link to figures.

It seems to always/usually choose the last ToC/ToF/etc. (i.e. if the last table is the table of figures all ToCs/ToFs/etc. will link to figures).

This also persists between saving/reopening and when exporting as PDF.

This issue doesn't happen when updating each ToC/etc. individually.

### Reproduction Steps

1. Create a new document
2. Create some figures, headers, etc.
3. Create a table of X for each
4. Select all -> right click -> update field
5. Ctrl + Click on the entries in each table of X to observe how they don't link correctly

Example file:
[OnlyOfficeBugDemo.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/15236619/OnlyOfficeBugDemo.docx)

### Additional information

Using the arch package from the "extra" repository on Manjaro Linux, under GNOME Wayland (not the DEB package).

**Comment by Rita-Bubnova** [comment] 2024-05-07 14:29
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2638.

**Closed by Rita-Bubnova** 2024-05-07 14:29 UTC
