### ISSUE TITLE
In Documents linux, bullets are not displayed correctly

### ISSUE THREAD

**Issue by maravento** [ONLYOFFICE/DesktopEditors#469] opened 2020-09-23 16:16 UTC
version: ONLYOFFICE Desktop Editors version 5.6.4.20
S.O: Ubuntu 20.04.2 LTS x64
MIME Type: .docx
Description: In Documents linux, bullets are not displayed correctly
Example:

**MS Office:**
![msoffice](https://user-images.githubusercontent.com/14880802/94039933-f0c6d500-fd8d-11ea-98ac-f8ebed6695aa.png)

**ONLYOFFICE Desktop Editors version 5.6.4.20 for Windows:**
![windows](https://user-images.githubusercontent.com/14880802/94040127-2ec3f900-fd8e-11ea-9094-86d74e34716e.png)

**ONLYOFFICE Desktop Editors version 5.6.4.20 for Linux:**
![linux](https://user-images.githubusercontent.com/14880802/94040170-3c797e80-fd8e-11ea-8f84-74bc1a6d7907.png)

thanks

**Comment by zilexa** [comment] 2021-08-10 21:59
Same issue here.

**Comment by ShockwaveNN** [comment] 2021-08-11 09:56
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/501

**Closed by ShockwaveNN** 2021-08-11 09:56 UTC
