### ISSUE TITLE
Find: `Ctrl`-`F` followed by `Enter`  does not move to the desired location on recently opened document

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1440] opened 2023-12-05 20:14 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.5.0.127

### Expected Behavior

`Ctrl`-`F` followed by `Enter` scrolls down to certain page in document and positions cursor to the found piece of text.

### Actual Behavior

The dialog invoked with `Ctrl`-`F` in upper right corner correctly shows number of found text fragments, e.g. 1/5.
But every time I press `Enter` or click arrow down `v`, document page doesn't move, stays on the first page. Though index of fragment increases like 2/5, then 3/5 and so on.

### Additional information

* https://github.com/ONLYOFFICE/DesktopEditors/issues/1074
* https://github.com/ONLYOFFICE/DocumentServer/issues/2289
* https://github.com/ONLYOFFICE/DesktopEditors/issues/1318
* https://github.com/ONLYOFFICE/DocumentServer/issues/2027

**Comment by XDmitryK** [comment] 2023-12-11 09:12
@HectorB-2020 Hi
Unfortunately, I cannot reproduce your case in versions 7.5 and 7.5.1 of the Onlyoffice.
Can you attach a short video?

**Comment by HectorB-2020** [comment] 2023-12-11 12:29
Interesting, I cannot reproduce it now either.
I'll probably have to file that file as it could be file specific.

**Comment by XDmitryK** [comment] 2024-02-15 13:39
@HectorB-2020 
If the problem does not recur, then I will close this issue.

**Closed** 2024-02-15 13:55 UTC
