### ISSUE TITLE
VLOOKUP not working across different documents

### ISSUE THREAD

**Issue by DarhonSoftware** [ONLYOFFICE/DesktopEditors#1083] opened 2022-10-30 06:49 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.1.1.57

### Expected Behavior

When using VLOOKUP, I would expect to be able to choose a range in Table_array from a different document (file).
This function only allows to select a range from a different tab in the the same document. 

### Actual Behavior

When using VLOOKUP, there is no option to choose a range in Table_array from a different document (file)

### Reproduction Steps

1. Click on fx (function)
2. Search and select VLOOKUP
3. Click on Table_array and a pop-up window will come out to select a range
4. Change to another document from the tiles at the top
5. The pop-up window disappears and there is no way to select a range in the new document

### Additional information

I'm using Onlyoffice as a Flatpak.

**Comment by ShockwaveNN** [comment] 2022-10-31 07:45
I think I can mark this as duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/982

Right now we do not support calling formula from another files, since this mechanics highly depends on DMS and we don't think it's easy to implement right now

**Closed by ShockwaveNN** 2022-10-31 07:45 UTC
