### ISSUE TITLE
Missing Paste Unformatted Text Hot Key And Popup Menu

### ISSUE THREAD

**Issue by mehelme** [ONLYOFFICE/DesktopEditors#843] opened 2022-02-11 07:59 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.0

### Expected Behavior

"Paste Unformatted" command via Hot Key CTRL+SHIFT+V and via Popup Menu by right mouse click - is **must have** feature as it presents in whole around software: editors\browsers\mailers and so on
So it is a bug what it is not present in Onlyoffice

### Actual Behavior

Nothing happens

**Comment by ShockwaveNN** [comment] 2022-02-11 08:07
I think it's duplicate of 

https://github.com/ONLYOFFICE/DocumentServer/issues/1002

Or 

https://github.com/ONLYOFFICE/DocumentServer/issues/1141

**Closed by ShockwaveNN** 2022-02-11 08:07 UTC

**Comment by mehelme** [comment] 2022-02-11 10:23
I dont understand what is "DocumentServer" if i using desktop app ?
