### ISSUE TITLE
File is not showing any change, When edit any cell.

### ISSUE THREAD

**Issue by maxj97983** [ONLYOFFICE/DesktopEditors#1345] opened 2023-08-16 09:35 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.4.1.36 (deb)

### Expected Behavior

Change the cell value and save the file. When open the same file again, Changed value should be shown.

### Actual Behavior

After change the cell value, save and close it. Again open the file, It will show the earlier value, not showing the changed value. It means current highlighted cell value is not changing.

### Reproduction Steps

1. Open an excel file of dummy data of 10 rows and 10 columns.
2. Let see change the value of (1,1) cell .
3. Save the file.
4. Again open the file, Value of(1,1) will be show the earlier value and not the changed value.
5. Changes are reflect only when select the another cell after change.

### Additional information

https://github.com/ONLYOFFICE/DesktopEditors/assets/141709637/882aa698-ff24-4876-9df0-62162fc3692c

**Comment by LuckySpecialist** [comment] 2023-08-17 15:17
Hi @maxj97983!
This problem is known as Bug 36551. Added your request there.
Thanks for the feedback.

**Comment by Rita-Bubnova** [comment] 2023-08-17 15:25
Maybe, duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/963.

**Closed** 2023-08-17 15:46 UTC
Labels: duplicate
