### ISSUE TITLE
Side scroll with mouse not function properlly

### ISSUE THREAD

**Issue by lighttigerXIV** [ONLYOFFICE/DesktopEditors#1219] opened 2023-02-24 12:11 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

ONLYOFFICE Desktop Editors version 7.3.0.184 (flatpak)

### Expected Behavior

When side scrolling with my mouse it should scroll properly.

### Actual Behavior

When using side scroll with my mouse (mx master 3) it scrolls horizontally but it scrolls vertically too, although not so much. 

### Reproduction Steps

1. Scroll horizontally with mouse.
![onlyoffice-scroll-bug](https://user-images.githubusercontent.com/35658492/221175877-e7f83e7d-d804-4a6d-955a-7adedd0063fc.gif)

### Additional information

I don´t know if this behavior is expected but there should be a toggle for that in that case. Thank you for excellent work all these years btw. :)

**Comment by Rita-Bubnova** [comment] 2023-03-02 10:33
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/536.

This issue actual in DocumentServer.

**Closed** 2023-03-02 10:36 UTC
Labels: duplicate
