### ISSUE TITLE
Onlyoffice Desktop interface displays huge padding on the right and bottom (Manjaro/KDE)

### ISSUE THREAD

**Issue by major-mayer** [ONLYOFFICE/DesktopEditors#450] opened 2020-09-05 14:04 UTC
**Do you want to request a *feature* or report a *bug*?**
Bugreport

**What is the current behavior?**
If I start the Onlyoffice Desktop Editors under Manjaro Linux (some sort of Arch Linux) using the KDE desktop environment it looks something like this:

![grafik](https://user-images.githubusercontent.com/17907799/92306716-9f4ad780-ef91-11ea-99d2-309074a610f6.png)

This is pretty much unusable and wastes a log of space.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
No specific steps required.

**What is the expected behavior?**
It should just display the desktop editors normal, not with this huuuge margin to the bottom and right.
I know about the HiDPI problems, but that's not what i want to address here. For me this is a separate issue.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I tested it with 5.6.0 Snap and 5.6.0.1 from the official repositories, but it's both broken.
My OS is Manjaro Linux with a 5.7.15 Linux kernel and KDE Plasma 5.19.4.

**Comment by ShockwaveNN** [comment] 2020-09-05 15:12
Hi, this is a duplicate of this issue #217, particularly [this](https://github.com/ONLYOFFICE/DesktopEditors/issues/217#issuecomment-622801481( comment

**Closed** 2020-09-05 15:13 UTC
Labels: duplicate
