### ISSUE TITLE
[FR] Embed fonts into document

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1057] opened 2022-10-16 18:17 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

May I ask to implement this feature which also exists in other text processors like LibreOffice Writer and MS Word?

The most vivid example is that many Linuxes are shipped with alternative fonts. For start my Ubuntus and Fedoras don't have that notorious Times New Roman, they are supplied with Liberation and other types of fonts. On the other hand I doubt all these fonts are installed by default on Windows hosts.

Here is how a file made in LibreOffice Writer look like if I chose to embed fonts:
```
unzip -l embed-font-test.docx 
Archive:  embed-font-test.docx
  Length      Date    Time    Name
---------  ---------- -----   ----
     2484  2022-10-16 17:57   word/styles.xml
     1532  2022-10-16 17:57   word/document.xml
     1491  2022-10-16 17:57   word/fontTable.xml
      390  2022-10-16 17:57   word/settings.xml
     1196  2022-10-16 17:57   word/_rels/fontTable.xml.rels
      531  2022-10-16 17:57   word/_rels/document.xml.rels
      573  2022-10-16 17:57   _rels/.rels
      731  2022-10-16 17:57   docProps/core.xml
      543  2022-10-16 17:57   docProps/app.xml
     2466  2022-10-16 17:57   [Content_Types].xml
   411344  2022-10-16 17:57   word/fonts/font6.odttf
   388528  2022-10-16 17:57   word/fonts/font1.odttf
   371200  2022-10-16 17:57   word/fonts/font3.odttf
   407200  2022-10-16 17:57   word/fonts/font8.odttf
   365292  2022-10-16 17:57   word/fonts/font2.odttf
   413108  2022-10-16 17:57   word/fonts/font7.odttf
   371292  2022-10-16 17:57   word/fonts/font4.odttf
   407860  2022-10-16 17:57   word/fonts/font5.odttf
---------                     -------
  3147761                     18 files

```

**Comment by ShockwaveNN** [comment] 2022-10-16 18:30
I think this is duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/228

**Closed by ShockwaveNN** 2022-10-16 18:30 UTC
