### ISSUE TITLE
Ditch xwayland and switch to wayland 

### ISSUE THREAD

**Issue by n3thshan** [ONLYOFFICE/DesktopEditors#1259] opened 2023-03-30 02:36 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

xwayland has many problems like on gnome with fractional scaling, everything is blurry and also the scrolling is not one to one giving a limited experience especially for touchpad users.

**Comment by spoorun** [comment] 2023-08-21 23:58
This issue remains and not just on Gnome but also on KDE
The only resolution is by native Wayland support, without it running DesktopEditors will still have blurry issues etc when run ontop of Wayland.

The main distros and even KDE are defaulting to Wayland, and almost all major apps including Libreoffice support native wayland. 

**See also**

#561 Blurry appearance when running on Wayland
and
#382 Linux binaries crashes on startup on Wayland

**Comment by rempas** [comment] 2023-11-18 22:02
Any updates? Is this worked on?

**Comment by matveevms** [comment] 2023-11-20 14:08
Hello, @rempas 
We are aware of this problem and are already working on a solution.
We will inform you as soon as there is news on this matter.

If you have problems with fractional scaling, you can follow the news in issue https://github.com/ONLYOFFICE/DesktopEditors/issues/561.

**Comment by Rita-Bubnova** [comment] 2023-11-20 14:22
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/561.

**Closed by Rita-Bubnova** 2023-11-20 14:22 UTC
