### ISSUE TITLE
4k monitor bug - flickering and white spaces

### ISSUE THREAD

**Issue by Coffeetron** [ONLYOFFICE/DesktopEditors#261] opened 2019-09-21 23:48 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

SPREADSHEET:
When moving the cursor over random areas of the window, parts become white spaces and stay that way. They randomly disappear when clicking on cells or buttons only to reappear in other places.
When entering random values or clicking on random buttons the whole window flickers.

DOCUMENT:
No white spaces observed, except for screen flickering when typing or clicking buttons.

PRESENTATION:
None of those issues observed.

IMPORTANT:
This happens on my Acer 28" 4k monitor when the window is maximized.
If the window is not in full screen mode I do not observe white spaces but flickering only in mentioned spreadsheet and document mode.

I have tested this on a Full HD monitor - no issues whatsoever.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

ONLYOFFICE Desktop Editors version 5.3.95.49
Arch Linux
Gnome 3.34.0
(Wayland)

A few months ago I did not observe those issues on the same hardware with Manjaro.
I do not know the version but it  was certainly an older Desktopeditor version...
![XC](https://user-images.githubusercontent.com/55640502/65380384-e6857d00-dcda-11e9-85e6-85bb08dba7fd.png)

**Comment by ShockwaveNN** [comment] 2019-09-23 08:10
Hi, this is known issue in our internal issue tracker, 40526. We try to figure some out

**Comment by ShockwaveNN** [comment] 2019-09-23 08:11
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/185

**Closed by ShockwaveNN** 2019-09-23 08:11 UTC
Labels: bug

**Comment by Coffeetron** [comment] 2019-09-23 17:25
Spasibo
