### ISSUE TITLE
[BUG] Key mapping for polish letters ę and ć

### ISSUE THREAD

**Issue by mnerd** [ONLYOFFICE/DesktopEditors#627] opened 2021-05-20 10:39 UTC
When I try to get ę pressing alt+e I get €. And letter ć (alt+c) gives ©. Rest of polish letters is ok

osX 10.14, 10.15, ONLYOFFICE 6.2

regards, Robert

**Comment by Rita-Bubnova** [comment] 2021-05-20 10:59
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/598.

**Closed** 2021-05-24 11:35 UTC
Labels: duplicate
