### ISSUE TITLE
The radio buttons and checkboxes added in DOCXF cannot be used after being converted to PDF.

### ISSUE THREAD

**Issue by Dlinw** [ONLYOFFICE/DesktopEditors#1590] opened 2024-06-06 01:39 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.0.1

### Expected Behavior

I hope that the form elements will function properly after being converted to PDF.

### Actual Behavior

The converted form is just a regular box, not a functional form element. When using OpenPDF, the form elements can be retrieved, but the radio button type is incorrectly retrieved as a checkbox type. Additionally, assigning values using OpenPDF does not work, and the radio buttons cannot be selected when the PDF is opened in a PDF viewer.

Here is the editing page in DOCXF：
![CleanShot 2024-06-06 at 09 37 18@2x](https://github.com/ONLYOFFICE/DesktopEditors/assets/45334447/41e68bca-6453-487b-8d47-54009df8aa4d)

Here is the effect of the PDF in the browser：
![CleanShot 2024-06-06 at 09 38 03](https://github.com/ONLYOFFICE/DesktopEditors/assets/45334447/0a2ca946-9057-4433-bcd0-bb271e996ed9)

**Comment by Dlinw** [comment] 2024-06-06 01:46
Additionally, I need to mention that after setting the option values for the radio buttons, OpenPDF still retrieves the option values as Choice*.

**Comment by Dlinw** [comment] 2024-06-06 01:54
Sorry, I got it wrong. I should have brought up this issue with DocumentServer.

**Comment by Rita-Bubnova** [comment] 2024-06-14 13:43
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2756.

**Closed by Rita-Bubnova** 2024-06-14 13:43 UTC
