### ISSUE TITLE
please support tsv file,like csv

### ISSUE THREAD

**Issue by heartacker** [ONLYOFFICE/DesktopEditors#1429] opened 2023-11-17 07:58 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

现在不支持 打开 tsv
请求支持打开 tsv
csv 以`;` 分隔
tsv 以`\t` 分隔

Currently, tsv files cannot be opened.

Request to support opening tsv files.

CSV files are separated by semicolons (;).

TSV files are separated by tabs (\t).

**Comment by Rita-Bubnova** [comment] 2023-11-17 08:45
Hello, @heartacker .
Please fill out the form template in english.

**Comment by heartacker** [comment] 2023-11-17 09:09
updated

**Comment by Rita-Bubnova** [comment] 2023-11-17 09:14
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1052.

**Closed by Rita-Bubnova** 2023-11-17 09:14 UTC
