### ISSUE TITLE
[Bug] Figure / Table Caption Numbers are not automatically updated when removing a figure / table between two existing figures / tables

### ISSUE THREAD

**Issue by philipreimer** [ONLYOFFICE/DesktopEditors#360] opened 2020-04-15 16:40 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Figure / Table Caption Numbers are not automatically updated when removing a figure / table between two existing figures / tables.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open OnlyOffice DesktopEditors and create a new document
1. Insert a table
1. Insert caption for table => "Table 1: a"
1. Insert a second table beneath the first table
1. Insert caption for second table => "Table 2: b"
1. Insert a third table beneath the second table
1. Insert caption for third table => "Table 3: c"
1. Delete the caption for the second table, additionally also delete the complete second table.

**What is the expected behavior?**
The caption for the third table should be updated from "Table 3: c" to "Table 2: c" because there are now only two tables left in the document.

But in the current version the caption is not updated and remains "Table 3: c". See attached [test2.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/4482516/test2.docx)

This also happens if you insert images from file instead of tables.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 5.5.1.78
Manjaro Linux Gnome 3.36.1

Figure and table captions did not exist before version 5.5.1

**Comment by XDmitryK** [comment] 2020-04-16 11:05
I think this is an analogue of behavior
Duplicate of #359

**Closed** 2020-04-16 11:06 UTC
