### ISSUE TITLE
PDF annotation, text/image selection and copying, editing?

### ISSUE THREAD

**Issue by dronkit** [ONLYOFFICE/DesktopEditors#1073] opened 2022-10-25 21:00 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I'm on onlyoffice 7.1.1.57 on pop OS 20.04. When opening a PDF file, I can view it but I can´t find any tools to select images, or annotate the PDF whatsoever. The only ribbon menus are File and Extensions.
I want to suggest the possibility of selecting and copying images, a snapshot tool that you can drag and copy an image of the selected rectangle to clipboard, and the possibility of annotating PDF, ie. highlighting text, putting on stamps, drawing shapes or freehand and inserting text comments as a typewriter on the page or as small comment icons, as most PDF viewers can.
Also, in the future, it would be great to have actual PDF editing capabilities, like, selecting the PDFś actual text fields and editing them, adding or deleting images and other elements, etc.

**Comment by ShockwaveNN** [comment] 2022-10-26 06:10
I think this can be marked a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1359, same idea

We planning to make annotation mode, but I cannot provide any timeframe

**Closed by ShockwaveNN** 2022-10-26 06:10 UTC
