### ISSUE TITLE
Need a function to add ,delete or sort outline in PDF. 

### ISSUE THREAD

**Issue by edwardostara** [ONLYOFFICE/DesktopEditors#1721] opened 2024-11-15 10:53 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Will you have a plan to add such functions to add ,delete or sort outline in PDF?

**Comment by Gingetsu** [comment] 2024-12-02 13:25
Hello @edwardostara  !
This is the same problem as in this issue: #2469

**Comment by Rita-Bubnova** [comment] 2024-12-03 07:14
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2469.

**Closed by Rita-Bubnova** 2024-12-03 07:14 UTC
