### ISSUE TITLE
Mouse position randomly incorrect

### ISSUE THREAD

**Issue by Yuri6037** [ONLYOFFICE/DesktopEditors#673] opened 2021-07-17 15:11 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Randomly, when all editors are attached to the main parent "ONLYOFFICE" window, the mouse position on all editors may start to randomly offset down forcing the user to click a little before the actual buttons. This bug happens on ALL editors except the main parent window. I haven't been able to recreate the problem when all editors are detached from the parent window.

**What is the expected behavior?**
No mouse position offset

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 6.3.1.56
PopOS 21.04 (Ubuntu Linux derivative)

**Comment by ShockwaveNN** [comment] 2021-07-19 06:17
Hi, issue seems rather strange, never happened for me

Could you try to record a video with this happening

Also please state your display resolution, its phisical size (14 inches for example) and scaling setting value from settings

I think this may be related to scaling

**Comment by Yuri6037** [comment] 2021-07-19 08:16
The problem happened twice so for now it'll be hard to recreate it.

As for the additional information:
- the size of the screen should 15 inches (the computer is a laptop from System76 - OryxPro)
- the display resolution is maxed at 1920x1080
- the display scaling in GNOME and NVIDIA is default 100%
- the interface scaling in OnlyOffice is set to 100% instead of Auto due to another bug of your editors: your editors are unable to detect that both NVIDIA and GNOME are set to 100% it detects instead 200% which is too big on that screen. This is not a QT bug as I have some other QT apps like VLC which have no problems detecting interface scaling properly.

**Comment by ShockwaveNN** [comment] 2021-07-19 10:00
Ok, if you ever encounter this - please record video

You settings, display resolution seems standart - so I think we can leave this issue opened and I show it to my colleagues but if cannot reproduce it - I don't think we can do anything about this

**Comment by Rita-Bubnova** [comment] 2024-09-04 13:05
@Yuri6037,  DesktopEditors v 8.1 is released. Please state is this problem still actual for you?

**Comment by sunhunter777** [comment] 2024-09-09 12:36
Perhaps it will help in solving the problem. A similar bug appeared in DocumentServer, 8.1 version. Gif attached.
![Onlyoffice](https://github.com/user-attachments/assets/9632b8ae-8208-43d1-be90-f0a707f70acc)

**Comment by Rita-Bubnova** [comment] 2024-09-11 07:50
> Perhaps it will help in solving the problem. A similar bug appeared in DocumentServer, 8.1 version. Gif attached. Clearing the browser cache helped !

This is another [problem](https://github.com/ONLYOFFICE/DocumentServer/issues/2859).

**Comment by Rita-Bubnova** [comment] 2024-09-11 07:51
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-09-11 07:51 UTC
Labels: help wanted
