### ISSUE TITLE
The first line indentation and hanging supports character units

### ISSUE THREAD

**Issue by Leroy-X** [ONLYOFFICE/DesktopEditors#1455] opened 2024-01-06 02:05 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

The default now is to use centimeters for indentation. In my native language, the first line is usually indented by two characters.
Expect character units to be used, or character units to be selected via the context menu.

Thank you so much

**Comment by HectorB-2020** [comment] 2024-01-06 15:13
The idea is not bad, though I doubt it's doable. Different characters have different width, unless you use monospace fonts. Also consider kerning which under certain circumstances can easily squeeze three symbols in the same space as two symbols usually take. Or one `W` could be as wide as whole word `Is`.

**Comment by Rita-Bubnova** [comment] 2024-01-09 09:23
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1282.

**Closed by Rita-Bubnova** 2024-01-09 09:23 UTC

**Comment by TatianaKirillova** [comment] 2024-01-10 12:26
Hello @Leroy-X! Thank you for your request!
I assure you that we have correctly identified the problem. It may not be obvious, but w:docGrid support needs to be implemented. Both problems need this

**Comment by TatianaKirillova** [comment] 2024-01-10 12:35
@Leroy-X Contact us! We will be happy to help you!
