### ISSUE TITLE
Automatic Switching between Light & Dark theme

### ISSUE THREAD

**Issue by Roxiun** [ONLYOFFICE/DesktopEditors#961] opened 2022-06-19 05:31 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Automatically switch between light and dark theme (sync with system).

Currently (at least on MacOS) you must manually change the theme in settings, the editor does not update with rest of the OS (no option to change theme to sync with system).

For Example

Theme set to Light and system theme set to dark
<img width="1440" alt="Screen Shot 2022-06-19 at 1 24 27 pm" src="https://user-images.githubusercontent.com/31913075/174467174-9bc78e78-067f-4abb-b99b-1167b880e7f8.png">

Theme set to dark and system theme set to light
<img width="1440" alt="Screen Shot 2022-06-19 at 1 24 51 pm" src="https://user-images.githubusercontent.com/31913075/174467183-cb737383-d35d-4156-8c4e-b40a6e52f179.png">

I did try making a janky implementation by setting the plist properties to the required theme, however this is far from ideal

`asc.onlyoffice.ONLYOFFICE "asc_user_ui_theme" -string "theme-dark"` appears to be the plist string which sets the theme

This may be useful:
https://successfulsoftware.net/2021/03/31/how-to-add-a-dark-theme-to-your-qt-application/#macOS

**Comment by ShockwaveNN** [comment] 2022-06-20 07:44
Hi, this is a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1746

**Closed by ShockwaveNN** 2022-06-20 07:44 UTC
