### ISSUE TITLE
Preview before opening csv file

### ISSUE THREAD

**Issue by NikolayEKolev** [ONLYOFFICE/DesktopEditors#944] opened 2022-06-03 19:53 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Currently (version ONLYOFFICE Desktop Editors v7.1) when opening a csv file the default option to open is with the TAB parameter, but the delimiter can be comma, semicolon, etc. To see what the file will look like you need to select the delimiter and only then see if it is the correct delimiter. 
Please add a preview in the separator selection screen. It would also be good to add what type each column is - text, numeric and so on.
![image](https://user-images.githubusercontent.com/70388317/171939673-84826170-3cc0-492f-9c38-b674a74fa3c5.png)

**Comment by Rita-Bubnova** [comment] 2022-06-10 10:56
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/160.

**Closed** 2022-06-10 11:30 UTC
Labels: duplicate
