### ISSUE TITLE
It isn't possible to perform update

### ISSUE THREAD

**Issue by rommy2015** [ONLYOFFICE/DesktopEditors#867] opened 2022-03-04 16:13 UTC
**ONLYOFFICE Desktop Editors версия 7.0.0.127**

during the installation of the application, an error appears that informs that: 

**### The process cannot access the file because this file is occupied by another process.**

**Comment by ShockwaveNN** [comment] 2022-03-04 16:19
I think some process of DesktopEditors is running in background, maybe try to reboot and install it again

And if this does not help - install new version manually from our side from https://www.onlyoffice.com/download-desktop.aspx

**Comment by sxge** [comment] 2022-03-07 10:46
I tried rebooting too. This Issue exists for me on every build since release of v6. However, no issues on linux, only on Windows. Manual installation works fine, but i'd prefer to just update using the little "Update Now" button.

**Comment by realsonic** [comment] 2023-03-20 18:30
Hi! The issue is still here. Any chances to get it fixed? Thanks.

**Comment by LuckySpecialist** [comment] 2023-08-07 10:08
This problem is fixed in version 7.4 after the update service was added.
Issue can be closed.

**Comment by Rita-Bubnova** [comment] 2023-08-07 10:13
DesktopEditors v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-08-07 10:13 UTC
Labels: bug, fixed
