### ISSUE TITLE
Print coming out on wrong printer

### ISSUE THREAD

**Issue by matiasduartee** [ONLYOFFICE/DesktopEditors#1422] opened 2023-11-14 19:34 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.5.0

### Expected Behavior

The expected behavior would be when I select printer A, the printout would be output to printer A

### Actual Behavior

From OnlyOffice, when I send a print to network printer A, the printout goes to USB printer B, selecting printer A correctly. I already reinstalled the zera program and nothing. I noticed that when you have a network printer and the USB printer is disconnected, it sends the printout to Microsft Print to PDF on Windows.

**Comment by LuckySpecialist** [comment] 2023-11-15 09:01
Hi @matiasduartee!
There are a few questions for you:
1. Is the problem repeated on the current version of the application 7.5.1?
2. Was there a problem on earlier versions of the application?
3. Can you describe your scenario and printer configuration in more detail?
4. Do you use the quick print feature?

**Comment by matiasduartee** [comment] 2023-11-26 22:29
Hi @LuckySpecialist !!

1. Yes, the problem still occurs in version 7.5.1.
2. The same problem happens in previous versions.
3. I have a network printer installed on the computer, via IP 10.0.0.2 (Ricoh MP 305+) and the computer 10.0.0.3, and another printer installed on the same computer via USB (Epson L3250). When I send a printout of the document to the IP 10.0.0.2 printer (Ricoh MP 305+) by selecting it in the print list, the printout is output to the USB printer (Epson L3250).
4. I don't use the quick print feature.

**Comment by Turab** [comment] 2023-11-27 12:03
I confirm this happens on Windows 11 and Onlyoffice Version  7.5.1.23 (x64)

I select a Brother laser printer from the dialog box; it says successfully sent to the printer but it prints from an HP printer (which is actually the "default" managed by Windows 11).

**Comment by DanielCarlos-hub** [comment] 2023-11-27 13:18
In my case, this problem is also occurring on the computers of some clients where the latest version of OnlyOffice was installed, with Windows 10 as the OS, clients with version 7.3.3.50 this problem does not occur. In the printers dialog box, it doesn't seem to be respecting the selected printer index.

**Comment by LuckySpecialist** [comment] 2023-11-27 13:54
@matiasduartee, @Turab & @DanielCarlos-hub thanks for the information.
I will try to reproduce the problem on my test environment.

**Comment by matiasduartee** [comment] 2023-11-29 11:44
Whether the video demonstrates the error when trying to print on the RICOH printer, see that the printout is sent to the Microsoft PDF printer.

**VERY IMPORTANT** detail, I removed version 7.5.1 and installed the OnlyOffice 7.3.3.50 version on the same computer and it worked correctly, that is, I selected the RICOH printer and the printout came out on the RICOH printer

@Turab  do this test in your environment, install version 7.3.3.50

https://github.com/ONLYOFFICE/DesktopEditors/assets/81826268/a148df8c-586c-4ce0-aee7-70dc1453636d

**Comment by LuckySpecialist** [comment] 2023-11-30 19:36
@matiasduartee, thanks for the video, but it didn't really help me understand the sequence of actions that lead to this problem.
I have already understood the essence of the problem from the description.
I think there should be some preliminary steps when the problem occurs, because I checked with two network printers and one local (connected via USB), so far without success.
I'll keep trying, but if you have any ideas, please write.

**Comment by matiasduartee** [comment] 2023-12-01 00:46
@LuckySpecialist As I said, in version 7.3.3.50 the error of sending the printout to the wrong printer does not occur!

**Comment by Turab** [comment] 2023-12-01 05:32
> I think there should be some preliminary steps when the problem occurs.

I don't think there are, because I can replicate the problem by;

- Restart computer
- Open a document
- Print
- It prints out to wrong printer.

Nothing in between, no any other steps needed.

**Comment by LuckySpecialist** [comment] 2023-12-01 07:52
> @LuckySpecialist As I said, in version 7.3.3.50 the error of sending the printout to the wrong printer does not occur!

Maybe so, but it makes little sense to check on the old version, the fix will already be on the current release branch.

> Nothing in between, no any other steps needed. So it is not related to any step taken by the user. It must be some conditional issue like a configuration, a driver incompatibility(?) or something similar.

If it were that easy to repeat, I would have passed the problem on to the developers long ago.

**Comment by Turab** [comment] 2023-12-01 08:35
> If it were that easy to repeat, I would have passed the problem on to the developers long ago.

That's exactly why I said it must be something conditional like a combination of configurations etc. Like there are some conditions present on some machines causing this and which are absent on your test machine. I said that because it is not caused by any step taken by the user. So no need for a video. For example on my machine, just start Windows, print a document and it will print on the wrong printer. This is not related to what I am doing before printing.

**Comment by matiasduartee** [comment] 2023-12-05 02:29
Machine conditions or not, I just know that in version 7.3.3.50 THE ERROR DOES NOT OCCUR.

**Comment by LuckySpecialist** [comment] 2023-12-06 10:47
Hi @matiasduartee @Turab, I have good news!
The problem turned out to be the length of the printer name, which should not exceed 31 characters. I issued it as Bug 65402.
I hope we will solve it soon.
Thanks for the feedback.

**Comment by LuckySpecialist** [comment] 2023-12-22 18:25
The problem is fixed [in this commit](https://github.com/ONLYOFFICE/desktop-apps/commit/d1074ed7fb9fd1a9ca0879ca4301fdb361f749a5) and will be included in the next release.

**Comment by Rita-Bubnova** [comment] 2024-02-01 08:41
Desktop Editors v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-02-01 08:41 UTC
Labels: confirmed-bug, fixed-release
