### ISSUE TITLE
OnlyOffice ignores the GTK style settings in plasma 5.15

### ISSUE THREAD

**Issue by M0rdecay** [ONLYOFFICE/DesktopEditors#230] opened 2019-05-26 18:39 UTC
I want to request a bug.

File open/save dialogs are as follows:
![image](https://user-images.githubusercontent.com/50422107/58385712-a6044400-8005-11e9-8612-98648580a5fc.png)

At the same time, GTK themes are specified in the style settings:
![image](https://user-images.githubusercontent.com/50422107/58385724-de0b8700-8005-11e9-914b-91fcc04de71c.png)
![image](https://user-images.githubusercontent.com/50422107/58385726-e9f74900-8005-11e9-9bc6-2b08201741dc.png)

In other non-QT applications, I could reassign the theme I was using with `-style=gtk`, but when I try to start the office with this parameter, I get an error:
`QApplication: invalid style override passed, ignoring it.`

I think this is a bug, because the application does not follow the system settings.
I already understood that there is no support for the native dialogue yet, but the current dialogue can use styles (I saw it in the Gnome/Unity). Or am I doing something wrong?

My system:
OS: KDE neon User Edition 5.15 x86_64 
Kernel: 4.15.0-50-generic

OnlyOffice:
ONLYOFFICE Desktop Editors 5.2.83.480 from ppa

**Comment by ShockwaveNN** [comment] 2019-05-27 08:45
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/164

**Closed by ShockwaveNN** 2019-05-27 08:45 UTC
