### ISSUE TITLE
Bug in spell checker in ukrainian language

### ISSUE THREAD

**Issue by niphoneua** [ONLYOFFICE/DesktopEditors#901] opened 2022-04-25 07:15 UTC
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.2

### Expected Behavior

When I type word with apostrophe, spell checker separate word with apostrophe and gives me spell error.

### Actual Behavior

When I type word with apostrophe, spell checker separate word with apostrophe and gives me spell error.

### Reproduction Steps

1. Type word with apostrophe

### Additional information

My language is ukrainian (i think it is cyrylic languages problem)

**Comment by ShockwaveNN** [comment] 2022-04-25 07:17
Hi, could you provide some examples of such words?

**Comment by niphoneua** [comment] 2022-04-25 07:34
Сім'я, об'єднання, бур'ян...

**Comment by ShockwaveNN** [comment] 2022-04-25 07:38
I think it's a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/576

This problem are not directly related to language, so Ukranian language has problems too

But thanks for your report anyway, I'll add it to our private issue 41724

**Closed by ShockwaveNN** 2022-04-25 07:38 UTC
