### ISSUE TITLE
Year is always 1975 with YYYY/MM/DD format in opening a CSV

### ISSUE THREAD

**Issue by KoichiM0** [ONLYOFFICE/DesktopEditors#1549] opened 2024-04-07 09:24 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

8.0.1

### Expected Behavior

In importing a csv file with dates in YYYY/MM/DD format in spreadsheat, the four digit number should be interpreted as year, but ONLYOFFICE converts it to MM.DD.1975, discarding the year information. Sorry but this is the first time I use ONLYOFFICE and I do not know how it worked in previous versions.

### Actual Behavior

Example file containing one liner:
2024/03/06,
In the spreadsheet after opening it, it appears as:
03.06.1975
or 6/3/1975 in the entering box. "2024" is lost from the data.

### Reproduction Steps

Example file containing one liner:
2024/03/06,
In the spreadsheet after opening it, it appears as:
03.06.1975
or 6/3/1975 in the entering box. "2024" is lost from the data.

**Comment by PJF-NZ** [comment] 2024-04-14 23:28
Please see issue #1544, which is similar to yours - thanks to @HectorB-2020 for drawing attention to this :-)

**Comment by VladimirProkofiev52** [comment] 2024-04-19 15:19
Hello! @KoichiM0 

I can confirm - this is bug, issue #55431.
Thanks for your report!

**Comment by Rita-Bubnova** [comment] 2024-04-24 12:08
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2629.

**Closed by Rita-Bubnova** 2024-04-24 12:08 UTC

**Comment by VladimirProkofiev52** [comment] 2024-04-24 12:17
@KoichiM0, Your issue is a duplicate, all discussions will be directed to another one. If you have any additional questions, please write them in this  [issue](https://github.com/ONLYOFFICE/DocumentServer/issues/2629).
