### ISSUE TITLE
Cursor jumping to the beggining of line after deleting selected text in the changes tracking mode

### ISSUE THREAD

**Issue by Zszywek** [ONLYOFFICE/DesktopEditors#1427] opened 2023-11-16 14:24 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.0.127

### Expected Behavior

After selecting the text or deleting words with Ctrl the cursor should appear just after the text which was previously just before the deleted text.

### Actual Behavior

After deleting the part of text with Ctrl or after selecting it, the cursor moves o the beginning of the line. The bug doesn't occur when deleting with backspace, single character at the time.

### Reproduction Steps

1. Turn on "Track changes" option in Collaboration tab.
2. Write several words.
3. Delete them word-by-word by holding Ctrl or select some text and delete the selected fragment.

### Additional information

I use the flatpak distribution if it matters. OS: Pop_OS! 22.04

**Comment by TatianaKirillova** [comment] 2023-11-17 11:44
Hello, @[Zszywek](https://github.com/Zszywek) 
Thanks for your request!
I can confirm - this is know bug, issue #63602 with your  proposal
Problem reproduces in Document Server.

**Comment by Rita-Bubnova** [comment] 2023-11-17 11:47
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2324.

**Closed by Rita-Bubnova** 2023-11-17 11:47 UTC

**Comment by Zszywek** [comment] 2023-11-17 14:04
Oh, sorry then, I was looking for it to avoid duplication but eventually failed as one can see

**Comment by TatianaKirillova** [comment] 2023-11-17 14:27
@Zszywek Everything is fine! Thanks for your vigilance

**Comment by TatianaKirillova** [comment] 2023-11-22 09:28
@Zszywek This issue fixed in future major release.
