### ISSUE TITLE
Right-click option to change slide background

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#177] opened 2019-02-03 11:58 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

Need an option to right-click a slide and change its background. Google Docs has it.

![screenshot from 2019-02-03 17-18-56](https://user-images.githubusercontent.com/22585732/52176448-fa768000-27d8-11e9-8afa-72578119b7e3.png)

OnlyOffice right-click menu is not as useful.
![screenshot from 2019-02-03 17-17-08](https://user-images.githubusercontent.com/22585732/52176460-14b05e00-27d9-11e9-8f6d-726d23d3edd7.png)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v 5.2.8

**Comment by Rita-Bubnova** [comment] 2019-07-17 13:46
Our team considered the issue of adding the “Change background” item to the context menu. 
As a result, it was decided to add the “Slide Settings” item to the context menu of the slide in the slide list.  Clicking on “Slide Settings” opens the “Slide Settings” tab of the right toolbar (if it was closed), in which you can change the background.

**Comment by uncertainquark** [comment] 2019-08-09 04:32
Hi, I'm using v5.3.3 and upon clicking "Slide Settings" the right toolbar tab does open but it doesn't get focused automatically. The buttons are not clickable until I click on the slide in the main view first.

**Comment by Rita-Bubnova** [comment] 2019-08-13 09:25
I'm not sure that I correctly understand the phrase "The buttons are not clickable until I click on the slide in the main view first".
You can explain more?

**Comment by uncertainquark** [comment] 2019-08-14 03:27
Here's a screenshot for how it is after I click "Slide Settings" from a slide context menu. Notice the unfocused state of the toolbar. Can't interact with the toolbar directly.

![toolbar-unfocused-state](https://user-images.githubusercontent.com/22585732/62992505-59e0d700-be71-11e9-8063-60877ac5858b.png)

Now here's a screenshot after I click anywhere on the slide, which then enables the toolbar to be clicked.

![toolbar-focused-state](https://user-images.githubusercontent.com/22585732/62992538-7a109600-be71-11e9-995b-d9dd3ec1c3a9.png)

**Comment by Rita-Bubnova** [comment] 2019-08-14 08:14
Unfortunately, I cannot reproduce the problem.
Can you attach video or gif of this problem?
Preinstall the latest version (5.3) of ONLYOFFICE Desktop Editors. And specify the OS.

**Comment by uncertainquark** [comment] 2019-08-25 03:47
Unable to reproduce it now all of a sudden. :/ 
Will get back if it happens again.

**Comment by ShockwaveNN** [comment] 2019-08-25 06:38
So i close this issue, feel free to commen if you'll be able to repduce

**Closed by ShockwaveNN** 2019-08-25 06:38 UTC
Labels: enhancement
