### ISSUE TITLE
Default fonts

### ISSUE THREAD

**Issue by hope-full** [ONLYOFFICE/DesktopEditors#315] opened 2020-01-26 14:24 UTC
Fonts shown by default for new documents are Arial (in text documents) and Calibri (in spreadsheets) even though they're not on the system.

In my opinion it would be better if the program showed the real name of the rendered font to avoid confusion.

**Comment by TatianaKirillova** [comment] 2023-08-25 10:03
Hello, @hope-full 
Thanks for your request!
I can confirm - this is know bug, issue #47180 with your proposal

**Comment by Rita-Bubnova** [comment] 2023-08-25 10:10
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/746.

**Closed by Rita-Bubnova** 2023-08-25 10:10 UTC
Labels: duplicate
