### ISSUE TITLE
Bengali Font Rendering Problem

### ISSUE THREAD

**Issue by ray6an1** [ONLYOFFICE/DesktopEditors#131] opened 2018-07-24 07:34 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Some font's of Bangali Language is not displaying correctly. ি (U+09BF), ে (U+09C7) need to be placed before any alphabet, but it's appearing after the previous alphabet. Those are vowel, you can learn more about Bangali alphabet at https://en.wikipedia.org/wiki/Bengali_alphabet

There also a form of Bengali Language called consonant conjunct or "Zuktakkhor" that's not showing correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This is a Bug and you can reproduce it by copy pasting my those words in Desktop Editors "যুক্তাক্ষর দেখিতে পাইলে অতি আনন্দিত হইতাম"

You will notice that the font's are not same as in your browser or Libreoffice or OpenOffice

**What is the expected behavior?**
It should rendered correctly as rendered in Libreoffice or Openoffice or Web Browser.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Desktop Editors Version: 5.1.29.348
OS: Tested in Ubuntu 18.04 and Windows 10
This was not working in any previous version of Desktop Editors, i am expecting that this will fix soon.

**Comment by Rita-Bubnova** [comment] 2018-07-24 09:01
Hello, @ray6an1.
Thank you. I can confirm - this is a bug, issue 38300 in our internal issue tracker.

**Comment by ArkaBhuiyan** [comment] 2021-07-30 17:49
Has anyone found a workaround for this issue yet? Is there any significant work to resolve this issue?

**Comment by ShockwaveNN** [comment] 2021-08-02 07:28
@ArkaBhuiyan Sorry, yes there is currently no workaround and there is significant work needed to completely and correctly resolve it

**Comment by princebillyGK** [comment] 2022-01-26 04:14
It is 2022 and the problem is still there. Is there any solution or update yet?

**Comment by ShockwaveNN** [comment] 2022-01-26 07:02
Sorry no, this problem is rather complicated and currently have not a high priority

If you want to discuss our priorities - please contact sales@onlyoffice.com

**Comment by hihabib** [comment] 2022-04-24 23:08
> Sorry no, this problem is rather complicated and currently have not a high priority
> 
> If you want to discuss our priorities - please contact [sales@onlyoffice.com](mailto:sales@onlyoffice.com)

It's making a problem at the time of writing the Bengali language. Why don't you consider as a problem? We can't use this software for office work for this problem

**Comment by ShockwaveNN** [comment] 2022-04-25 07:08
@hihabib We are consider this is a problem, but have not enough resources to fix it, sorry

**Comment by getashraf** [comment] 2022-05-16 07:24
Sorry to hear it is not your priority :-( 
Almost all major editors support multiple languages including Bengali. But OnlyOffice is taking too long to solve this.

**Comment by K0R0L** [comment] 2022-07-06 08:20
Version 7.2 support Bengali script. And a lot of new functionality with text shaping.

**Comment by ShockwaveNN** [comment] 2022-10-05 14:11
We released v7.2 several days ago, so this issue should be fixed

If there is still some issues - I think it's better to create a completely new issue on github

**Closed by ShockwaveNN** 2022-10-05 14:11 UTC
Labels: bug, fixed

**Comment by Shihabus-Sakib-Rad** [comment] 2023-12-10 11:30
![onlyofficeCapture](https://github.com/ONLYOFFICE/DesktopEditors/assets/47505877/69bff6ff-98ff-4616-81ef-ea25c7ec1f2a)

version 7.5.1.23 on windows 10 x64
