### ISSUE TITLE
Double page view on a single document

### ISSUE THREAD

**Issue by IlmastroStefanuzzo** [ONLYOFFICE/DesktopEditors#701] opened 2021-08-22 17:11 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Having an option to enable a double page view like on Microsoft Word would be really useful.

_The double page view on Microsoft Word_
![image](https://user-images.githubusercontent.com/71498817/130363943-a272e099-a320-4a75-abb1-0396de15212b.png)

**Comment by Rita-Bubnova** [comment] 2021-08-23 08:07
This issue actual in Document Server.
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/919.

**Closed** 2021-08-23 08:08 UTC
Labels: duplicate
