### ISSUE TITLE
Dark Document mode for Spreadsheets

### ISSUE THREAD

**Issue by thisisartman** [ONLYOFFICE/DesktopEditors#1736] opened 2024-11-27 02:04 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Add a dark document mode similar to what is present in the Document, PDF Editors.

**Comment by Rita-Bubnova** [comment] 2024-11-29 09:49
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1944.

**Closed by Rita-Bubnova** 2024-11-29 09:49 UTC
