### ISSUE TITLE
Feature request: Support to accentuation in Ubuntu

### ISSUE THREAD

**Issue by danielmaurer** [ONLYOFFICE/DesktopEditors#64] opened 2017-09-22 21:48 UTC
Please add support to accentuation in Ubuntu, it is essential for writes documents in Portuguese Language and others.

**Comment by ShockwaveNN** [comment] 2017-09-25 06:54
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/29

**Closed by ShockwaveNN** 2017-09-25 06:54 UTC
