### ISSUE TITLE
Linux: Use native file picker

### ISSUE THREAD

**Issue by joewood9364** [ONLYOFFICE/DesktopEditors#1616] opened 2024-06-25 21:38 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I have noticed on KDE Flatpak version that the KDE file picker inst used when saving and some old gnome one is used instead. Would be better to use the native one for each desktop environment (I think they call it xdg portal or something).

**Comment by matveevms** [comment] 2024-06-28 10:17
Hello, @joewood9364 
For now, you can enable the desired dialog using the `--xdg-desktop-portal=default` option when starting the application.
`--xdg-desktop-portal` - the parameter is saved for subsequent launches of the application

**Comment by Rita-Bubnova** [comment] 2024-06-28 10:20
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/712.

**Closed by Rita-Bubnova** 2024-06-28 10:20 UTC
