### ISSUE TITLE
Cannot enter text in text document after navigating away and back to the window

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DesktopEditors#921] opened 2022-05-17 05:42 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

Windows 11--Version 10.0.22000 Build 22000

### Expected Behavior

When I open a text document and type, it should capture text and display it on the screen. See steps to reproduce for more detail.

### Actual Behavior

After working on a docx file, navigating away and navigating back, it does not capture text and display it on the screen. 

You need to actively click into the document each time you return to it for text to be captured. Previously you could simply navigate back to the editor and it would pick up your text again, no clicking into the editor necessary. 

See steps to reproduce for more detail.

### Reproduction Steps

1. Open a text document saved as a .docx file (others might do it too, I work with .docx). 
2. Enter text into the document. 
3. Switch to another application (ie a browser, etc.). 
4. Switch back to onlyoffice. 
5. Try typing something. It doesn't register. 

### Additional information

Computer and Windows version are both pretty standard. No other programs running that could interfere (just Brave).

**Comment by Rita-Bubnova** [comment] 2022-05-18 12:56
Hello, @WhoStoleMyFries.
Could you attach a video to demonstrate the problem?
Are you clicking on the windows in step 3?

I checked the issue on ONLYOFFICE Desktop Editors versions 7.0 and 7.1 (Windows 11), but the behavior hasn't changed.

**Comment by WhoStoleMyFries** [comment] 2022-05-22 18:28
I'm not sure how a video would help. It's me opening the document, typing,
switching to a web browser and switching back. Nothing looks different, it
just doesn't recognize any input.

Try it with a long document (one I'm working on is 40 pages)

**Comment by WhoStoleMyFries** [comment] 2022-05-22 18:36
Hey I just found another way to generate the bug. Open 2 documents. Switch
from one to the other and back. Try typing. It won't work.

I suspect the bug is in whatever focuses a specific doc

**Comment by Rita-Bubnova** [comment] 2022-05-27 09:27
@WhoStoleMyFries, sorry I can't help if you don't answer my questions.
How do you switch to another application? Are you clicking on the new window, when switch to another application?

Could you record a video showing mouse clicks and keyboard shortcuts (if you use them)?

**Comment by WhoStoleMyFries** [comment] 2022-05-27 09:43
I did answer your questions. You should reread it. Make sure you read both
responses. Getting upset at someone helping you diagnose a bug is neither
helpful nor productive.

I use a mouse to click into other applications. The issue is replicable
with any situation where the document loses focus. This includes, but is
not limited to:
- switching to a different document within the editor and back
- clicking the minus sign for the application and re-opening it via the
icon in the windows navigation bar at the bottom of the screen
- selecting another application in the navigation bar at the bottom of the
screen and then returning by selecting only office.
- putting the computer to sleep without minimizing the application (I
closed the lid of my PC) and re-entering the os

And no, I am not going to go to the trouble of setting up video capture for
you. The text description is more than enough for you to have your QA
replicate this. As a developer I rarely see bug reports this detailed. If
you can't work with this it's on you.

**Comment by matveevms** [comment] 2022-05-27 11:24
This is known issue - 56672 in our private issue tracker.
Thank you for report.

**Comment by HectorB-2020** [comment] 2022-10-17 09:44
I've a gut feeling that these two issues are related - #1052.

**Comment by Rita-Bubnova** [comment] 2024-05-07 11:20
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-05-07 11:20 UTC
Labels: confirmed-bug
