### ISSUE TITLE
GTK Theme implemented with OnlyOffice window frame

### ISSUE THREAD

**Issue by matissime** [ONLYOFFICE/DesktopEditors#745] opened 2021-10-29 11:51 UTC
**Do you want to request a *feature* or report a *bug*?**
A feature
**What is the current behavior?**
OnlyOffice windows is not using the GTK theme in a gnome desktop but a own window theme that look like Windows.
**Feature requested**
Being able to choose if we want to integrated the window style of OnlyOffice with our own GTK theme that the current desktop environment use.
**Operating System:**
Ubuntu 20.04 with GNOME 40
**Example**
My current GTK Theme have a window frame that look like this (check the close button as a reference) :
![GTKWindowFrame](https://user-images.githubusercontent.com/28954962/139429279-f09a98c6-09a1-4c17-9f61-2afbc928b8ed.png)
And i suggest to implement the option to let the user to integrate OnlyOffice window with the current GTK Theme
![OnlyOfficeWindowFrameTheme](https://user-images.githubusercontent.com/28954962/139429284-8bbc6000-8626-4e13-a462-05151dea5287.png)

I hope to been understood, if you need more explanation do not hesitate :)

**Comment by janxkoci** [comment] 2021-11-15 14:41
I think this is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/216

**Comment by matveevms** [comment] 2023-08-14 13:04
Hi, @matissime.
Indeed, this is a duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/216. To inherit windows, you can use the desktop with the `--system-title-bar flag`

**Closed** 2023-08-14 13:05 UTC
Labels: duplicate

**Comment by matveevms** [comment] 2024-05-06 14:03
Yes, at the moment, this is one of the options to inherit system windows. But if you use this flag once when running through the console, the window view will be preserved for subsequent launches too.
