### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by vatterspun** [ONLYOFFICE/DesktopEditors#112] opened 2018-05-31 13:54 UTC
I thought someone had already posted about this but I can't find it.  Could someone point me to the Windows build instructions?  Thanks.

**Comment by ShockwaveNN** [comment] 2018-05-31 14:08
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/4

**Closed by ShockwaveNN** 2018-05-31 14:08 UTC

**Comment by vatterspun** [comment] 2018-05-31 19:01
Sorry, I'm not trying to harp on this, I tried several different ways to find the topic and just couldn't find it.  Thanks for the pointer.
