### ISSUE TITLE
Dark Mode support

### ISSUE THREAD

**Issue by rafadesign** [ONLYOFFICE/DesktopEditors#620] opened 2021-05-11 23:47 UTC
Onlyoffice could support dark mode, in linux I use dark mode and it is uncomfortable to use onlyoffice in light mode

**Comment by ShockwaveNN** [comment] 2021-05-12 06:02
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1008

**Closed by ShockwaveNN** 2021-05-12 06:02 UTC

**Comment by cipricus** [comment] 2021-11-22 13:02
This is a dark GUI theme but note a full-dark mode with dark/custom page background like MSOffice and LO have.
