### ISSUE TITLE
Desktop Editor starting window shows cropped content and crashes when trying to fit to screen

### ISSUE THREAD

**Issue by frnprt** [ONLYOFFICE/DesktopEditors#847] opened 2022-02-15 15:48 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.0.0

### Expected Behavior

The main window should start normally, with scaled inner content or scrollbars to navigate the cropped content.
When double clicking on the top bar, the app should go fullscreen, resizing according to the display size and resolution.

### Actual Behavior

The main window starts cropped w/o any way to be navigated.
When trying to go fullscreen via double clicking the top bar, the app crashes.

### Reproduction Steps

Open the app and try to go fullscreen with a double click on top bar.

### Additional information

I have two screens, the main one is 2560x1440 and the other is 1920x1080.
If it can help in any way, I also set the Windows UI scale to 150% in the display settings.

GIF screenshot of the crashing process (here I have just opened the app):
[Link](https://cdn.imgchest.com/files/myd5cxjdm4b.gif)

**Comment by ShockwaveNN** [comment] 2022-02-16 14:07
Hi, this is strange case

Could you provide some more info about your hardware, except screen resolutions?

Is this a laptop or desktop? Maybe some strange/rare videocard?

**Comment by frnprt** [comment] 2022-02-16 14:22
Hi! Thanks for coming by.
Of course, here are the main specs.

• OS: Windows 10 Pro, 10.0.19043
• CPU: Intel Core i7-8700
• GPU: NVIDIA GeForce GTX 1080 (with latest Driver version)
• Desktop environment, 2 monitors:
- Main monitor - BenQ BL2420-T 2560x1440, 60Hz
- Secondary monitor (which is set as an extension of the first) - Asus VH228D 1920x1080, 60Hz

The UI scale to 150% is applied to both the screens.

**Comment by frnprt** [comment] 2022-02-16 14:27
Currently set to Auto, but it's worth noting that I've tried every other option and, even if it does change something (e.g. the text is smaller or bigger) the window is still cropped in the same way and still crashes when I try to go fullscreen.

**Comment by ShockwaveNN** [comment] 2022-02-16 14:29
Thanks for info, we'll try to localize it

**Comment by LuckySpecialist** [comment] 2022-02-17 09:33
Hi @frnprt!
I can't reproduce your problem, although I have a similar configuration.
Monitors 4K - 24" (main) and FHD- 23", the same processor, GTX 1650, 16 GB of RAM.
On the attached GIF, I see you have an unusual height of the main window title. In addition, when you double-click on the title, part of the window flies away, it seems, to the second monitor and then the application crashes.
Can you attach a screenshot of how your displays are located in the settings, relative to each other.
It would also be interesting to look at the error, recorded in the system log after the crash. You can view it by running the command (Win+R):
`eventvwr.msc /c:Application`

**Comment by frnprt** [comment] 2022-02-17 11:47
> Hi @frnprt! I can't reproduce your problem, although I have a similar configuration. Monitors 4K - 24" (main) and FHD - 23", the same processor, GTX 1650, 16 GB of RAM (Win 10 Pro 21H2 19044.1526). On the attached GIF, I see you have an unusual height of the main window title. In addition, when you double-click on the title, part of the window flies away, it seems, to the second monitor and then the application crashes. Can you attach a screenshot of how your displays are located in the settings, relative to each other? It would also be interesting to look at the error, recorded in the system log after the crash. You can view it by running the command (Win+R): `eventvwr.msc /c:Application`


Hi Lucky, thanks for taking the time!

To answer the first implicit question: no, the window doesn't fly to the second monitor. In the GIF it was being executed there for privacy purpose (I didn't want to capture the main screen).
If you need a screenshot of the main monitor I can provide it to you, though.
The exact sequence of crashing is: 
1) I open the app. The app window is cropped as you can see in the GIF.
2) I double click on the top bar to go fullscreen.
3) The window briefly (1 or 2 seconds) binds itself to the top left corner of the screen I'm working on (either the main or the second, the behaviour is the same)
4) The app crashes.

Proceeding to the second request, here is a screenshot of the disposition config:

<img width="765" alt="Cattura" src="https://user-images.githubusercontent.com/44530535/154469787-3a82ef89-a678-4dd4-9699-9eae36373a05.PNG">

Finally, the Event Viewer generates 2 errors when the app crashes, one immediately after the other.
I exported them in .evtx format (the native language is italian, but I should have managed to include the EN (USA) config too).
Let me know if you need the raw text instead.
The password of the archive is your github username.
FILE:
[Events.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/8088351/Events.zip)

**Comment by LuckySpecialist** [comment] 2022-02-17 12:44
It looks like I was able to reproduce the problem. It will take me some time to describe the scenario and pass the problem to the developers.

**Comment by LuckySpecialist** [comment] 2022-02-17 13:04
It was possible to repeat the problem only once, it does not work anymore yet.
I think the key point here is to understand how you managed to get such a cropped window.
For me, it always expands to the minimum (not cropped).
We need some kind of sequence of actions that will lead to such an effect.

**Comment by frnprt** [comment] 2022-02-17 13:26
I tried recording the whole process (from opening to crashing) on the main screen this time, I hope it helps.
Let me know if there is anything else I can do.

Screen Capture:
https://user-images.githubusercontent.com/44530535/154490545-6c687a90-58cf-4e96-a8ed-6773d75557a2.mp4

**Comment by frnprt** [comment] 2022-02-17 13:50
When trying to manually resize, this is the result:
https://user-images.githubusercontent.com/44530535/154495053-0c8c3b85-c699-4858-8fba-5fab2ea36eab.mp4

**Comment by LuckySpecialist** [comment] 2022-02-17 14:15
Reinstalling the application does not change the situation, does it always start cropped?

**Comment by frnprt** [comment] 2022-02-17 14:21
Correct, I've tried reinstalling multiple times (and across multiple releases, this happened in 6.x too).

**Comment by LuckySpecialist** [comment] 2022-02-17 14:45
Try to force the editor to run the interface scale 100%.
This can be done by running the command (Win+R):
`"C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe" --force-scale=1`

**Comment by LuckySpecialist** [comment] 2022-02-17 17:01
Can you record a video of what the application looks like [with a forced scale of 100%](https://github.com/ONLYOFFICE/DesktopEditors/issues/847#issuecomment-1043025732) to show it to developers?
You can also show what happens when you try to resize the window.
Thanx.

**Comment by maxkadushkin** [comment] 2022-02-17 19:05
Hi, @frnprt ! could you share the video where you applying different ui scaling on page Settings?

**Comment by maxkadushkin** [comment] 2022-02-17 19:06
without --force-scale=1 flag

**Comment by frnprt** [comment] 2022-02-17 19:29
> Hi, @frnprt ! could you share the video where you applying different ui scaling on page Settings?

Hello max, glad you joined the topic!
Of course, here it is:
https://user-images.githubusercontent.com/44530535/154556185-19cb3d58-4560-42bb-9939-a819b2f81b4f.mp4

**Comment by maxkadushkin** [comment] 2022-02-22 18:02
sorry for the delay
could you make some logs?
download portable version of app with logs by that [link](https://bit.ly/3sbiIci),
uncompress it, launch DesktopEditors.exe and do the same like in last video. 
app.log will be created in app root directory. share that log with us to [support@onlyoffice.com](mailto:support@onlyoffice.com)

**Comment by frnprt** [comment] 2022-02-22 18:30
Hello again,
I tried downloading the package and doing as told but DesktopEditors.exe won't open. A weird error appears:

<img width="310" alt="Capture" src="https://user-images.githubusercontent.com/44530535/155196080-b2680ff9-0cc7-455b-a147-ca1e95ec4040.PNG">

**Comment by maxkadushkin** [comment] 2022-02-22 19:57
I've fixed error messsage. [try it](https://bit.ly/36yXyMY)

**Comment by frnprt** [comment] 2022-02-22 20:34
Done. I will share it here, but please be welcome to tell me if you specifically need it to be sent to the mail you said and (in that case) if I should write some specific object in it.
Thank you for your work!

[app.log](https://github.com/ONLYOFFICE/DesktopEditors/files/8119987/app.log)

**Comment by maxkadushkin** [comment] 2022-02-23 21:41
Hello, @frnprt 
added more logs. [try it](https://bit.ly/3IfEIs1), pls

**Comment by frnprt** [comment] 2022-02-24 00:18
Here they are:
[app.log](https://github.com/ONLYOFFICE/DesktopEditors/files/8128675/app.log)

**Comment by maxkadushkin** [comment] 2022-02-24 21:16
it seems i've reproduced similar bug
do you have something from the following in your system's enviroment variables?
QT_DEVICE_PIXEL_RATIO, QT_SCALE_FACTOR, QT_AUTO_SCREEN_SCALE_FACTOR, QT_SCREEN_SCALE_FACTORS

**Comment by frnprt** [comment] 2022-02-25 10:19
I have indeed.
Of the ones you mentioned, it seems there is only QT_DEVICE_PIXEL_RATIO and it is set to "auto".

**Comment by maxkadushkin** [comment] 2022-02-25 11:14
try to rename it, relogin to system to apply changes and launch the app after

**Comment by frnprt** [comment] 2022-02-25 11:30
> try to rename it, relogin to system to apply changes and launch the app after

It worked!
I had to rename the QT_DEVICE_PIXEL_RATIO in the User variables too, but in the end it worked!
Now OnlyOffice is running very smoothly, with proper window size/scaling and (most important) without crashes.
BTW this also solved some strange behaviours in other apps that use Qt (e.g. in TeamSpeak some icons appeared blurred, now they don't anymore).

Thank you a lot for the hard work on this!

**Comment by maxkadushkin** [comment] 2022-02-26 12:57
it's interesting what the app wrote down and use this variable

**Comment by frnprt** [comment] 2022-03-04 11:08
Hey, sorry for the delay!

I haven't the foggest idea about what could have written those values.
This instance of Windows goes back in time quite a lot, so it could be anything I previously installed.
Anyway, so far so good w/o the User and System variables.

**Comment by ShockwaveNN** [comment] 2022-03-09 08:51
I think I'll close this issue if the problem is resolved for you, if you find a reason some app change ENV variables - feel free to comment

**Closed by ShockwaveNN** 2022-03-09 08:51 UTC
