### ISSUE TITLE
Animated Gif Support in Presentations 

### ISSUE THREAD

**Issue by T-Herrmann-WI** [ONLYOFFICE/DesktopEditors#1105] opened 2022-11-11 17:20 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

We are using animated Gif's to record short explains as part tutorials for e.g.. MS Powerpoint support animated Gif files since a while. OnlyOffice don't support it right now and much worse it kills animated Gif's inside of a presentation by saving it. We use Onlyoffice in Webframework with confluence and inside I a web browser it's very annoying that there is no animated GIF support. 

I will hope this feature will come soon part of the presentation part of OnlyOffice.

Thank you

**Comment by ShockwaveNN** [comment] 2022-11-14 07:30
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1534

**Closed by ShockwaveNN** 2022-11-14 07:30 UTC

**Comment by chuchoda** [comment] 2023-11-20 15:55
Best regard;
Desktop editors allow .gif images to be inserted, but their movements are not reproduced (the images remain static), as Microsoft Office and Libre Office do. I am a teacher and I constantly use .gif images in different text documents, spreadsheets and presentations.
I appreciate you promptly resolving this error.
