### ISSUE TITLE
More Page Number Options 

### ISSUE THREAD

**Issue by Sanjay-Khadka** [ONLYOFFICE/DesktopEditors#1479] opened 2024-01-27 13:11 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Users Should have the option to use Roman numerals(i, ii, iii, iv, etc) for their page numbers. This feature will be very useful in formal documents, academic papers, or any context where alternative page numbering systems are required which will help solidify it as a better and an open source alternative to ms word/ms office.

**Comment by Rita-Bubnova** [comment] 2024-01-29 09:15
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1251.

**Closed by Rita-Bubnova** 2024-01-29 09:15 UTC
