### ISSUE TITLE
A bug with alt+space layout switching

### ISSUE THREAD

**Issue by Akergez** [ONLYOFFICE/DesktopEditors#793] opened 2021-12-21 17:47 UTC
When I switch keyboard layout with alt+space, the text stops printing until I click on the end of the line.

Fedora 35, Gnome, Wayland, desktop client from flathub.

**Comment by ShockwaveNN** [comment] 2021-12-21 18:27
Moving this issue to DesktopEditors repo, since by content it's not related with DocumentServer

@matveevms Please take a look at that issue
If this is reproduces only on flatpak image - I'll move it to correct repo

**Comment by matveevms** [comment] 2021-12-23 12:30
Hello, @Akergez 
This problem does not recur on my systems. Perhaps this keyboard shortcut is being used for something else on your system?

**Comment by ShockwaveNN** [comment] 2022-03-24 09:03
This issue was closed due to no response.

**Closed by ShockwaveNN** 2022-03-24 09:03 UTC
