### ISSUE TITLE
Provide overview of tracked changes

### ISSUE THREAD

**Issue by allefeld** [ONLYOFFICE/DesktopEditors#1643] opened 2024-07-17 20:18 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Problem: I find it hard to get an overview over all tracked changes in a document, especially small changes like adding or deleting a comma.

I find the presentation of tracked changes less intrusive as in Word, which in principle is good, because it distracts less from the actual text. However, it makes it hard if one needs to get an overview of all changes, short of moving through the document stepwise with the "Previous" & "Next" buttons.

Providing such an overview could be achieved by showing all the balloons for all changes, e.g. as a fourth Display Mode, "Markup and persistent balloons". Or it could have the form of a Changes panel, similar to the existing Comments panel.

**Comment by XDmitryK** [comment] 2024-08-13 10:49
@allefeld Hi
This is known issue #47351

**Comment by Rita-Bubnova** [comment] 2024-08-13 12:04
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2729.

**Closed by Rita-Bubnova** 2024-08-13 12:04 UTC
