### ISSUE TITLE
Copying an image into another presentation results in an empty image

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#1240] opened 2023-03-07 18:39 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.0

### Expected Behavior

It should be possible to copy the image in the attached presentation into another presentation.

[bug-OO-copy-image.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/10912889/bug-OO-copy-image.pptx)

### Actual Behavior

Copying the image of the attached presentation into another presentation results in an empty image.

### Reproduction Steps

Steps to reproduce:
- open the attached .pptx file
- select the image and type CTRL-C
- open an empty presentation
- copy the image with CTRL-V
- => the image is empty

**Comment by matveevms** [comment] 2023-03-27 10:31
Hello, @parrenin 
I can confirm - this is bug, issue Bug 61808 in our issue tracker.
Thank you for report.

**Comment by parrenin** [comment] 2023-06-16 09:18
I think this bug is now fixed in 7.4.0.

**Comment by matveevms** [comment] 2023-08-07 13:34
Hi, @parrenin 
The problem is solved for local files, but unfortunately still present when working in the cloud. 
We'll let you know when the problem is fully fixed.

**Comment by Rita-Bubnova** [comment] 2024-10-22 14:23
DesktopEditors v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-10-22 14:23 UTC
Labels: confirmed-bug, fixed-release
