### ISSUE TITLE
Pasting an image does not preserve the aspect ratio

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#545] opened 2021-01-05 09:05 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
On Linux, I copied an image from evince, the pdf viewer.
Then I pasted the image in OO (document editor).
I found that the aspect ratio of the image is damaged, with the image far too stretched horizontally.
See attached screenshot.
![Capture d’écran de 2021-01-05 10-04-35](https://user-images.githubusercontent.com/4678272/103627139-79ccdb00-4f3d-11eb-9417-1e41e5bf8d0b.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
On Linux, copy an image and paste it in OO Document editor.

**What is the expected behavior?**
The aspect ratio should be preserved.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Debian Linux 11 Bullseye, DestopEditors 6.1.0

**Comment by HectorB-2020** [comment] 2021-01-05 10:16
Indeed! 
I confirm the same behavior on Windows as well.
Windows 10 20H2
Only Office 6.1.0.90

![OO12](https://user-images.githubusercontent.com/64358003/103634357-fff61b00-4f57-11eb-8c96-61b37c9ea762.png)

**Comment by Rita-Bubnova** [comment] 2021-01-12 13:21
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/221.

**Closed** 2021-01-12 13:47 UTC
