### ISSUE TITLE
Inserting images via Drag and drop not working on Manjaro with KDE

### ISSUE THREAD

**Issue by maagenta** [ONLYOFFICE/DesktopEditors#1268] opened 2023-04-20 02:25 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.3.50

### Expected Behavior

Drag and drop images, then attach it in the document.

### Actual Behavior

I have Onlyoffice 7.3.3.50 on Manjaro with KDE Plasma 5.26.4.

The onlyoffice package was installed via pacman.

When I Drag and Drop appears the cursor with the no symbol.

![Screenshot_20230419_162328-1](https://user-images.githubusercontent.com/126840451/233241426-869c8bdc-df90-4659-85ce-1b57711185d8.png)

**Comment by Rita-Bubnova** [comment] 2023-04-21 10:52
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/275.

**Closed** 2023-04-21 14:32 UTC
Labels: duplicate
