### ISSUE TITLE
Allow for animating by, line, word and symbol in presentation

### ISSUE THREAD

**Issue by moritz-t-w** [ONLYOFFICE/DesktopEditors#1529] opened 2024-03-15 15:15 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I would like to animate text boxes paragraph by line by line, word by word and symbol by symbol, like [in MS Powerpoint](https://support.microsoft.com/en-us/office/animate-or-make-words-appear-one-line-at-a-time-cfb5ebdc-90cf-4324-8933-874c7c840175)

**Comment by Rita-Bubnova** [comment] 2024-03-18 11:47
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1962.

**Closed by Rita-Bubnova** 2024-03-18 11:47 UTC
