### ISSUE TITLE
Ctrl+Shift+UP-arrow inserts random TAB. Does not select Line

### ISSUE THREAD

**Issue by Juan-132** [ONLYOFFICE/DesktopEditors#1550] opened 2024-04-09 17:27 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

 8.0.1.31

### Expected Behavior

This bug happens on Windows 11.

Expected behavior:
The new TAB '->" should NOT be inserted.
The "Line below" should be selected in it's entirely.

### Actual Behavior

A TAB "->" is inserted after the "Line above" and the cursor is placed exactly above the previous position.

### Reproduction Steps

Steps to reproduce:
1. Enter text like in screencapture
2. Navigate cursor to end of line below
3. Press: Ctrl+Shift+UP-arrow

https://github.com/ONLYOFFICE/DesktopEditors/assets/59505296/fe9248d0-7029-4757-a990-0af5ab4de8f8

**Comment by Rita-Bubnova** [comment] 2024-04-16 13:44
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2595.

**Closed by Rita-Bubnova** 2024-04-16 13:44 UTC

**Comment by TatianaKirillova** [comment] 2024-04-23 12:21
@Juan-132 I'm happy to report that the issue is fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/dfbfad609c2a8762cf931939bffb8d54eb3b9d22) and will be included in the next release. Don't miss updates)
