### ISSUE TITLE
english words ending in -n't are shown as spelling errors

### ISSUE THREAD

**Issue by fastrizwaan** [ONLYOFFICE/DesktopEditors#1045] opened 2022-10-11 00:49 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.0.204

### Expected Behavior

words like aren't, isn't, doesn't, etc... should not be shown as spelling errors..

### Actual Behavior

Here's the list of english words whcih ends in `n't` like `couldn't` `aren't` etc.
https://en.wiktionary.org/wiki/Category:English_terms_suffixed_with_-n%27t

### Reproduction Steps

1. Create New document
2. Type `isn't` `couldn't` `aren't` etc. (just copy paste list from https://en.wiktionary.org/wiki/Category:English_terms_suffixed_with_-n%27t)
3. Many English words are shown as spelling errors.

**Comment by ShockwaveNN** [comment] 2022-10-11 07:13
Hi, this is a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/576

**Closed** 2022-10-11 07:13 UTC
