### ISSUE TITLE
Add Web Layout like in MS Office

### ISSUE THREAD

**Issue by KlimaRitter** [ONLYOFFICE/DesktopEditors#779] opened 2021-12-06 11:32 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

There is no way to **change between different Editor Views** like in other Office suits.
Here is how this is implemented in MS Office:

Normal Layout:
![figure-a](https://user-images.githubusercontent.com/54468603/144838330-758e51e3-9306-42c4-b8f8-d0d2415dd327.jpg)

Web Layout:
![figure-b](https://user-images.githubusercontent.com/54468603/144838339-e6294045-93d8-4ec0-bdda-a93ea527e43b.jpg)

It is specially useful if you are trying to write in split screen, and you can fit all the text on one half of your screen, without needing to move the view all the time or to change to a small scaling.

**Comment by ShockwaveNN** [comment] 2021-12-06 12:44
I think it's a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1446

DocumentServer is our base product and currently this feature is not implemented

**Closed by ShockwaveNN** 2021-12-06 12:44 UTC
