### ISSUE TITLE
Program crashes when trying to print a page

### ISSUE THREAD

**Issue by ximian** [ONLYOFFICE/DesktopEditors#1029] opened 2022-09-26 21:04 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.0-204

### Expected Behavior

The Printer prints the page after clicking "Print" in a printing popup window.

### Actual Behavior

Program crashes.
I get a Memory protection violation error in the terminal.

### Reproduction Steps

* Open an XLSX file.
* Hit Ctrl + P to show the Printing dialog
* Change page layout from portrait to landscape
* Change margins to fit a page properly (0,7cm on top and bottom and 0,9cm on the left)
* Click on the Print button
* Click on the Print button in the popup window
* Crash

### Additional information

My system is Pop!_OS 22.04 LTS. On the previous version of OnlyOffice, everything worked as expected.

**Comment by PDXUser** [comment] 2022-09-30 00:39
I have the same issue using Arch Linux which has worked flawlessly before with OnlyOffice.  This is a relatively fresh install of "EndeavourOS" which is Arch with a little extra behind it.  Nonetheless, the package is built from the .deb file so I think it may be related to the .deb perhaps. 

In any event, this is the message from terminal if you run it from there:

/usr/bin/onlyoffice-desktopeditors %U
QLayout: Attempting to add QLayout "" to CTabBarWrapper "tabWrapper", which already has a layout
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1867, resource id: 104857752, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1872, resource id: 104857752, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1875, resource id: 104857752, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1911, resource id: 104857752, major code: 130 (Unknown), minor code: 3
Segmentation fault (core dumped)

Running this as root does not cause an issue, except when graphics (clipart only) is included.  Other printing is flawless.

**Comment by LuckySpecialist** [comment] 2022-10-04 12:54
Hi @ximian!
The problem you have repeats on any XLSX file or on some specific one only. If possible, attach the file.
Are you trying to print to a real printer or to a file (for example, a PDF printer)?
Please attach a video with a demonstration of the problem, if possible.

**Comment by ximian** [comment] 2022-10-05 08:13
Hi @LuckySpecialist 
It seems that the problem only occurs when at least one picture is inserted into a spreadsheet (I've attached an example of a file that causes the problem).
I'm trying to print to an actual printer (HP LaserJet 1320n connected by a network to be exact) but printing to a PDF printer gives the same result.

Example file:
[Skoroszyt1.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/9713820/Skoroszyt1.xlsx)

Screen record with a demonstration of the problem:
[Nagranie ekranu z 05.10.2022 10:07:06.webm](https://user-images.githubusercontent.com/4366946/194012631-a51c86fb-2527-472d-a688-a0efe67748c7.webm)

**Comment by LuckySpecialist** [comment] 2022-10-05 09:44
I confirm that the problem is present on linux systems (it does not repeat on windows). It has already been fixed and will be included in the next update of the application. The exact release date has not yet been determined.
Thanks for the feedback!

**Comment by VasilisKos** [comment] 2022-10-05 10:38
Yeah, same happens on Linux Mint 21, with version 7.2 installed from deb file. Both when trying to print on physical prtinter or pdf file. Hope it really is fixed ASAP, cause now I can't print at all!

**Comment by ximian** [comment] 2022-10-05 11:17
> Yeah, same happens on Linux Mint 21, with version 7.2 installed from deb file. Both when trying to print on physical prtinter or pdf file. Hope it really is fixed ASAP, cause now I can't print at all!

Temporarily You can downgrade to [7.1.1](https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/v7.1.1)

**Comment by jack0tr** [comment] 2022-10-20 05:12
Im a new user of onlyoffice and use it on windows 10, both on desktop and laptop CTD when printing a pdf to a physical printer, docs and spreadsheets print just fine

**Comment by VasilisKos** [comment] 2022-10-20 05:14
> Im a new user of onlyoffice and use it on windows 10, both on desktop and laptop CTD when printing a pdf to a physical printer, docs and spreadsheets print just fine

We've all mentioned above that the bug is on Linux only...

**Comment by jack0tr** [comment] 2022-10-20 13:13
And im mentioning that is present on windows too, or do i have to submit a new issue?

**Comment by ShockwaveNN** [comment] 2022-10-20 13:16
@jack0tr I think it's better to create a new one, if we determine the source as same as here we're duplicate it, but right now I cannot tell it

**Comment by LuckySpecialist** [comment] 2022-10-21 18:51
Hi @ximian @PDXUser @VasilisKos!
This problem has been fixed in fresh hotfix [release](https://github.com/ONLYOFFICE/DesktopEditors/releases) 7.2.1.
Please, check and write the result whether everything works correctly for you.
Thanks.

**Comment by ShockwaveNN** [comment] 2022-10-21 18:56
DesktopEditors v7.2.1 are released and this problem should be fixed

I'll close this issue but feel free to comment if got any troubles

**Closed by ShockwaveNN** 2022-10-21 18:56 UTC
Labels: bug, fixed

**Comment by ximian** [comment] 2022-10-22 08:24
> Hi @ximian @PDXUser @VasilisKos! This problem has been fixed in fresh hotfix [release](https://github.com/ONLYOFFICE/DesktopEditors/releases) 7.2.1. Please, check and write the result whether everything works correctly for you. Thanks.

Indeed it works fine now.

**Comment by w-vi** [comment] 2023-02-16 08:51
We see this behaviour again. Any attempt to print results in a crash after the system print settings pop up is showed. This is the result we see in terminal.
```
$ onlyoffice
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1418, resource id: 90177599, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1421, resource id: 90177599, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1424, resource id: 90177599, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1446, resource id: 90177599, major code: 130 (Unknown), minor code: 3
Neúspěšně ukončen (SIGABRT) (core dumped [obraz paměti uložen])
```
System Information:

ONLYOFFICE Desktop Editors version 7.3.0.184
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 5.15.93-1-MANJARO (64-bit)
Graphics Platform: X11

**Comment by w-vi** [comment] 2023-02-21 09:16
@LuckySpecialist Bringing this to your attention as you were responding to this thread before.

**Comment by LuckySpecialist** [comment] 2023-03-05 21:35
Hi @w-vi!
If you are sure that the problem is on our side, then put it in a separate topic, since it is not related to the current one. You can add more details about your environment and a video demonstrating the problem there.
By the way, it was not possible to reproduce the problem on our systems. Tested on Manjaro Linux with 5.15.93-1-MANJARO kernel (for AUR/SNAP package) and Arch Linux with 6.1.15-1-lts kernel (for AUR package).
Thanks for understanding.

**Comment by LuckySpecialist** [comment] 2023-03-06 12:07
Thanks for the information, it will take some time to find a similar configuration and reproduce the problem.

**Comment by oe3gwu** [comment] 2023-03-29 18:59
I got a similar problem. But it also crashes when trying to print a empty page created from onlyoffice. No matter if Spreadsheet or Wordprocessor.

```
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1456, resource id: 100663368, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1459, resource id: 100663368, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1462, resource id: 100663368, major code: 130 (Unknown), minor code: 3
```
