### ISSUE TITLE
When moving the cursor outside the document - stops printing text

### ISSUE THREAD

**Issue by Xazev** [ONLYOFFICE/DesktopEditors#940] opened 2022-05-31 03:12 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1.0.215

### Expected Behavior

Continue typing text regardless of cursor position

### Actual Behavior

https://user-images.githubusercontent.com/11159920/171084772-034e83d0-99dc-4535-bd8f-b6b3753376ed.mp4

### Reproduction Steps

1. Open document
2. Place it on the floor of the screen
3. Switch to another app
4. Return to document
5. Start typing text
6. Move the mouse cursor outside the document
7. Try to type text

### Additional information

Checked in KDE, Cinnamon.
This is not observed in other office suites.

**Comment by ShockwaveNN** [comment] 2022-05-31 07:38
Hi, this is duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/743

**Closed by ShockwaveNN** 2022-05-31 07:38 UTC
